"""
This type stub file was generated by pyright.
"""

import torch
from collections.abc import Generator
from tensordict import TensorDict
from rsl_rl.modules import HiddenState

class RolloutStorage:
    """Storage for the data collected during a rollout.

    The rollout storage is populated by adding transitions during the rollout phase. It then returns a generator for
    learning, depending on the algorithm and the policy architecture.
    """
    class Transition:
        """Storage for a single state transition.

        This class is populated incrementally during the rollout phase and then passed to
        :meth:`RolloutStorage.add_transition` to record the data.
        """
        def __init__(self) -> None:
            """Initialize an empty transition container."""
            ...
        
        def clear(self) -> None:
            """Reset all transition fields to None."""
            ...
        
    
    
    class Batch:
        """A batch of data yielded by the rollout storage generators.

        This class provides named access to mini-batch fields. Fields are optional to support different training modes
        (RL vs distillation) and architectures (feedforward vs recurrent).
        """
        def __init__(self, observations: TensorDict | None = ..., actions: torch.Tensor | None = ..., values: torch.Tensor | None = ..., advantages: torch.Tensor | None = ..., returns: torch.Tensor | None = ..., old_actions_log_prob: torch.Tensor | None = ..., old_distribution_params: tuple[torch.Tensor, ...] | None = ..., hidden_states: tuple[HiddenState, HiddenState] = ..., masks: torch.Tensor | None = ..., privileged_actions: torch.Tensor | None = ..., dones: torch.Tensor | None = ...) -> None:
            """Initialize a batch container over rollout data."""
            ...
        
    
    
    def __init__(self, training_type: str, num_envs: int, num_transitions_per_env: int, obs: TensorDict, actions_shape: tuple[int, ...] | list[int], device: str = ...) -> None:
        """Allocate rollout buffers for a specific training mode and batch shape."""
        ...
    
    def add_transition(self, transition: Transition) -> None:
        """Add one transition to the storage at the current step index."""
        ...
    
    def clear(self) -> None:
        """Reset the write cursor for the next rollout."""
        ...
    
    def generator(self) -> Generator[Batch, None, None]:
        """Yield per-timestep batches for distillation training."""
        ...
    
    def mini_batch_generator(self, num_mini_batches: int, num_epochs: int = ...) -> Generator[Batch, None, None]:
        """Yield shuffled flat mini-batches for feedforward RL updates."""
        ...
    
    def recurrent_mini_batch_generator(self, num_mini_batches: int, num_epochs: int = ...) -> Generator[Batch, None, None]:
        """Yield trajectory mini-batches with masks and recurrent hidden states."""
        ...
    


