"""
This type stub file was generated by pyright.
"""

from tensordict.nn.common import TensorDictModule, TensorDictModuleBase, TensorDictModuleWrapper, WrapModule, dispatch, make_tensordict
from tensordict.nn.distributions import AddStateIndependentNormalScale, CompositeDistribution, NormalParamExtractor, OneHotCategorical, TruncatedNormal, rand_one_hot
from tensordict.nn.ensemble import EnsembleModule
from tensordict.nn.functional_modules import get_functional, is_functional, make_functional, repopulate_module
from tensordict.nn.params import TensorDictParams
from tensordict.nn.probabilistic import InteractionType, ProbabilisticTensorDictModule, ProbabilisticTensorDictSequential, set_interaction_type
from tensordict.nn.sequence import TensorDictSequential
from tensordict.nn.utils import add_custom_mapping, biased_softplus, inv_softplus, mappings, set_skip_existing, skip_existing
from .common import as_tensordict_module
from .cudagraphs import CudaGraphModule
from .utils import composite_lp_aggregate, set_composite_lp_aggregate

__all__ = ["TensorDictModule", "TensorDictModuleBase", "TensorDictModuleWrapper", "WrapModule", "TensorDictSequential", "EnsembleModule", "CudaGraphModule", "ProbabilisticTensorDictModule", "ProbabilisticTensorDictSequential", "InteractionType", "set_interaction_type", "make_functional", "get_functional", "is_functional", "repopulate_module", "AddStateIndependentNormalScale", "CompositeDistribution", "NormalParamExtractor", "OneHotCategorical", "rand_one_hot", "TruncatedNormal", "TensorDictParams", "dispatch", "make_tensordict", "as_tensordict_module", "add_custom_mapping", "biased_softplus", "inv_softplus", "mappings", "skip_existing", "set_skip_existing", "composite_lp_aggregate", "set_composite_lp_aggregate"]
