"""
This type stub file was generated by pyright.
"""

import torch
from typing import Any, Callable, Dict, List, Optional, Tuple, Union
from tensordict.base import TensorDictBase
from tensordict.nn.utils import _set_skip_existing_None
from tensordict.utils import NestedKey
from torch import nn

_has_functorch = ...
__all__ = ["TensorDictModule", "TensorDictModuleWrapper"]
class dispatch:
    """Allows for a function expecting a TensorDict to be called using kwargs.

    :func:`dispatch` must be used within modules that have an ``in_keys`` (or
    another source of keys indicated by the ``source`` keyword argument) and
    ``out_keys`` (or another ``dest`` key list) attributes indicating what keys
    to be read and written from the tensordict. The wrapped function should
    also have a ``tensordict`` leading argument.

    The resulting function will return a single tensor (if there is a single
    element in out_keys), otherwise it will return a tuple sorted as the ``out_keys``
    of the module.

    :func:`dispatch` can be used either as a method or as a class when extra arguments
    need to be passed.

    Args:
        separator (str, optional): separator that combines sub-keys together
            for ``in_keys`` that are tuples of strings.
            Defaults to ``"_"``.
        source (str or list of keys, optional): if a string is provided,
            it points to the module attribute that contains the
            list of input keys to be used. If a list is provided instead, it
            will contain the keys used as input to the module.
            Defaults to ``"in_keys"`` which is the attribute name of
            :class:`~.TensorDictModule` list of input keys.
        dest (str or list of keys, optional): if a string is provided,
            it points to the module attribute that contains the
            list of output keys to be used. If a list is provided instead, it
            will contain the keys used as output to the module.
            Defaults to ``"out_keys"`` which is the attribute name of
            :class:`~.TensorDictModule` list of output keys.
        auto_batch_size (bool, optional): if ``True``, the batch-size of the
            input tensordict is determined automatically as the maximum number
            of common dimensions across all the input tensors.
            Defaults to ``True``.

    Examples:
        >>> class MyModule(nn.Module):
        ...     in_keys = ["a"]
        ...     out_keys = ["b"]
        ...
        ...     @dispatch
        ...     def forward(self, tensordict):
        ...         tensordict['b'] = tensordict['a'] + 1
        ...         return tensordict
        ...
        >>> module = MyModule()
        >>> b = module(a=torch.zeros(1, 2))
        >>> assert (b == 1).all()
        >>> # equivalently
        >>> class MyModule(nn.Module):
        ...     keys_in = ["a"]
        ...     keys_out = ["b"]
        ...
        ...     @dispatch(source="keys_in", dest="keys_out")
        ...     def forward(self, tensordict):
        ...         tensordict['b'] = tensordict['a'] + 1
        ...         return tensordict
        ...
        >>> module = MyModule()
        >>> b = module(a=torch.zeros(1, 2))
        >>> assert (b == 1).all()
        >>> # or this
        >>> class MyModule(nn.Module):
        ...     @dispatch(source=["a"], dest=["b"])
        ...     def forward(self, tensordict):
        ...         tensordict['b'] = tensordict['a'] + 1
        ...         return tensordict
        ...
        >>> module = MyModule()
        >>> b = module(a=torch.zeros(1, 2))
        >>> assert (b == 1).all()

    :func:`dispatch_kwargs` will also work with nested keys with the default
    ``"_"`` separator.

    Examples:
        >>> class MyModuleNest(nn.Module):
        ...     in_keys = [("a", "c")]
        ...     out_keys = ["b"]
        ...
        ...     @dispatch
        ...     def forward(self, tensordict):
        ...         tensordict['b'] = tensordict['a', 'c'] + 1
        ...         return tensordict
        ...
        >>> module = MyModuleNest()
        >>> b, = module(a_c=torch.zeros(1, 2))
        >>> assert (b == 1).all()

    If another separator is wanted, it can be indicated with the ``separator``
    argument in the constructor:

    Examples:
        >>> class MyModuleNest(nn.Module):
        ...     in_keys = [("a", "c")]
        ...     out_keys = ["b"]
        ...
        ...     @dispatch(separator="sep")
        ...     def forward(self, tensordict):
        ...         tensordict['b'] = tensordict['a', 'c'] + 1
        ...         return tensordict
        ...
        >>> module = MyModuleNest()
        >>> b, = module(asepc=torch.zeros(1, 2))
        >>> assert (b == 1).all()


    Since the input keys is a sorted sequence of strings,
    :func:`dispatch` can also be used with unnamed arguments where the order
    must match the order of the input keys.

    .. note::
        If the first argument is a :class:`~.TensorDictBase` instance, it is
        assumed that dispatch is __not__ being used and that this tensordict
        contains all the necessary information to be run through the module.
        In other words, one cannot decompose a tensordict with the first key
        of the module inputs pointing to a tensordict instance.
        In general, it is preferred to use :func:`dispatch` with tensordict
        leaves only.

    Examples:
        >>> class MyModuleNest(nn.Module):
        ...     in_keys = [("a", "c"), "d"]
        ...     out_keys = ["b"]
        ...
        ...     @dispatch
        ...     def forward(self, tensordict):
        ...         tensordict['b'] = tensordict['a', 'c'] + tensordict["d"]
        ...         return tensordict
        ...
        >>> module = MyModuleNest()
        >>> b, = module(torch.zeros(1, 2), d=torch.ones(1, 2))  # works
        >>> assert (b == 1).all()
        >>> b, = module(torch.zeros(1, 2), torch.ones(1, 2))  # works
        >>> assert (b == 1).all()
        >>> try:
        ...     b, = module(torch.zeros(1, 2), a_c=torch.ones(1, 2))  # fails
        ... except:
        ...     print("oopsy!")
        ...

    """
    DEFAULT_SEPARATOR = ...
    DEFAULT_SOURCE = ...
    DEFAULT_DEST = ...
    def __new__(cls, separator=..., source=..., dest=..., auto_batch_size: bool = ...): # -> Callable[..., Any] | Self:
        ...
    
    def __init__(self, separator=..., source=..., dest=..., auto_batch_size: bool = ...) -> None:
        ...
    
    def __call__(self, func: Callable) -> Callable:
        ...
    
    def get_source(self, func, self_func): # -> Any:
        ...
    


class _OutKeysSelect:
    module: nn.Module | None = ...
    def __init__(self, out_keys) -> None:
        ...
    
    def __call__(self, module: TensorDictModuleBase, tensordict_in: TensorDictBase, kwargs: Dict, tensordict_out: TensorDictBase): # -> TensorDictBase | tuple[Any, ...] | tuple[()]:
        ...
    
    def remove(self): # -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    


class TensorDictModuleBase(nn.Module):
    """Base class to TensorDict modules.

    TensorDictModule subclasses are characterized by ``in_keys`` and ``out_keys``
    key-lists that indicate what input entries are to be read and what output
    entries should be expected to be written.

    The forward method input/output signature should always follow the
    convention:

        >>> tensordict_out = module.forward(tensordict_in)

    Unlike :class:`~tensordict.nn.TensorDictModule`, `TensorDictModuleBase` is typically used via subclassing:
    you can wrap any python function in a `TensorDictModuleBase` subclass, as long as the subclass forward reads and
    writes tensordict (or related types) instances.

    The `in_keys` and `out_keys` should be properly specified. For example, `out_keys` can be dynamically reduced using
    :meth:`~tensordict.nn.TensorDictBase.select_out_keys`.

    Examples:
        >>> from tensordict import TensorDict
        >>> from tensordict.nn import TensorDictModuleBase
        >>> class Mod(TensorDictModuleBase):
        ...     in_keys = ["a"] # can also be specified during __init__
        ...     out_keys = ["b", "c"]
        ...     def forward(self, tensordict):
        ...         b = tensordict["a"].clone()
        ...         c = b + 1
        ...         return tensordict.replace({"b": b, "c": c})
        >>> mod = Mod()
        >>> td = mod(TensorDict(a=0))
        >>> td["b"]
        tensor(0)
        >>> td["c"]
        tensor(1)
        >>> mod.select_out_keys("c")
        >>> td = mod(TensorDict(a=0))
        >>> td["c"]
        tensor(1)
        >>> assert "b" not in td

    """
    def __new__(cls, *args, **kwargs): # -> Self:
        ...
    
    @staticmethod
    def is_tdmodule_compatible(module): # -> bool:
        """Checks if a module is compatible with TensorDictModule API."""
        ...
    
    @property
    def in_keys(self): # -> list[Any | str | tuple[Any | str | tuple[Any, ...], ...]]:
        ...
    
    @in_keys.setter
    def in_keys(self, value: List[Union[str, Tuple[str]]]): # -> None:
        ...
    
    @property
    def out_keys(self): # -> list[Any | str | tuple[Any | str | tuple[Any, ...], ...]] | List[str | Tuple[str]]:
        ...
    
    @property
    def out_keys_source(self): # -> list[Any | str | tuple[Any | str | tuple[Any, ...], ...]] | List[str | Tuple[str]]:
        ...
    
    @out_keys.setter
    def out_keys(self, value: List[Union[str, Tuple[str]]]): # -> None:
        ...
    
    def select_out_keys(self, *out_keys) -> TensorDictModuleBase:
        """Selects the keys that will be found in the output tensordict.

        This is useful whenever one wants to get rid of intermediate keys in a
        complicated graph, or when the presence of these keys may trigger unexpected
        behaviours.

        The original ``out_keys`` can still be accessed via ``module.out_keys_source``.

        Args:
            *out_keys (a sequence of strings or tuples of strings): the
                out_keys that should be found in the output tensordict.

        Returns: the same module, modified in-place with updated ``out_keys``.

        The simplest usage is with :class:`~.TensorDictModule`:

        Examples:
            >>> from tensordict import TensorDict
            >>> from tensordict.nn import TensorDictModule, TensorDictSequential
            >>> import torch
            >>> mod = TensorDictModule(lambda x, y: (x+2, y+2), in_keys=["a", "b"], out_keys=["c", "d"])
            >>> td = TensorDict({"a": torch.zeros(()), "b": torch.ones(())}, [])
            >>> mod(td)
            TensorDict(
                fields={
                    a: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    b: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    c: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    d: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False)},
                batch_size=torch.Size([]),
                device=None,
                is_shared=False)
            >>> mod.select_out_keys("d")
            >>> td = TensorDict({"a": torch.zeros(()), "b": torch.ones(())}, [])
            >>> mod(td)
            TensorDict(
                fields={
                    a: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    b: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    d: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False)},
                batch_size=torch.Size([]),
                device=None,
                is_shared=False)

        This feature will also work with dispatched arguments:
        Examples:
            >>> mod(torch.zeros(()), torch.ones(()))
            tensor(2.)

        This change will occur in-place (ie the same module will be returned
        with an updated list of out_keys). It can be reverted using the
        :meth:`TensorDictModuleBase.reset_out_keys` method.

        Examples:
            >>> mod.reset_out_keys()
            >>> mod(TensorDict({"a": torch.zeros(()), "b": torch.ones(())}, []))
            TensorDict(
                fields={
                    a: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    b: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    c: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    d: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False)},
                batch_size=torch.Size([]),
                device=None,
                is_shared=False)

        This will work with other classes too, such as Sequential:
        Examples:
            >>> from tensordict.nn import TensorDictSequential
            >>> seq = TensorDictSequential(
            ...     TensorDictModule(lambda x: x+1, in_keys=["x"], out_keys=["y"]),
            ...     TensorDictModule(lambda x: x+1, in_keys=["y"], out_keys=["z"]),
            ... )
            >>> td = TensorDict({"x": torch.zeros(())}, [])
            >>> seq(td)
            TensorDict(
                fields={
                    x: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    y: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    z: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False)},
                batch_size=torch.Size([]),
                device=None,
                is_shared=False)
            >>> seq.select_out_keys("z")
            >>> td = TensorDict({"x": torch.zeros(())}, [])
            >>> seq(td)
            TensorDict(
                fields={
                    x: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    z: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False)},
                batch_size=torch.Size([]),
                device=None,
                is_shared=False)

        """
        ...
    
    def reset_out_keys(self): # -> Self:
        """Resets the ``out_keys`` attribute to its orignal value.

        Returns: the same module, with its original ``out_keys`` values.

        Examples:
            >>> from tensordict import TensorDict
            >>> from tensordict.nn import TensorDictModule, TensorDictSequential
            >>> import torch
            >>> mod = TensorDictModule(lambda x, y: (x+2, y+2), in_keys=["a", "b"], out_keys=["c", "d"])
            >>> mod.select_out_keys("d")
            >>> td = TensorDict({"a": torch.zeros(()), "b": torch.ones(())}, [])
            >>> mod(td)
            TensorDict(
                fields={
                    a: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    b: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    d: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False)},
                batch_size=torch.Size([]),
                device=None,
                is_shared=False)
            >>> mod.reset_out_keys()
            >>> mod(td)
            TensorDict(
                fields={
                    a: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    b: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    c: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    d: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False)},
                batch_size=torch.Size([]),
                device=None,
                is_shared=False)
        """
        ...
    
    def reset_parameters_recursive(self, parameters: Optional[TensorDictBase] = ...) -> Optional[TensorDictBase]:
        """Recursively reset the parameters of the module and its children.

        Args:
            parameters (TensorDict of parameters, optional): If set to None, the module will reset using self.parameters().
                Otherwise, we will reset the parameters in the tensordict in-place. This is
                useful for functional modules where the parameters are not stored in the module itself.

        Returns:
            A tensordict of the new parameters, only if parameters was not None.

        Examples:
            >>> from tensordict.nn import TensorDictModule
            >>> from torch import nn
            >>> net = nn.Sequential(nn.Linear(2,3), nn.ReLU())
            >>> old_param = net[0].weight.clone()
            >>> module = TensorDictModule(net, in_keys=['bork'], out_keys=['dork'])
            >>> module.reset_parameters()
            >>> (old_param == net[0].weight).any()
            tensor(False)

        This method also supports functional parameter sampling:

            >>> from tensordict import TensorDict
            >>> from tensordict.nn import TensorDictModule
            >>> from torch import nn
            >>> net = nn.Sequential(nn.Linear(2,3), nn.ReLU())
            >>> module = TensorDictModule(net, in_keys=['bork'], out_keys=['dork'])
            >>> params = TensorDict.from_module(module)
            >>> old_params = params.clone(recurse=True)
            >>> module.reset_parameters(params)
            >>> (old_params == params).any()
            False
        """
        ...
    
    @property
    def __name__(self): # -> property:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class TensorDictModule(TensorDictModuleBase):
    """A TensorDictModule, is a python wrapper around a :obj:`nn.Module` that reads and writes to a TensorDict.

    Args:
        module (Callable[[Any], Any]): a callable, typically a :class:`torch.nn.Module`,
            used to map the input to the output parameter space. Its forward method
            can return a single tensor, a tuple of tensors or even a dictionary.
            In the latter case, the output keys of the :class:`TensorDictModule`
            will be used to populate the output tensordict (ie. the keys present
            in ``out_keys`` should be present in the dictionary returned by the
            ``module`` forward method).
        in_keys (iterable of NestedKeys, Dict[NestedStr, str]): keys to be read
            from input tensordict and passed to the module. If it
            contains more than one element, the values will be passed in the
            order given by the in_keys iterable.
            If ``in_keys`` is a dictionary, its keys must correspond to the key
            to be read in the tensordict and its values must match the name of
            the keyword argument in the function signature. If `out_to_in_map` is ``True``,
            the mapping gets inverted so that the keys correspond to the keyword
            arguments in the function signature.
        out_keys (iterable of str): keys to be written to the input tensordict. The length of out_keys must match the
            number of tensors returned by the embedded module. Using "_" as a key avoid writing tensor to output.

    Keyword Args:
        out_to_in_map (bool, optional): if ``True`` (default), `in_keys` is read as if the keys are the arguments keys of
            the :meth:`~.forward` method and the values are the keys in the input :class:`~tensordict.TensorDict`. If
            ``False``, keys are considered to be the input keys and values the method's arguments keys.
        inplace (bool or string, optional): if ``True`` (default), the output of the module are written in the tensordict
            provided to the :meth:`~.forward` method. If ``False``, a new :class:`~tensordict.TensorDict` with and empty
            batch-size and no device is created. if ``"empty"``, :meth:`~tensordict.TensorDict.empty` will be used to
            create the output tensordict.

            .. note::
                If ``inplace=False`` and the tensordict passed to the module is another
                :class:`~tensordict.TensorDictBase` subclass than :class:`~tensordict.TensorDict`, the output will still
                be a :class:`~tensordict.TensorDict` instance. Its batch-size will be empty, and it will have no device.
                Set to ``"empty"`` to get the same :class:`~tensordict.TensorDictBase` subtype, an identical batch-size
                and device. Use ``tensordict_out`` at runtime (see below) to have a more fine-grained control over the
                output.

            .. note::
                If ``inplace=False`` and a `tensordict_out` is passed to the :meth:`~.forward` method,
                the ``tensordict_out`` will prevail. This is the way one can get a tensordict_out taensordict passed to the module is another
                :class:`~tensordict.TensorDictBase` subclass than :class:`~tensordict.TensorDict`, the output will still
                be a :class:`~tensordict.TensorDict` instance.

        method (str, optional): the method to be called in the module, if any. Defaults to `__call__`.
        method_kwargs (Dict[str, Any], optional): additional keyword arguments to be passed to the module's method being called.
        strict (bool, optional): if ``True``, the module will raise an exception if any of the inputs is missing from
            the input tensordict. Otherwise, a `None` value will be used as placeholder. Defaults to ``False``.
        get_kwargs (dict[str, Any], optional): additional keyword arguments to be passed to the :meth:`~tensordict.TensorDictBase.get`
            method. This is particularily useful when dealing with ragged tensors (see :meth:`~tensordict.LazyStackedTensorDict.get`).
            Defaults to ``{}``.

    Embedding a neural network in a TensorDictModule only requires to specify the input
    and output keys. TensorDictModule support functional and regular :obj:`nn.Module`
    objects. In the functional case, the 'params' (and 'buffers') keyword argument must
    be specified:

    Examples:
        >>> from tensordict import TensorDict
        >>> # one can wrap regular nn.Module
        >>> module = TensorDictModule(nn.Transformer(128), in_keys=["input", "tgt"], out_keys=["out"])
        >>> input = torch.ones(2, 3, 128)
        >>> tgt = torch.zeros(2, 3, 128)
        >>> data = TensorDict({"input": input, "tgt": tgt}, batch_size=[2, 3])
        >>> data = module(data)
        >>> print(data)
        TensorDict(
            fields={
                input: Tensor(shape=torch.Size([2, 3, 128]), device=cpu, dtype=torch.float32, is_shared=False),
                out: Tensor(shape=torch.Size([2, 3, 128]), device=cpu, dtype=torch.float32, is_shared=False),
                tgt: Tensor(shape=torch.Size([2, 3, 128]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([2, 3]),
            device=None,
            is_shared=False)

    We can also pass directly the tensors

    Examples:
        >>> out = module(input, tgt)
        >>> assert out.shape == input.shape
        >>> # we can also wrap regular functions
        >>> module = TensorDictModule(lambda x: (x-1, x+1), in_keys=[("input", "x")], out_keys=[("output", "x-1"), ("output", "x+1")])
        >>> module(TensorDict({("input", "x"): torch.zeros(())}, batch_size=[]))
        TensorDict(
            fields={
                input: TensorDict(
                    fields={
                        x: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False)},
                    batch_size=torch.Size([]),
                    device=None,
                    is_shared=False),
                output: TensorDict(
                    fields={
                        x+1: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                        x-1: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False)},
                    batch_size=torch.Size([]),
                    device=None,
                    is_shared=False)},
            batch_size=torch.Size([]),
            device=None,
            is_shared=False)

    We can use TensorDictModule to populate a tensordict:

    Examples:
        >>> module = TensorDictModule(lambda: torch.randn(3), in_keys=[], out_keys=["x"])
        >>> print(module(TensorDict({}, batch_size=[])))
        TensorDict(
            fields={
                x: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([]),
            device=None,
            is_shared=False)

    Another feature is passing a dictionary as input keys, to control the
    dispatching of values to specific keyword arguments.

    Examples:
        >>> module = TensorDictModule(lambda x, *, y: x+y,
        ...     in_keys={'1': 'x', '2': 'y'}, out_keys=['z'], out_to_in_map=False
        ...     )
        >>> td = module(TensorDict({'1': torch.ones(()), '2': torch.ones(())*2}, []))
        >>> td['z']
        tensor(3.)

    If `out_to_in_map` is set to ``True``, then the `in_keys` mapping is reversed. This way,
    one can use the same input key for different keyword arguments.

    Examples:
        >>> module = TensorDictModule(lambda x, *, y, z: x+y+z,
        ...     in_keys={'x': '1', 'y': '2', z: '2'}, out_keys=['t'], out_to_in_map=True
        ...     )
        >>> td = module(TensorDict({'1': torch.ones(()), '2': torch.ones(())*2}, []))
        >>> td['t']
        tensor(5.)

    We can specify the method to be called within a module. Compared to using a lambda function or similar around the
    module's method, this has the advantage that the module attributes (params, buffers, submodules) will be exposed.

    Examples:
        >>> from tensordict import TensorDict
        >>> from tensordict.nn import TensorDictSequential as Seq, TensorDictModule as Mod
        >>> from torch import nn
        >>> import torch
        >>>
        >>> class MyNet(nn.Module):
        ...     def my_func(self, tensor: torch.Tensor, *, an_integer: int):
        ...         return tensor + an_integer
        ...
        >>> s = Seq(
        ...     {
        ...         "a": lambda td: td+1,
        ...         "b": lambda td: td * 2,
        ...         "c": Mod(MyNet(), in_keys=["a"], out_keys=["b"], method="my_func", method_kwargs={"an_integer": 2}),
        ...     }
        ... )
        >>> td = s(TensorDict(a=0))
        >>> print(td)
        >>>
        >>> assert td["b"] == 4

    Functional calls to a tensordict module is easy:

    Examples:
        >>> import torch
        >>> from tensordict import TensorDict
        >>> from tensordict.nn import TensorDictModule
        >>> td = TensorDict({"input": torch.randn(3, 4), "hidden": torch.randn(3, 8)}, [3,])
        >>> module = torch.nn.GRUCell(4, 8)
        >>> td_module = TensorDictModule(
        ...    module=module, in_keys=["input", "hidden"], out_keys=["output"]
        ... )
        >>> params = TensorDict.from_module(td_module)
        >>> # functional API
        >>> with params.to_module(td_module):
        ...     td_functional = td_module(td.clone())
        >>> print(td_functional)
        TensorDict(
            fields={
                hidden: Tensor(shape=torch.Size([3, 8]), device=cpu, dtype=torch.float32, is_shared=False),
                input: Tensor(shape=torch.Size([3, 4]), device=cpu, dtype=torch.float32, is_shared=False),
                output: Tensor(shape=torch.Size([3, 8]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([3]),
            device=None,
            is_shared=False)

    In the stateful case:
        >>> module = torch.nn.GRUCell(4, 8)
        >>> td_module = TensorDictModule(
        ...    module=module, in_keys=["input", "hidden"], out_keys=["output"]
        ... )
        >>> td_stateful = td_module(td.clone())
        >>> print(td_stateful)
        TensorDict(
            fields={
                hidden: Tensor(shape=torch.Size([3, 8]), device=cpu, dtype=torch.float32, is_shared=False),
                input: Tensor(shape=torch.Size([3, 4]), device=cpu, dtype=torch.float32, is_shared=False),
                output: Tensor(shape=torch.Size([3, 8]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([3]),
            device=None,
            is_shared=False)

    """
    _IN_KEY_ERR = ...
    _OUT_KEY_ERR = ...
    def __init__(self, module: Callable, in_keys: NestedKey | List[NestedKey] | Dict[NestedKey: str], out_keys: NestedKey | List[NestedKey], *, out_to_in_map: bool | None = ..., inplace: bool | str = ..., method: str | None = ..., method_kwargs: dict | None = ..., strict: bool = ..., get_kwargs: dict | None = ...) -> None:
        ...
    
    @property
    def is_functional(self) -> bool:
        ...
    
    @dispatch(auto_batch_size=False)
    @_set_skip_existing_None()
    def forward(self, tensordict: TensorDictBase, *args, tensordict_out: TensorDictBase | None = ..., **kwargs: Any) -> TensorDictBase:
        """When the tensordict parameter is not set, kwargs are used to create an instance of TensorDict."""
        ...
    
    @property
    def device(self) -> torch.device:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __getattr__(self, name: str) -> Any:
        ...
    
    def __getstate__(self): # -> dict[str, Any]:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    


class TensorDictModuleWrapper(TensorDictModuleBase):
    """Wrapper class for TensorDictModule objects.

    Once created, a TensorDictModuleWrapper will behave exactly as the
    TensorDictModule it contains except for the methods that are
    overwritten.

    Args:
        td_module (TensorDictModule): operator to be wrapped.

    """
    def __init__(self, td_module: TensorDictModuleBase) -> None:
        ...
    
    def __getattr__(self, name: str) -> Any:
        ...
    
    def forward(self, *args: Any, **kwargs: Any) -> TensorDictBase:
        ...
    


class WrapModule(TensorDictModuleBase):
    """A wrapper around any callable that processes TensorDict instances.

    This wrapper is useful when building :class:`~tensordict.nn.TensorDictSequential` stacks and when a transform
    requires the entire TensorDict instance to be visible.

    Args:
        func (Callable[[TensorDictBase], TensorDictBase]): A callable function that takes in a TensorDictBase instance
            and returns a transformed TensorDictBase instance.

    Keyword Args:
        inplace (bool, optional): If ``True``, the input TensorDict will be modified in-place. Otherwise, a new TensorDict
            will be returned (if the function does not modify it in-place and returns it). Defaults to ``False``.
        in_keys (list of NestedKey, optional): if provided, indicates what entries are read by the module.
            This will not be checked and is provided just for the purpose of informing :class:`~tensordict.nn.TensorDictSequential`
            about the input keys of the wrapped module. Defaults to `[]`.
        out_keys (list of NestedKey, optional): if provided, indicates what entries are written by the module.
            This will not be checked and is provided just for the purpose of informing :class:`~tensordict.nn.TensorDictSequential`
            about the output keys of the wrapped module. Defaults to `[]`.

    Examples:
        >>> from tensordict.nn import TensorDictSequential as Seq, TensorDictModule as Mod, WrapModule
        >>> seq = Seq(
        ...     Mod(lambda x: x * 2, in_keys=["x"], out_keys=["y"]),
        ...     WrapModule(lambda td: td.reshape(-1)),
        ... )
        >>> td = TensorDict(x=torch.ones(3, 4, 5), batch_size=[3, 4])
        >>> td = Seq(td)
        >>> assert td.shape == (12,)
        >>> assert (td["y"] == 2).all()
        >>> assert td["y"].shape == (12, 5)

    """
    in_keys = ...
    out_keys = ...
    def __init__(self, func: Callable[[TensorDictBase], TensorDictBase], *, inplace: bool = ..., in_keys: List[NestedKey] | None = ..., out_keys: List[NestedKey] | None = ...) -> None:
        ...
    
    def forward(self, data: TensorDictBase) -> TensorDictBase:
        ...
    


class as_tensordict_module:
    """A decorator that converts a function into a TensorDictModule.

    Args:
        in_keys (List[NestedKey] | NestedKey | None, optional): The input keys of the resulting TensorDictModule.
        out_keys (List[NestedKey] | NestedKey | None, optional): The output keys of the resulting TensorDictModule.

    Returns:
        Callable: A decorator that can be applied to a function to convert it into a TensorDictModule.

    Examples:
        >>> class MyClass:
        ...     @as_tensordict_module(in_keys="c", out_keys="d")
        ...     def my_method(self, c):
        ...         return c + 1
        >>> obj = MyClass()
        >>> result = obj.my_method(TensorDict(c=0))
        >>> print(result["d"])  # prints: 1
        >>> @as_tensordict_module(in_keys="c", out_keys="d")
        ... def my_function(c):
        ...     return c + 1
        >>> result = my_function(TensorDict(c=0))
        >>> print(result["d"])  # prints: 1
    """
    def __init__(self, *, in_keys: List[NestedKey] | NestedKey, out_keys: List[NestedKey] | NestedKey) -> None:
        ...
    
    def __call__(self, func): # -> _Wrapped:
        ...
    


