"""
This type stub file was generated by pyright.
"""

import os
import torch
from typing import Iterable
from tensordict._td import TensorDict
from tensordict.utils import implement_for, strtobool
from torch import nn
from torch._functorch.vmap import Tensor

__base__setattr__ = ...
PYTREE_HAS_ISLEAF = ...
def set_tensor(module: torch.nn.Module, name: str, tensor: torch.Tensor) -> None:
    """Simplified version of torch.nn.utils._named_member_accessor."""
    ...

@implement_for("torch", "2.0", None)
def set_tensor_dict(module_dict, module, name: str, tensor: torch.Tensor) -> None:
    """Simplified version of torch.nn.utils._named_member_accessor."""
    ...

@implement_for("torch", None, "2.0")
def set_tensor_dict(module_dict, module, name: str, tensor: torch.Tensor) -> None:
    """Simplified version of torch.nn.utils._named_member_accessor."""
    ...

_RESET_OLD_TENSORDICT = ...
class _exclude_td_from_pytree:
    def __init__(self) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    
    def set(self): # -> None:
        ...
    
    def unset(self): # -> None:
        ...
    


if not strtobool(os.getenv("PYTORCH_TENSORDICT_IMPORT_VMAP", "False")):
    ...
def extract_weights_and_buffers(model: nn.Module) -> TensorDict:
    ...

def is_functional(module: nn.Module):
    ...

def make_functional(module: nn.Module, funs_to_decorate: Iterable[str] | None = ..., keep_params: bool = ..., return_params: bool = ...) -> TensorDict:
    ...

def get_functional(module: nn.Module, funs_to_decorate: Iterable[str] | None = ...) -> nn.Module:
    ...

def repopulate_module(model: nn.Module, tensordict: TensorDict) -> nn.Module:
    ...

if strtobool(os.environ.get("EXCLUDE_TD_FROM_PYTREE", "0")):
    ...
