"""
This type stub file was generated by pyright.
"""

import torch
from typing import Any, Callable, Iterator, OrderedDict, Self, Sequence, TYPE_CHECKING, Type
from tensordict._nestedkey import NestedKey
from tensordict._tensorcollection import TensorCollection
from tensordict.base import CompatibleType, T, TensorDictBase
from tensordict.memmap import MemoryMappedTensor
from tensordict.utils import IndexType, lock_blocked
from torch import Tensor, multiprocessing as mp, nn

_has_funcdim = ...
if TYPE_CHECKING:
    ...
else:
    ...
class _unlock_and_set:
    def __new__(cls, *args, **kwargs): # -> _Wrapped | Self:
        ...
    
    def __init__(self, **only_for_kwargs) -> None:
        ...
    
    def __call__(self, func): # -> _Wrapped:
        ...
    


class TensorDictParams(TensorDictBase, nn.Module):
    r"""A Wrapper for TensorDictBase with Parameter Exposure.

    This class is designed to hold a `TensorDictBase` instance that contains parameters, making them accessible to a
    parent :class:`~torch.nn.Module`. This allows for seamless integration of tensordict parameters into PyTorch modules,
    enabling operations like parameter iteration and optimization.

    Key Features:

    - Parameter Exposure: Parameters within the tensordict are exposed to the parent module, allowing them to be included
      in operations like `named_parameters()`.
    - Indexing: Indexing works similarly to the wrapped tensordict. However, parameter names (in :meth:`~.named_parameters`) are registered using
      `TensorDict.flatten_keys("_")`, which may result in different key names compared to the tensordict content.
    - Automatic Conversion: Any tensor set in the tensordict is automatically converted to a :class:`torch.nn.Parameter`,
      unless specified otherwise through the :attr:`no_convert` keyword argument.

    Args
        parameters (TensorDictBase or dict): The tensordict to represent as parameters. Values are converted to
            parameters unless `no_convert=True`. If a `dict` is provided, it is wrapped in a `TensorDict` instance.
            Keyword arguments can also be used.

    Keyword Args:
        no_convert (bool): If `True`, no conversion to `nn.Parameter` occurs and all non-parameter, non-buffer tensors
            will be converted to a :class:`~torch.nn.Buffer` instance.
            If ``False``, all tensors with non-integer dtypes will be converted to :class:`~torch.nn.Parameter`
            whereas integer dtypes will be converted to :class:`~torch.nn.Buffer` instances.
            Defaults to `False`.
        lock (bool): If `True`, the tensordict hosted by `TensorDictParams` is locked, preventing modifications and
            potentially impacting performance when `unlock_()` is required.
            Defaults to `False`.

            .. warning:: Because the inner tensordict isn't copied or locked by default, registering the tensordict
                in a ``TensorDictParams`` and modifying its content afterwards will __not__ update the values within
                the  ``TensorDictParams`` :meth:`.parameters` and :meth:`~.buffers` sequences.

        **kwargs: Key-value pairs to populate the `TensorDictParams`. Exclusive with the `parameters` input.

    Examples
        >>> from torch import nn
        >>> from tensordict import TensorDict
        >>> module = nn.Sequential(nn.Linear(3, 4), nn.Linear(4, 4))
        >>> params = TensorDict.from_module(module)
        >>> params.lock_()
        >>> p = TensorDictParams(params)
        >>> print(p)
        TensorDictParams(params=TensorDict(
            fields={
                0: TensorDict(
                    fields={
                        bias: Parameter(shape=torch.Size([4]), device=cpu, dtype=torch.float32, is_shared=False),
                        weight: Parameter(shape=torch.Size([4, 3]), device=cpu, dtype=torch.float32, is_shared=False)},
                    batch_size=torch.Size([]),
                    device=None,
                    is_shared=False),
                1: TensorDict(
                    fields={
                        bias: Parameter(shape=torch.Size([4]), device=cpu, dtype=torch.float32, is_shared=False),
                        weight: Parameter(shape=torch.Size([4, 4]), device=cpu, dtype=torch.float32, is_shared=False)},
                    batch_size=torch.Size([]),
                    device=None,
                    is_shared=False)},
            batch_size=torch.Size([]),
            device=None,
            is_shared=False))
        >>> class CustomModule(nn.Module):
        ...     def __init__(self, params):
        ...         super().__init__()
        ...         self.params = params
        >>> m = CustomModule(p)
        >>> # The wrapper supports assignment, and values are converted to Parameters
        >>> m.params['other'] = torch.randn(3)
        >>> assert isinstance(m.params['other'], nn.Parameter)

    """
    def __init__(self, parameters: TensorDictBase | dict | None = ..., *, no_convert=..., lock: bool = ..., **kwargs) -> None:
        ...
    
    def __iter__(self): # -> Generator[Any | Tensor, Any, None]:
        ...
    
    def register_get_post_hook(self, hook): # -> None:
        """Register a hook to be called after any get operation on leaf tensors."""
        ...
    
    @classmethod
    def __torch_function__(cls, func: Callable, types: tuple[type, ...], args: tuple[Any, ...] = ..., kwargs: dict[str, Any] | None = ...) -> Callable:
        ...
    
    @lock_blocked
    @_unlock_and_set
    def __setitem__(self, index: IndexType, value: Any) -> None:
        ...
    
    @lock_blocked
    @_unlock_and_set
    def set(self, key: NestedKey, item: CompatibleType, inplace: bool = ..., **kwargs: Any) -> TensorDictBase:
        ...
    
    @lock_blocked
    def update(self, input_dict_or_td: dict[str, CompatibleType] | TensorDictBase, clone: bool = ..., inplace: bool = ..., *, non_blocking: bool = ..., keys_to_update: Sequence[NestedKey] | None = ..., is_leaf: Callable[[Type], bool] | None = ..., update_batch_size: bool = ..., ignore_lock: bool = ...) -> TensorDictBase:
        ...
    
    @lock_blocked
    @_unlock_and_set
    def pop(self, key: NestedKey, default: Any = ...) -> CompatibleType:
        ...
    
    @lock_blocked
    @_unlock_and_set
    def popitem(self): # -> None:
        ...
    
    @lock_blocked
    @_unlock_and_set
    def rename_key_(self, old_key: NestedKey, new_key: NestedKey, safe: bool = ...) -> TensorDictBase:
        ...
    
    def map(self, fn: Callable, dim: int = ..., num_workers: int | None = ..., chunksize: int | None = ..., num_chunks: int | None = ..., pool: mp.Pool = ..., generator: torch.Generator | None = ..., max_tasks_per_child: int | None = ..., worker_threads: int = ..., mp_start_method: str | None = ...):
        ...
    
    @_unlock_and_set(inplace=True)
    def apply(self, fn: Callable, *others: TensorDictBase, batch_size: Sequence[int] | None = ..., device: torch.device | None = ..., names: Sequence[str] | None = ..., inplace: bool = ..., default: Any = ..., filter_empty: bool | None = ..., call_on_nested: bool = ..., **constructor_kwargs) -> TensorDictBase | None:
        ...
    
    @_unlock_and_set(inplace=True)
    def named_apply(self, fn: Callable, *others: TensorDictBase, batch_size: Sequence[int] | None = ..., device: torch.device | None = ..., names: Sequence[str] | None = ..., inplace: bool = ..., default: Any = ..., filter_empty: bool | None = ..., call_on_nested: bool = ..., **constructor_kwargs) -> TensorDictBase | None:
        ...
    
    @_get_post_hook
    @_fallback
    def get(self, key: NestedKey, default: Any = ...) -> CompatibleType:
        ...
    
    @_get_post_hook
    @_fallback
    def __getitem__(self, index: IndexType) -> Self | Tensor | TensorCollection | Any:
        ...
    
    @_fallback
    def auto_device_(self) -> Self:
        ...
    
    __getitems__ = ...
    def to(self, *args, **kwargs) -> TensorDictBase:
        ...
    
    def cpu(self): # -> Self | TensorDictParams:
        ...
    
    def cuda(self, device=...): # -> Self | TensorDictParams:
        ...
    
    @_fallback
    def chunk(self, chunks: int, dim: int = ...) -> tuple[TensorDictBase, ...]:
        ...
    
    @classmethod
    def from_dict(cls, *args, **kwargs): # -> TensorDictParams:
        ...
    
    @_fallback
    def to_tensordict(self, *, retain_none: bool | None = ...): # -> None:
        ...
    
    @_fallback
    def to_h5(self, filename, **kwargs): # -> None:
        ...
    
    def __hash__(self) -> int:
        ...
    
    @_fallback
    def __eq__(self, other: object) -> TensorDictBase:
        ...
    
    @_fallback
    def __ne__(self, other: object) -> TensorDictBase:
        ...
    
    @_fallback
    def __xor__(self, other: object) -> TensorDictBase:
        ...
    
    @_fallback
    def __or__(self, other: object) -> TensorDictBase:
        ...
    
    @_fallback
    def __ge__(self, other: object) -> TensorDictBase:
        ...
    
    @_fallback
    def __gt__(self, other: object) -> TensorDictBase:
        ...
    
    @_fallback
    def __le__(self, other: object) -> TensorDictBase:
        ...
    
    @_fallback
    def __lt__(self, other: object) -> TensorDictBase:
        ...
    
    def __getattr__(self, item: str) -> Any:
        ...
    
    @_fallback_property
    def batch_size(self) -> torch.Size:
        ...
    
    @_fallback
    def contiguous(self, *args, **kwargs): # -> None:
        ...
    
    @lock_blocked
    @_unlock_and_set
    def del_(self, *args, **kwargs): # -> None:
        ...
    
    @_fallback
    def detach_(self, *args, **kwargs): # -> None:
        ...
    
    @_fallback_property
    def device(self): # -> None:
        ...
    
    @_fallback
    def entry_class(self, *args, **kwargs): # -> None:
        ...
    
    @_fallback
    def is_contiguous(self, *args, **kwargs): # -> None:
        ...
    
    @_fallback
    def keys(self, *args, **kwargs): # -> None:
        ...
    
    @_fallback
    def masked_fill(self, *args, **kwargs): # -> None:
        ...
    
    @_fallback
    def masked_fill_(self, *args, **kwargs): # -> None:
        ...
    
    def memmap_(self, prefix: str | None = ..., copy_existing: bool = ..., num_threads: int = ...) -> TensorDictBase:
        ...
    
    _memmap_ = ...
    _load_memmap = ...
    def make_memmap(self, key: NestedKey, shape: torch.Size | torch.Tensor, *, dtype: torch.dtype | None = ...) -> MemoryMappedTensor:
        ...
    
    def make_memmap_from_storage(self, key: NestedKey, storage: torch.UntypedStorage, shape: torch.Size | torch.Tensor, *, dtype: torch.dtype | None = ...) -> MemoryMappedTensor:
        ...
    
    def make_memmap_from_tensor(self, key: NestedKey, tensor: torch.Tensor, *, copy_data: bool = ...) -> MemoryMappedTensor:
        ...
    
    @_fallback_property
    def names(self): # -> None:
        ...
    
    def pin_memory(self, *args, **kwargs): # -> Any:
        ...
    
    @_fallback
    def share_memory_(self, *args, **kwargs): # -> None:
        ...
    
    @property
    def is_locked(self) -> bool:
        ...
    
    @is_locked.setter
    def is_locked(self, value): # -> None:
        ...
    
    @_fallback_property
    def is_shared(self) -> bool:
        ...
    
    @_fallback_property
    def is_memmap(self) -> bool:
        ...
    
    @_fallback_property
    def shape(self) -> torch.Size:
        ...
    
    unlock_ = ...
    lock_ = ...
    @property
    def data(self): # -> TensorDictBase | TensorDict | _CustomOpTensorDict | None:
        ...
    
    @property
    def grad(self): # -> TensorDictBase | TensorDict | _CustomOpTensorDict | None:
        ...
    
    @_unlock_and_set(inplace=True)
    def flatten_keys(self, separator: str = ..., inplace: bool = ...) -> TensorDictBase:
        ...
    
    @_unlock_and_set(inplace=True)
    def unflatten_keys(self, separator: str = ..., inplace: bool = ...) -> TensorDictBase:
        ...
    
    @_carry_over
    def from_dict_instance(self, input_dict, *, auto_batch_size: bool = ..., batch_size=..., device=..., batch_dims=...): # -> None:
        ...
    
    @_fallback
    def where(self, condition: Tensor, other: Tensor | TensorDictBase, *, out: TensorDictBase | None = ..., pad: int | bool = ..., update_batch_size: bool = ...): # -> None:
        ...
    
    _check_device = ...
    _check_is_shared = ...
    @_fallback
    def all(self, dim: int | None = ...) -> bool | TensorDictBase:
        ...
    
    @_fallback
    def any(self, dim: int | None = ...) -> bool | TensorDictBase:
        ...
    
    @_fallback
    def expand(self, *args, **kwargs) -> Self:
        ...
    
    @_fallback
    def masked_select(self, mask: Tensor) -> Self:
        ...
    
    @_fallback
    def memmap_like(self, prefix: str | None = ..., copy_existing: bool = ..., num_threads: int = ...) -> Self:
        ...
    
    @_fallback
    def reshape(self, *shape: int): # -> None:
        ...
    
    @_fallback
    def repeat_interleave(self, *shape: int): # -> None:
        ...
    
    @_fallback
    def split(self, split_size: int | list[int], dim: int = ...) -> list[TensorDictBase]:
        ...
    
    @_unlock_and_set
    def create_nested(self, key): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def values(self, include_nested: bool = ..., leaves_only: bool = ..., is_leaf: Callable[[Type], bool] | None = ..., *, sort: bool = ...) -> Iterator[CompatibleType]:
        ...
    
    def state_dict(self, *args, destination=..., prefix=..., keep_vars=..., flatten=...): # -> OrderedDict[str, Any]:
        ...
    
    def load_state_dict(self, state_dict: OrderedDict[str, Any], strict=..., assign=...): # -> Self:
        ...
    
    def items(self, include_nested: bool = ..., leaves_only: bool = ..., is_leaf: Callable[[Type], bool] | None = ..., *, sort: bool = ...) -> Iterator[CompatibleType]:
        ...
    
    @_apply_on_data
    def zero_(self) -> Self:
        ...
    
    @_apply_on_data
    def fill_(self, key: NestedKey, value: float | bool) -> Self:
        ...
    
    @_apply_on_data
    def copy_(self, tensordict: T, non_blocking: bool | None = ...) -> T:
        ...
    
    @_apply_on_data
    def set_at_(self, key: NestedKey, value: CompatibleType, index: IndexType) -> Self:
        ...
    
    @_apply_on_data
    def set_(self, key: NestedKey, item: CompatibleType) -> Self:
        ...
    
    @_apply_on_data
    def update_(self, input_dict_or_td: dict[str, CompatibleType] | T, clone: bool = ..., *, non_blocking: bool = ..., keys_to_update: Sequence[NestedKey] | None = ...) -> T:
        ...
    
    @_apply_on_data
    def update_at_(self, input_dict_or_td: dict[str, CompatibleType] | T, idx: IndexType, clone: bool = ..., *, non_blocking: bool = ..., keys_to_update: Sequence[NestedKey] | None = ...) -> T:
        ...
    
    @_apply_on_data
    def apply_(self, fn: Callable, *others, **kwargs) -> Self:
        ...
    


TDPARAM_HANDLED_FUNCTIONS = ...
def implements_for_tdparam(torch_function: Callable) -> Callable[[Callable], Callable]:
    """Register a torch function override for TensorDictParams."""
    ...

