"""
This type stub file was generated by pyright.
"""

import torch
from typing import Any, Dict, List, OrderedDict, Self, TYPE_CHECKING, overload
from tensordict._nestedkey import NestedKey
from tensordict.nn.common import TensorDictModuleBase, dispatch
from tensordict.nn.sequence import TensorDictSequential
from tensordict.nn.utils import _set_skip_existing_None
from tensordict.tensordict import TensorDictBase
from torch import Tensor, distributions as D
from torch.utils._contextlib import _DecoratorContextManager
from enum import StrEnum

if TYPE_CHECKING:
    ...
else:
    ...
__all__ = ["ProbabilisticTensorDictModule", "ProbabilisticTensorDictSequential"]
class InteractionType(StrEnum):
    """A list of possible interaction types with a distribution.

    MODE, MEDIAN and MEAN point to the property / attribute with the same name.
    RANDOM points to ``rsample()`` if that method exists or ``sample()`` if not.

    DETERMINISTIC can be used as a generic fallback if ``MEAN`` or ``MODE`` are not guaranteed to
    be analytically tractable. In such cases, a rude deterministic estimate can be used
    in some cases even if it lacks a true algebraic meaning.
    This value will trigger a query to the ``deterministic_sample`` attribute in the distribution
    and if it does not exist, the ``mean`` will be used.

    """
    MODE = ...
    MEDIAN = ...
    MEAN = ...
    RANDOM = ...
    DETERMINISTIC = ...
    @classmethod
    def from_str(cls, type_str: str) -> InteractionType:
        """Return the interaction_type with name matched to the provided string (case insensitive)."""
        ...
    


_interaction_type = ...
DETERMINISTIC_REGISTER = ...
dist_has_enum_support = ...
def interaction_type() -> InteractionType | None:
    """Returns the current sampling type."""
    ...

class set_interaction_type(_DecoratorContextManager):
    """Sets all ProbabilisticTDModules sampling to the desired type.

    Args:
        type (InteractionType or str): sampling type to use when the policy is being called.

    """
    def __init__(self, type: InteractionType | str | None = ...) -> None:
        ...
    
    def clone(self) -> set_interaction_type:
        ...
    
    def __enter__(self) -> None:
        ...
    
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        ...
    


class ProbabilisticTensorDictModule(TensorDictModuleBase):
    """A probabilistic TD Module.

    `ProbabilisticTensorDictModule` is a non-parametric module embedding a
    probability distribution constructor. It reads the distribution parameters from an input
    TensorDict using the specified `in_keys` and outputs a sample (loosely speaking) of the
    distribution.

    The output "sample" is produced given some rule, specified by the input ``default_interaction_type``
    argument and the ``interaction_type()`` global function.

    `ProbabilisticTensorDictModule` can be used to construct the distribution
    (through the :meth:`~.get_dist` method) and/or sampling from this distribution
    (through a regular :meth:`~.__call__` to the module).

    A `ProbabilisticTensorDictModule` instance has two main features:

    - It reads and writes from and to TensorDict objects;
    - It uses a real mapping R^n -> R^m to create a distribution in R^d from
      which values can be sampled or computed.

    When the :meth:`~.__call__` and :meth:`~.forward` method are called, a distribution is
    created, and a value computed (depending on the ``interaction_type`` value, 'dist.mean',
    'dist.mode', 'dist.median' attributes could be used, as well as
    the 'dist.rsample', 'dist.sample' method). The sampling step is skipped if the supplied
    TensorDict has all the desired key-value pairs already.

    By default, `ProbabilisticTensorDictModule` distribution class is a :class:`~torchrl.modules.distributions.Delta`
    distribution, making `ProbabilisticTensorDictModule` a simple wrapper around
    a deterministic mapping function.


    Args:
        in_keys (NestedKey | List[NestedKey] | Dict[str, NestedKey]): key(s) that will be read from the input TensorDict
            and used to build the distribution.
            Importantly, if it's a list of NestedKey or a NestedKey, the leaf (last element) of those keys must match the keywords used by
            the distribution class of interest, e.g. ``"loc"`` and ``"scale"`` for
            the :class:`~torch.distributions.Normal` distribution and similar.
            If in_keys is a dictionary, the keys are the keys of the distribution and the values are the keys in the
            tensordict that will get match to the corresponding distribution keys.
        out_keys (NestedKey | List[NestedKey] | None): key(s) where the sampled values will be written.
            Importantly, if these keys are found in the input TensorDict, the sampling step will be skipped.

    Keyword Args:
        default_interaction_type (InteractionType, optional): keyword-only argument.
            Default method to be used to retrieve
            the output value. Should be one of InteractionType: MODE, MEDIAN, MEAN or RANDOM
            (in which case the value is sampled randomly from the distribution). Default
            is MODE.

            .. note:: When a sample is drawn, the
                :class:`ProbabilisticTensorDictModule` instance will
                first look for the interaction mode dictated by the
                :func:`~tensordict.nn.probabilistic.interaction_type`
                global function. If this returns `None` (its default value), then the
                `default_interaction_type` of the `ProbabilisticTDModule`
                instance will be used. Note that
                :class:`~torchrl.collectors.collectors.DataCollectorBase`
                instances will use `set_interaction_type` to
                :class:`tensordict.nn.InteractionType.RANDOM` by default.

            .. note::
                In some cases, the mode, median or mean value may not be
                readily available through the corresponding attribute.
                To paliate this, :class:`~ProbabilisticTensorDictModule` will first attempt
                to get the value through a call to ``get_mode()``, ``get_median()`` or ``get_mean()``
                if the method exists.

        distribution_class (Type or Callable[[Any], Distribution], optional): keyword-only argument.
            A :class:`torch.distributions.Distribution` class to
            be used for sampling.
            Default is :class:`~tensordict.nn.distributions.Delta`.

            .. note::
                If the distribution class is of type
                :class:`~tensordict.nn.distributions.CompositeDistribution`, the ``out_keys``
                can be inferred directly form the ``"distribution_map"`` or ``"name_map"``
                keywork arguments provided through this class' ``distribution_kwargs``
                keyword argument, making the ``out_keys`` optional in such cases.

        distribution_kwargs (dict, optional): keyword-only argument.
            Keyword-argument pairs to be passed to the distribution.

            .. note:: if your kwargs contain tensors that you would like to transfer to device with the module, or
                tensors that should see their dtype modified when calling `module.to(dtype)`, you can wrap the kwargs
                in a :class:`~tensordict.nn.TensorDictParams` to do this automatically.

        return_log_prob (bool, optional): keyword-only argument.
            If ``True``, the log-probability of the
            distribution sample will be written in the tensordict with the key
            `log_prob_key`. Default is ``False``.
        log_prob_keys (List[NestedKey], optional): keys where to write the log_prob if ``return_log_prob=True``.
            Defaults to `'<sample_key_name>_log_prob'`, where `<sample_key_name>` is each of the :attr:`out_keys`.

            .. note:: This is only available when :func:`~tensordict.nn.probabilistic.composite_lp_aggregate` is set to ``False``.

        log_prob_key (NestedKey, optional): key where to write the log_prob if ``return_log_prob=True``.
            Defaults to `'sample_log_prob'` when :func:`~tensordict.nn.probabilistic.composite_lp_aggregate` is set to `True`
            or `'<sample_key_name>_log_prob'` otherwise.

            .. note:: When there is more than one sample, this is only available when :func:`~tensordict.nn.probabilistic.composite_lp_aggregate` is set to ``True``.

        cache_dist (bool, optional): keyword-only argument.
            EXPERIMENTAL: if ``True``, the parameters of the
            distribution (i.e. the output of the module) will be written to the
            tensordict along with the sample. Those parameters can be used to re-compute
            the original distribution later on (e.g. to compute the divergence between
            the distribution used to sample the action and the updated distribution in
            PPO). Default is ``False``.
        n_empirical_estimate (int, optional): keyword-only argument.
            Number of samples to compute the empirical
            mean when it is not available. Defaults to 1000.

    Examples:
        >>> import torch
        >>> from tensordict import TensorDict
        >>> from tensordict.nn import (
        ...     ProbabilisticTensorDictModule,
        ...     ProbabilisticTensorDictSequential,
        ...     TensorDictModule,
        ... )
        >>> from tensordict.nn.distributions import NormalParamExtractor
        >>> from tensordict.nn.functional_modules import make_functional
        >>> from torch.distributions import Normal, Independent
        >>> td = TensorDict(
        ...     {"input": torch.randn(3, 4), "hidden": torch.randn(3, 8)}, [3]
        ... )
        >>> net = torch.nn.GRUCell(4, 8)
        >>> module = TensorDictModule(
        ...     net, in_keys=["input", "hidden"], out_keys=["params"]
        ... )
        >>> normal_params = TensorDictModule(
        ...     NormalParamExtractor(), in_keys=["params"], out_keys=["loc", "scale"]
        ... )
        >>> def IndepNormal(**kwargs):
        ...     return Independent(Normal(**kwargs), 1)
        >>> prob_module = ProbabilisticTensorDictModule(
        ...     in_keys=["loc", "scale"],
        ...     out_keys=["action"],
        ...     distribution_class=IndepNormal,
        ...     return_log_prob=True,
        ... )
        >>> td_module = ProbabilisticTensorDictSequential(
        ...     module, normal_params, prob_module
        ... )
        >>> params = TensorDict.from_module(td_module)
        >>> with params.to_module(td_module):
        ...     _ = td_module(td)
        >>> print(td)
        TensorDict(
            fields={
                action: Tensor(shape=torch.Size([3, 4]), device=cpu, dtype=torch.float32, is_shared=False),
                hidden: Tensor(shape=torch.Size([3, 8]), device=cpu, dtype=torch.float32, is_shared=False),
                input: Tensor(shape=torch.Size([3, 4]), device=cpu, dtype=torch.float32, is_shared=False),
                loc: Tensor(shape=torch.Size([3, 4]), device=cpu, dtype=torch.float32, is_shared=False),
                params: Tensor(shape=torch.Size([3, 8]), device=cpu, dtype=torch.float32, is_shared=False),
                sample_log_prob: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                scale: Tensor(shape=torch.Size([3, 4]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([3]),
            device=None,
            is_shared=False)
        >>> with params.to_module(td_module):
        ...     dist = td_module.get_dist(td)
        >>> print(dist)
        Independent(Normal(loc: torch.Size([3, 4]), scale: torch.Size([3, 4])), 1)
        >>> # we can also apply the module to the TensorDict with vmap
        >>> from torch import vmap
        >>> params = params.expand(4)
        >>> def func(td, params):
        ...     with params.to_module(td_module):
        ...         return td_module(td)
        >>> td_vmap = vmap(func, (None, 0))(td, params)
        >>> print(td_vmap)
        TensorDict(
            fields={
                action: Tensor(shape=torch.Size([4, 3, 4]), device=cpu, dtype=torch.float32, is_shared=False),
                hidden: Tensor(shape=torch.Size([4, 3, 8]), device=cpu, dtype=torch.float32, is_shared=False),
                input: Tensor(shape=torch.Size([4, 3, 4]), device=cpu, dtype=torch.float32, is_shared=False),
                loc: Tensor(shape=torch.Size([4, 3, 4]), device=cpu, dtype=torch.float32, is_shared=False),
                params: Tensor(shape=torch.Size([4, 3, 8]), device=cpu, dtype=torch.float32, is_shared=False),
                sample_log_prob: Tensor(shape=torch.Size([4, 3]), device=cpu, dtype=torch.float32, is_shared=False),
                scale: Tensor(shape=torch.Size([4, 3, 4]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([4, 3]),
            device=None,
            is_shared=False)

    """
    def __init__(self, in_keys: NestedKey | List[NestedKey] | Dict[str, NestedKey], out_keys: NestedKey | List[NestedKey] | None = ..., *, default_interaction_type: InteractionType = ..., distribution_class: type = ..., distribution_kwargs: dict | None = ..., return_log_prob: bool = ..., log_prob_keys: List[NestedKey] | None = ..., log_prob_key: NestedKey | None = ..., cache_dist: bool = ..., n_empirical_estimate: int = ..., num_samples: int | torch.Size | None = ...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @property
    def out_keys(self) -> List[NestedKey]:
        ...
    
    @property
    def log_prob_key(self): # -> NestedKey | None:
        ...
    
    @property
    def log_prob_keys(self): # -> list[NestedKey | Any | None] | List[NestedKey] | None:
        ...
    
    @property
    def dist_params_keys(self) -> List[NestedKey]:
        """Returns all the keys pointing at the distribution params."""
        ...
    
    @property
    def dist_sample_keys(self) -> List[NestedKey]:
        """Returns all the keys pointing at the distribution samples."""
        ...
    
    def get_dist(self, tensordict: TensorDictBase) -> D.Distribution:
        """Creates a :class:`torch.distribution.Distribution` instance with the parameters provided in the input tensordict.

        Args:
            tensordict (TensorDictBase): The input tensordict containing the distribution parameters.

        Returns:
            A :class:`torch.distribution.Distribution` instance created from the input tensordict.

        Raises:
            TypeError: If the input tensordict does not match the distribution keywords.
        """
        ...
    
    build_dist_from_params = ...
    _CHANGE_IN_C_LP_A = ...
    def log_prob(self, tensordict, *, dist: torch.distributions.Distribution | None = ...): # -> Tensor | TensorDictBase | Literal[0]:
        """Computes the log-probability of the distribution sample.

        Args:
            tensordict (TensorDictBase): The input tensordict containing the distribution parameters.
            dist (torch.distributions.Distribution, optional): The distribution instance. Defaults to ``None``.
                If ``None``, the distribution will be computed using the `get_dist` method.

        Returns:
            A tensor representing the log-probability of the distribution sample.
        """
        ...
    
    @property
    def SAMPLE_LOG_PROB_KEY(self):
        ...
    
    @dispatch(auto_batch_size=False)
    @_set_skip_existing_None()
    def forward(self, tensordict: TensorDictBase, tensordict_out: TensorDictBase | None = ..., _requires_sample: bool = ...) -> TensorDictBase:
        ...
    


class ProbabilisticTensorDictSequential(TensorDictSequential):
    """A sequence of :class:`~tensordict.nn.TensorDictModules` containing at least one :class:`~tensordict.nn.ProbabilisticTensorDictModule`.

    This class extends :class:`~tensordict.nn.TensorDictSequential` and is typically configured with a sequence of
    modules where the final module is an instance of :class:`~tensordict.nn.ProbabilisticTensorDictModule`.
    However, it also supports configurations where one or more intermediate modules are instances of
    :class:`~tensordict.nn.ProbabilisticTensorDictModule`, while the last module may or may not be probabilistic.
    In all cases, it exposes the :meth:`~.get_dist` method to recover the distribution object from the
    :class:`~tensordict.nn.ProbabilisticTensorDictModule` instances in the sequence.

    Multiple probabilistic modules can co-exist in a single ``ProbabilisticTensorDictSequential``.
    If `return_composite` is ``False`` (default), only the last one will produce a distribution and the others
    will be executed as regular :class:`~tensordict.nn.TensorDictModule` instances.
    However, if a `ProbabilisticTensorDictModule` is not the last module in the sequence and `return_composite=False`,
    a `ValueError` will be raised when trying to query the module. If `return_composite=True`,
    all intermediate `ProbabilisticTensorDictModule` instances will contribute to a single
    :class:`~tensordict.nn.CompositeDistribution` instance.

    Resulting log-probabilities will be conditional probabilities if samples are interdependent:
    whenever

        .. math::
            Z = F(X, Y)

    then the log-probability of Z will be

        .. math::
            log(p(z | x, y))

    Args:
        *modules (sequence or OrderedDict of TensorDictModuleBase or ProbabilisticTensorDictModule): An ordered sequence of
            :class:`~tensordict.nn.TensorDictModule` instances, usually terminating in a :class:`~tensordict.nn.ProbabilisticTensorDictModule`,
            to be run sequentially.
            The modules can be instances of TensorDictModuleBase or any other function that matches this signature.
            Note that if a non-TensorDictModuleBase callable is used, its input and output keys will not be tracked,
            and thus will not affect the `in_keys` and `out_keys` attributes of the TensorDictSequential.

    Keyword Args:
        partial_tolerant (bool, optional): If ``True``, the input tensordict can miss some
            of the input keys. If so, only the modules that can be executed given the
            keys that are present will be executed. Also, if the input tensordict is a
            lazy stack of tensordicts AND if partial_tolerant is ``True`` AND if the stack
            does not have the required keys, then TensorDictSequential will scan through
            the sub-tensordicts looking for those that have the required keys, if any.
            Defaults to ``False``.
        return_composite (bool, optional): If `True` and multiple
            :class:`~tensordict.nn.ProbabilisticTensorDictModule` or
            :class:`~tensordict.nn.ProbabilisticTensorDictSequential` instances are found,
            a :class:`~tensordict.nn.CompositeDistribution` instance will be used.
            Otherwise, only the last module will be used to build the distribution.
            Defaults to ``True`` whenever there are more than one probabilistic modules or the last module is not probabilistic.
            Errors if `return_composite` is `False` and the neither of the above conditions are met.
        inplace (bool, optional): if `True`, the input tensordict is modified in-place. If `False`, a new empty
            :class:`~tensordict.TensorDict` instance is created. If `"empty"`, `input.empty()` is used instead (ie, the
            output preserves type, device and batch-size). Defaults to `None` (relies on sub-modules).

    Raises:
        ValueError: If the input sequence of modules is empty.
        TypeError: If the final module is not an instance of
            :obj:`ProbabilisticTensorDictModule` or
            :obj:`ProbabilisticTensorDictSequential`.

    Examples:
        >>> from tensordict.nn import ProbabilisticTensorDictModule as Prob, ProbabilisticTensorDictSequential as Seq
        >>> import torch
        >>> # Typical usage: a single distribution is computed last in the sequence
        >>> import torch
        >>> from tensordict import TensorDict
        >>> from tensordict.nn import ProbabilisticTensorDictModule as Prob, ProbabilisticTensorDictSequential as Seq, \
        ...     TensorDictModule as Mod
        >>> torch.manual_seed(0)
        >>>
        >>> module = Seq(
        ...     Mod(lambda x: x + 1, in_keys=["x"], out_keys=["loc"]),
        ...     Prob(in_keys=["loc"], out_keys=["sample"], distribution_class=torch.distributions.Normal,
        ...          distribution_kwargs={"scale": 1}),
        ... )
        >>> input = TensorDict(x=torch.ones(3))
        >>> td = module(input.copy())
        >>> print(td)
        TensorDict(
            fields={
                loc: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                sample: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                x: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([]),
            device=None,
            is_shared=False)
        >>> print(module.get_dist(input))
        Normal(loc: torch.Size([3]), scale: torch.Size([3]))
        >>> print(module.log_prob(td))
        tensor([-0.9189, -0.9189, -0.9189])
        >>> # Intermediate distributions are ignored when return_composite=False
        >>> module = Seq(
        ...     Mod(lambda x: x + 1, in_keys=["x"], out_keys=["loc"]),
        ...     Prob(in_keys=["loc"], out_keys=["sample0"], distribution_class=torch.distributions.Normal,
        ...          distribution_kwargs={"scale": 1}),
        ...     Mod(lambda x: x + 1, in_keys=["sample0"], out_keys=["loc2"]),
        ...     Prob(in_keys={"loc": "loc2"}, out_keys=["sample1"], distribution_class=torch.distributions.Normal,
        ...          distribution_kwargs={"scale": 1}),
        ...     return_composite=False,
        ... )
        >>> td = module(TensorDict(x=torch.ones(3)))
        >>> print(td)
        TensorDict(
            fields={
                loc2: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                loc: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                sample0: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                sample1: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                x: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([]),
            device=None,
            is_shared=False)
        >>> print(module.get_dist(input))
        Normal(loc: torch.Size([3]), scale: torch.Size([3]))
        >>> print(module.log_prob(td))
        tensor([-0.9189, -0.9189, -0.9189])
        >>> # Intermediate distributions produce a CompositeDistribution when return_composite=True
        >>> module = Seq(
        ...     Mod(lambda x: x + 1, in_keys=["x"], out_keys=["loc"]),
        ...     Prob(in_keys=["loc"], out_keys=["sample0"], distribution_class=torch.distributions.Normal,
        ...          distribution_kwargs={"scale": 1}),
        ...     Mod(lambda x: x + 1, in_keys=["sample0"], out_keys=["loc2"]),
        ...     Prob(in_keys={"loc": "loc2"}, out_keys=["sample1"], distribution_class=torch.distributions.Normal,
        ...          distribution_kwargs={"scale": 1}),
        ...     return_composite=True,
        ... )
        >>> input = TensorDict(x=torch.ones(3))
        >>> td = module(input.copy())
        >>> print(td)
        TensorDict(
            fields={
                loc2: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                loc: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                sample0: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                sample1: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                x: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([]),
            device=None,
            is_shared=False)
        >>> print(module.get_dist(input))
        CompositeDistribution({'sample0': Normal(loc: torch.Size([3]), scale: torch.Size([3])), 'sample1': Normal(loc: torch.Size([3]), scale: torch.Size([3]))})
        >>> print(module.log_prob(td))
        TensorDict(
            fields={
                sample0_log_prob: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                sample1_log_prob: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([]),
            device=None,
            is_shared=False)
        >>> # Even a single intermediate distribution is wrapped in a CompositeDistribution when
        >>> # return_composite=True
        >>> module = Seq(
        ...     Mod(lambda x: x + 1, in_keys=["x"], out_keys=["loc"]),
        ...     Prob(in_keys=["loc"], out_keys=["sample0"], distribution_class=torch.distributions.Normal,
        ...          distribution_kwargs={"scale": 1}),
        ...     Mod(lambda x: x + 1, in_keys=["sample0"], out_keys=["y"]),
        ...     return_composite=True,
        ... )
        >>> td = module(TensorDict(x=torch.ones(3)))
        >>> print(td)
        TensorDict(
            fields={
                loc: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                sample0: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                x: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                y: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([]),
            device=None,
            is_shared=False)
        >>> print(module.get_dist(input))
        CompositeDistribution({'sample0': Normal(loc: torch.Size([3]), scale: torch.Size([3]))})
        >>> print(module.log_prob(td))
        TensorDict(
            fields={
                sample0_log_prob: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([]),
            device=None,
            is_shared=False)

    """
    @overload
    def __init__(self, modules: OrderedDict[str, TensorDictModuleBase | ProbabilisticTensorDictModule], partial_tolerant: bool = ..., return_composite: bool | None = ..., *, inplace: bool | None = ...) -> None:
        ...
    
    @overload
    def __init__(self, modules: List[TensorDictModuleBase | ProbabilisticTensorDictModule], partial_tolerant: bool = ..., return_composite: bool | None = ..., *, inplace: bool | None = ...) -> None:
        ...
    
    def __init__(self, *modules: TensorDictModuleBase | ProbabilisticTensorDictModule, partial_tolerant: bool = ..., return_composite: bool | None = ..., inplace: bool | None = ...) -> None:
        ...
    
    def __getitem__(self, index: int | slice | str) -> Self | TensorDictModuleBase:
        ...
    
    _dist_sample = ...
    @property
    def det_part(self): # -> Any:
        ...
    
    def get_dist_params(self, tensordict: TensorDictBase, tensordict_out: TensorDictBase | None = ..., **kwargs) -> tuple[D.Distribution, TensorDictBase]:
        """Returns the distribution parameters and output tensordict.

        This method runs the deterministic part of the :class:`~tensordict.nn.ProbabilisticTensorDictSequential`
        module to obtain the distribution parameters. The interaction type is set to the current global
        interaction type if available, otherwise it defaults to the interaction type of the last module.

        Args:
            tensordict (TensorDictBase): The input tensordict.
            tensordict_out (TensorDictBase, optional): The output tensordict. If ``None``, a new tensordict will be created.
                Defaults to ``None``.

        Keyword Args:
            **kwargs: Additional keyword arguments passed to the deterministic part of the module.

        Returns:
            tuple[D.Distribution, TensorDictBase]: A tuple containing the distribution object and the output tensordict.

        .. note:: The interaction type is temporarily set to the specified value during the execution of this method.
        """
        ...
    
    @property
    def log_prob_keys(self): # -> list[Any]:
        ...
    
    log_prob_key = ...
    @property
    def dist_params_keys(self) -> List[NestedKey]:
        """Returns all the keys pointing at the distribution params."""
        ...
    
    @property
    def dist_sample_keys(self) -> List[NestedKey]:
        """Returns all the keys pointing at the distribution samples."""
        ...
    
    @property
    def num_samples(self): # -> tuple[()] | tuple[int, ...] | Size:
        ...
    
    def get_dist(self, tensordict: TensorDictBase, tensordict_out: TensorDictBase | None = ..., **kwargs) -> D.Distribution:
        """Returns the distribution resulting from passing the input tensordict through the sequence.

        If `return_composite` is ``False`` (default), this method will only consider the last probabilistic module in the sequence.

        Otherwise, it will return a :class:`~tensordict.nn.CompositeDistribution` instance containing the distributions of all probabilistic modules.

        Args:
            tensordict (TensorDictBase): The input tensordict.
            tensordict_out (TensorDictBase, optional): The output tensordict. If ``None``, a new tensordict will be created.
                Defaults to ``None``.

        Keyword Args:
            **kwargs: Additional keyword arguments passed to the underlying modules.

        Returns:
            D.Distribution: The resulting distribution object.

        Raises:
            RuntimeError: If no probabilistic module is found in the sequence.

        .. note::
            When `return_composite` is ``True``, the distributions are conditioned on the previous samples in the sequence.
            This means that if a module depends on the output of a previous probabilistic module, its distribution will be conditional.

        """
        ...
    
    @property
    def default_interaction_type(self): # -> Any | InteractionType | None:
        """Returns the `default_interaction_type` of the module using an iterative heuristic.

        This property iterates over all modules in reverse order, attempting to retrieve the
        `default_interaction_type` attribute from any child module. The first non-None value
        encountered is returned. If no such value is found, a default `interaction_type()` is returned.

        """
        ...
    
    def log_prob(self, tensordict, tensordict_out: TensorDictBase | None = ..., *, dist: torch.distributions.Distribution | None = ..., **kwargs) -> TensorDictBase | torch.Tensor:
        """Returns the log-probability of the input tensordict.

        If `self.return_composite` is ``True`` and the distribution is a :class:`~tensordict.nn.CompositeDistribution`,
        this method will return the log-probability of the entire composite distribution.

        Otherwise, it will only consider the last probabilistic module in the sequence.

        Args:
            tensordict (TensorDictBase): The input tensordict.
            tensordict_out (TensorDictBase, optional): The output tensordict. If ``None``, a new tensordict will be created.
                Defaults to ``None``.

        Keyword Args:
            dist (torch.distributions.Distribution, optional): The distribution object. If ``None``, it will be computed using `get_dist`.
                Defaults to ``None``.

        Returns:
            TensorDictBase or torch.Tensor: The log-probability of the input tensordict.

        """
        ...
    
    def build_dist_from_params(self, tensordict: TensorDictBase) -> D.Distribution:
        """Constructs a distribution from the input parameters without evaluating other modules in the sequence.

        This method searches for the last :class:`~tensordict.nn.ProbabilisticTensorDictModule` in the sequence and uses it to build the distribution.

        Args:
            tensordict (TensorDictBase): The input tensordict containing the distribution parameters.

        Returns:
            D.Distribution: The constructed distribution object.

        Raises:
            RuntimeError: If no :class:`~tensordict.nn.ProbabilisticTensorDictModule` is found in the sequence.
        """
        ...
    
    @dispatch(auto_batch_size=False)
    @_set_skip_existing_None()
    def forward(self, tensordict: TensorDictBase, tensordict_out: TensorDictBase | None = ..., **kwargs) -> TensorDictBase:
        ...
    


