[build-system]
requires = ["uv_build>=0.8.19,<0.9.0"]
build-backend = "uv_build"

[project]
name = "mjlab-microduck"
version = "0.1.0"
description = "RL training environments for the Microduck robot, built on mjlab"
readme = { file = "README", content-type = "text/plain" }
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.12, <3.13"
dependencies = [
    "mjlab==1.3.0",
    "warp-lang==1.12.0",
    "better-actuator-models",
    "onnxruntime>=1.24.4",
    "huggingface_hub>=0.27.0",
    "scipy>=1.16",
    "torch==2.9.1",
    "matplotlib>=3.9",
]

[project.entry-points."mjlab.tasks"]
mjlab_microduck = "src.task_registry"

[project.scripts]
duck-body = "src.sim_body_server:main"
publish = "src.publish_cli:main"
export = "src.export:main"
infer = "src.infer:main"
pong = "src.pong:main"

[tool.uv.build-backend]
module-name = "src"
module-root = ""
namespace = true

[tool.ruff]
indent-width = 4
line-length = 5000
target-version = "py312"

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint]
ignore = [
    "B008",
    "BLE001",
    "S110",
    "SIM102",
    "RUF012",
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.uv]
override-dependencies = [
    "protobuf>=4.0,<7.0",
    "onnx>=1.20.1",
    "zmq ; python_version < '3.0'",
]

[tool.uv.sources]
better-actuator-models = { git = "https://github.com/Rhoban/bam.git", branch = "mjlab_frictionloss" }
torch = [
  { index = "pytorch-cu129", marker = "sys_platform == 'linux' and platform_machine == 'aarch64'" },
]

[[tool.uv.index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu129"
explicit = true
