"""
This type stub file was generated by pyright.
"""

from tensordict.nn.distributions import continuous, discrete
from tensordict.nn.distributions.composite import CompositeDistribution
from tensordict.nn.distributions.continuous import AddStateIndependentNormalScale, Delta, NormalParamExtractor
from tensordict.nn.distributions.discrete import OneHotCategorical, rand_one_hot
from tensordict.nn.distributions.truncated_normal import TruncatedNormal
from tensordict.nn.probabilistic import InteractionType, set_interaction_type
from tensordict.nn.utils import add_custom_mapping, mappings

distributions_maps = ...
__all__ = ["CompositeDistribution", "AddStateIndependentNormalScale", "Delta", "NormalParamExtractor", "OneHotCategorical", "rand_one_hot", "TruncatedNormal", "InteractionType", "set_interaction_type", "continuous", "discrete", "distributions_maps", "add_custom_mapping", "mappings"]
