"""
This type stub file was generated by pyright.
"""

import torch
from collections.abc import Mapping
from typing import Dict, Self, TYPE_CHECKING
from tensordict.base import TensorDictBase
from tensordict.utils import IndexType, NestedKey
from torch import distributions as d

if TYPE_CHECKING:
    ...
else:
    ...
class CompositeDistribution(d.Distribution, Mapping):
    """A composite distribution that groups multiple distributions together using the TensorDict interface.

    This class allows for operations such as `log_prob_composite`, `entropy_composite`, `cdf`, `icdf`, `rsample`, and `sample`
    to be performed on a collection of distributions, returning a TensorDict. The input TensorDict may be modified in-place.

    Args:
        params (TensorDictBase): A nested key-tensor map where the root entries correspond to sample names, and the leaves
            are the distribution parameters. Entry names must match those specified in `distribution_map`.
        distribution_map (Dict[NestedKey, Type[torch.distribution.Distribution]]): Specifies the distribution types to be used.
            The names of the distributions should match the sample names in the `TensorDict`.

    Keyword Arguments:
        name_map (Dict[NestedKey, NestedKey], optional): A mapping of where each sample should be written. If not provided,
            the key names from `distribution_map` will be used.
        extra_kwargs (Dict[NestedKey, Dict], optional): A dictionary of additional keyword arguments for constructing the distributions.
        log_prob_key (NestedKey, optional): The key where the aggregated log probability will be stored.
            Defaults to `'sample_log_prob'`.

            .. note:: if :func:`tensordict.nn.probabilistic.composite_lp_aggregate` returns ``False``, tbe log-probabilities will
                be written under `("path", "to", "leaf", "<sample_name>_log_prob")`
                where `("path", "to", "leaf", "<sample_name>")` is the :class:`~tensordict.NestedKey` corresponding to
                the leaf tensor being sampled. In that case, the ``log_prob_key`` argument will be ignored.

        entropy_key (NestedKey, optional): The key where the entropy will be stored. Defaults to `'entropy'`

            .. note:: if :func:`tensordict.nn.probabilistic.composite_lp_aggregate` returns ``False``, tbe entropies will
                be written under `("path", "to", "leaf", "<sample_name>_entropy")`
                where `("path", "to", "leaf", "<sample_name>")` is the :class:`~tensordict.NestedKey` corresponding to
                the leaf tensor being sampled. In that case, the ``entropy_key`` argument will be ignored.

    .. note:: The batch size of the input TensorDict containing the parameters (`params`) determines the batch shape of
        the distribution. For example, the `"sample_log_prob"` entry resulting from a call to `log_prob` will have the
        shape of the parameters plus any additional batch dimensions.

    .. seealso:: :class:`~tensordict.nn.ProbabilisticTensorDictModule` and :class:`~tensordict.nn.ProbabilisticTensorDictSequential`
        to learn how to use this class as part of a model.

    .. seealso:: :class:`~tensordict.nn.set_composite_lp_aggregate` to control the aggregation of the log-probabilities.

    Examples:
        >>> params = TensorDict({
        ...     "cont": {"loc": torch.randn(3, 4), "scale": torch.rand(3, 4)},
        ...     ("nested", "disc"): {"logits": torch.randn(3, 10)}
        ... }, [3])
        >>> dist = CompositeDistribution(params,
        ...     distribution_map={"cont": d.Normal, ("nested", "disc"): d.Categorical})
        >>> sample = dist.sample((4,))
        >>> with set_composite_lp_aggregate(False):
        ...     sample = dist.log_prob(sample)
        ...     print(sample)
        TensorDict(
            fields={
                cont: Tensor(shape=torch.Size([4, 3, 4]), device=cpu, dtype=torch.float32, is_shared=False),
                cont_log_prob: Tensor(shape=torch.Size([4, 3, 4]), device=cpu, dtype=torch.float32, is_shared=False),
                nested: TensorDict(
                    fields={
                        disc: Tensor(shape=torch.Size([4, 3]), device=cpu, dtype=torch.int64, is_shared=False),
                        disc_log_prob: Tensor(shape=torch.Size([4, 3]), device=cpu, dtype=torch.float32, is_shared=False)},
                    batch_size=torch.Size([4]),
                    device=None,
                    is_shared=False)},
            batch_size=torch.Size([4]),
            device=None,
            is_shared=False)

    """
    def __init__(self, params: TensorDictBase, distribution_map: dict, *, name_map: dict | None = ..., extra_kwargs=..., log_prob_key: NestedKey | None = ..., entropy_key: NestedKey | None = ...) -> None:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    
    def __getitem__(self, item: IndexType) -> Self:
        ...
    
    def __len__(self): # -> int:
        ...
    
    @property
    def log_prob_key(self): # -> Literal['sample_log_prob']:
        ...
    
    @log_prob_key.setter
    def log_prob_key(self, value): # -> None:
        ...
    
    @property
    def entropy_key(self): # -> Literal['entropy']:
        ...
    
    @entropy_key.setter
    def entropy_key(self, value): # -> None:
        ...
    
    @classmethod
    def from_distributions(cls, params, distributions: Dict[NestedKey, d.Distribution], *, name_map: dict | None = ..., log_prob_key: NestedKey | None = ..., entropy_key: NestedKey | None = ...) -> CompositeDistribution:
        """Create a `CompositeDistribution` instance from existing distribution objects.

        This class method allows for the creation of a `CompositeDistribution` by directly providing
        a dictionary of distribution instances, rather than specifying distribution types and parameters separately.

        Args:
            params (TensorDictBase): A TensorDict that defines the batch shape for the composite distribution.
                The params will not be used by this method, but the tensordict will be used to gather the key names of
                the distributions.
            distributions (Dict[NestedKey, d.Distribution]): A dictionary mapping nested keys to distribution instances.
                These distributions will be used directly in the composite distribution.

        Keyword Args:
            name_map (Dict[NestedKey, NestedKey], optional): A mapping of where each sample should be written. If not provided,
                the key names from `distribution_map` will be used.
            log_prob_key (NestedKey, optional): The key where the log probability will be stored.
                Defaults to `'sample_log_prob'`.
            entropy_key (NestedKey, optional): The key where the entropy will be stored. Defaults to `'entropy'`.

        Returns:
            CompositeDistribution: An instance of `CompositeDistribution` initialized with the provided distributions.

        Raises:
            KeyError: If a key in `name_map` cannot be found in the provided distributions.

        .. note:: The batch size of the `params` TensorDict determines the batch shape of the composite distribution.

        Example:
            >>> from tensordict.nn import CompositeDistribution, ProbabilisticTensorDictSequential, ProbabilisticTensorDictModule, TensorDictModule
            >>> import torch
            >>> from tensordict import TensorDict
            >>>
            >>> # Values are not used to build the dists
            >>> params = TensorDict({("0", "loc"): None, ("1", "loc"): None, ("0", "scale"): None, ("1", "scale"): None})
            >>> d0 = torch.distributions.Normal(0, 1)
            >>> d1 = torch.distributions.Normal(torch.zeros(1, 2), torch.ones(1, 2))
            >>>
            >>> d = CompositeDistribution.from_distributions(params, {"0": d0, "1": d1})
            >>> print(d.sample())
            TensorDict(
                fields={
                    0: Tensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                    1: Tensor(shape=torch.Size([1, 2]), device=cpu, dtype=torch.float32, is_shared=False)},
                batch_size=torch.Size([]),
                device=None,
                is_shared=False)
        """
        ...
    
    def sample(self, shape=...) -> TensorDictBase:
        ...
    
    @property
    def mode(self) -> TensorDictBase:
        ...
    
    @property
    def mean(self) -> TensorDictBase:
        ...
    
    @property
    def deterministic_sample(self) -> TensorDictBase:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def rsample(self, shape=...) -> TensorDictBase:
        ...
    
    def log_prob(self, sample: TensorDictBase) -> torch.Tensor | TensorDictBase:
        """Compute the summed log-probability of a given sample.

        Args:
            sample (TensorDictBase): The input sample to compute the log probability for.

        If ``self.aggregate_probabilities`` is ``True``, this method will return a single tensor with
        the summed log-probabilities. If ``self.aggregate_probabilities`` is ``False``, this method will
        call the `:meth:`~.log_prob_composite` method and return a tensordict with the log-probabilities
        of each sample in the input tensordict along with a ``sample_log_prob`` entry with the summed
        log-prob. In both cases, the output shape will be the shape of the input tensordict.
        """
        ...
    
    def log_prob_composite(self, sample: TensorDictBase, *, include_sum: bool | None = ...) -> TensorDictBase:
        """Computes the log-probability of each component in the input sample and return a TensorDict with individual log-probabilities.

        Args:
            sample (TensorDictBase): The input sample to compute the log probabilities for.

        Keyword Args:
            include_sum (bool, optional): Whether to include the summed log-probability in the output TensorDict.
                Defaults to ``composite_lp_aggregate()`` (``False`` by default).

        Returns:
            TensorDictBase: A TensorDict containing the individual log-probabilities for each component in the input sample,
                along with a "sample_log_prob" entry containing the summed log-probability if `include_sum` is True.
        """
        ...
    
    def entropy(self, samples_mc: int = ..., *, aggregate_probabilities: bool | None = ..., include_sum: bool | None = ...) -> torch.Tensor | TensorDictBase:
        """Computes and returns the entropy of the composite distribution.

        This method calculates the entropy for each component distribution and optionally sums them.

        Args:
            samples_mc (int): The number of samples to draw if the entropy does not have a closed-form solution.
                Defaults to `1`.

        Keyword Args:
            include_sum (bool, optional): Whether to include the summed entropy in the output TensorDict.
                Defaults to `composite_lp_aggregate()`, which defaults to `False`.

        Returns:
            torch.Tensor or TensorDictBase: If `aggregate_probabilities` is `True`, returns a single tensor with
            the summed entropies. If `aggregate_probabilities` is `False`, returns a TensorDict with the entropies
            of each component distribution.

        .. note:: If a distribution does not implement a closed-form solution for entropy, Monte Carlo sampling is used
            to estimate it.
        """
        ...
    
    def entropy_composite(self, samples_mc=..., *, include_sum: bool | None = ...) -> TensorDictBase:
        """Computes the entropy for each component distribution and returns a TensorDict with individual entropies.

        This method is used by the `entropy` method when `self.aggregate_probabilities` is `False`.

        Args:
            samples_mc (int): The number of samples to draw if the entropy does not have a closed-form solution.
                Defaults to `1`.

        Keyword Args:
            include_sum (bool, optional): Whether to include the summed entropy in the output TensorDict.
                Defaults to `composite_lp_aggregate()`, which is defaults to `False`.

        Returns:
            TensorDictBase: A TensorDict containing the individual entropies for each component distribution,
            along with an "entropy" entry containing the summed entropies if `include_sum` is `True`.

        .. note:: If a distribution does not implement a closed-form solution for entropy, Monte Carlo sampling is used
            to estimate it.
        """
        ...
    
    def cdf(self, sample: TensorDictBase) -> TensorDictBase:
        """Computes the cumulative distribution function (CDF) for each component distribution in the composite distribution.

        This method calculates the CDF for each component distribution and updates the input TensorDict with the results.

        Args:
            sample (TensorDictBase): A TensorDict containing samples for which to compute the CDF.

        Returns:
            TensorDictBase: The input TensorDict updated with `<sample_name>_cdf` entries for each component distribution.
        """
        ...
    
    def icdf(self, sample: TensorDictBase) -> TensorDictBase:
        """Computes the inverse cumulative distribution function (inverse CDF) for each component distribution.

        This method requires the input TensorDict to have either a `<sample_name>_cdf` entry or a `<sample_name>` entry
        for each component distribution. It calculates the inverse CDF and updates the TensorDict with the results.

        Args:
            sample (TensorDictBase): A TensorDict containing either `<sample_name>_cdf` or `<sample_name>` entries
                for each component distribution.

        Returns:
            TensorDictBase: The input TensorDict updated with `<sample_name>_icdf` entries for each component distribution.

        Raises:
            KeyError: If neither `<sample_name>` nor `<sample_name>_cdf` can be found in the input TensorDict for a component distribution.
        """
        ...
    


