"""
This type stub file was generated by pyright.
"""

import torch
from numbers import Number
from typing import Sequence
from torch import distributions as D, nn

__all__ = ["NormalParamExtractor", "AddStateIndependentNormalScale", "Delta"]
class NormalParamWrapper(nn.Module):
    def __init__(self, operator: nn.Module, scale_mapping: str = ..., scale_lb: Number = ...) -> None:
        ...
    


class NormalParamExtractor(nn.Module):
    """A non-parametric nn.Module that splits its input into loc and scale parameters.

    The scale parameters are mapped onto positive values using the specified ``scale_mapping``.

    Args:
        scale_mapping (str, optional): positive mapping function to be used with the std.
            default = ``"biased_softplus_1.0"`` (i.e. softplus map with bias such that fn(0.0) = 1.0)
            choices: ``"softplus"``, ``"exp"``, ``"relu"``, ``"biased_softplus_1"`` or ``"none"`` (no mapping).
            See :func:`~tensordict.nn.mappings` for more details.
        scale_lb (Number, optional): The minimum value that the variance can take. Default is 1e-4.

    Examples:
        >>> import torch
        >>> from tensordict.nn.distributions import NormalParamExtractor
        >>> from torch import nn
        >>> module = nn.Linear(3, 4)
        >>> normal_params = NormalParamExtractor()
        >>> tensor = torch.randn(3)
        >>> loc, scale = normal_params(module(tensor))
        >>> print(loc.shape, scale.shape)
        torch.Size([2]) torch.Size([2])
        >>> assert (scale > 0).all()
        >>> # with modules that return more than one tensor
        >>> module = nn.LSTM(3, 4)
        >>> tensor = torch.randn(4, 2, 3)
        >>> loc, scale, others = normal_params(*module(tensor))
        >>> print(loc.shape, scale.shape)
        torch.Size([4, 2, 2]) torch.Size([4, 2, 2])
        >>> assert (scale > 0).all()

    """
    def __init__(self, scale_mapping: str = ..., scale_lb: Number = ...) -> None:
        ...
    
    def forward(self, *tensors: torch.Tensor) -> tuple[torch.Tensor, ...]:
        ...
    


class AddStateIndependentNormalScale(torch.nn.Module):
    """A nn.Module that adds trainable state-independent scale parameters.

    The scale parameters are mapped onto positive values using the specified ``scale_mapping``.

    Args:
        scale_shape (torch.Size or equivalent, optional): the shape of the scale parameter.
            Defaults to ``torch.Size(())``.

    Keyword Args:
        scale_mapping (str, optional): positive mapping function to be used with the std.
            Defaults to ``"exp"``,
            choices: ``"softplus"``, ``"exp"``, ``"relu"``, ``"biased_softplus_1"``.
        scale_lb (Number, optional): The minimum value that the variance can take.
            Defaults to ``1e-4``.
        device (torch.device, optional): the device of the module.
        make_param (bool, optional): whether the scale should be a parameter (``True``)
            or a buffer (``False``).
            Defaults to ``True``.
        init_value (float, optional): Initial value of state independent scale.
            Defaults to 0.0.

    Examples:
        >>> from torch import nn
        >>> import torch
        >>> num_outputs = 4
        >>> module = nn.Linear(3, num_outputs)
        >>> module_normal = AddStateIndependentNormalScale(num_outputs)
        >>> tensor = torch.randn(3)
        >>> loc, scale = module_normal(module(tensor))
        >>> print(loc.shape, scale.shape)
        torch.Size([4]) torch.Size([4])
        >>> assert (scale > 0).all()
        >>> # with modules that return more than one tensor
        >>> module = nn.LSTM(3, num_outputs)
        >>> module_normal = AddStateIndependentNormalScale(num_outputs)
        >>> tensor = torch.randn(4, 2, 3)
        >>> loc, scale, others = module_normal(*module(tensor))
        >>> print(loc.shape, scale.shape)
        torch.Size([4, 2, 4]) torch.Size([4, 2, 4])
        >>> assert (scale > 0).all()
    """
    def __init__(self, scale_shape: torch.Size | int | tuple = ..., *, scale_mapping: str = ..., scale_lb: Number = ..., device: torch.device | None = ..., make_param: bool = ..., init_value: float = ...) -> None:
        ...
    
    def forward(self, loc: torch.Tensor, *others: torch.Tensor) -> tuple[torch.Tensor, ...]:
        """Forward of AddStateIndependentNormalScale.

        Args:
            loc (torch.Tensor): a location parameter.
            *others: other unused parameters.

        Returns:
            a tuple of two or more tensors containing the ``(loc, scale, *others)`` values.
        """
        ...
    


class Delta(D.Distribution):
    """Delta distribution.

    Args:
        param (torch.Tensor): parameter of the delta distribution;
        atol (number, optional): absolute tolerance to consider that a tensor matches the distribution parameter;
            Default is 1e-6
        rtol (number, optional): relative tolerance to consider that a tensor matches the distribution parameter;
            Default is 1e-6
        batch_shape (torch.Size, optional): batch shape;
        event_shape (torch.Size, optional): shape of the outcome.

    """
    arg_constraints: dict = ...
    def __init__(self, param: torch.Tensor, atol: float = ..., rtol: float = ..., batch_shape: torch.Size | Sequence[int] | None = ..., event_shape: torch.Size | Sequence[int] | None = ...) -> None:
        ...
    
    def update(self, param: torch.Tensor) -> None:
        ...
    
    def log_prob(self, value: torch.Tensor) -> torch.Tensor:
        ...
    
    @torch.no_grad()
    def sample(self, sample_shape: torch.Size | Sequence[int] | None = ...) -> torch.Tensor:
        ...
    
    def rsample(self, sample_shape: torch.Size | Sequence[int] | None = ...) -> torch.Tensor:
        ...
    
    @property
    def mode(self) -> torch.Tensor:
        ...
    
    @property
    def mean(self) -> torch.Tensor:
        ...
    
    @property
    def deterministic_sample(self) -> torch.Tensor:
        ...
    


