"""
This type stub file was generated by pyright.
"""

import torch
from typing import Sequence
from torch import distributions as D

__all__ = ["OneHotCategorical"]
def rand_one_hot(values: torch.Tensor, do_softmax: bool = ...) -> torch.Tensor:
    ...

class OneHotCategorical(D.Categorical):
    """One-hot categorical distribution.

    This class behaves excacly as torch.distributions.Categorical except that it reads and produces one-hot encodings
    of the discrete tensors.

    """
    num_params: int = ...
    def __init__(self, logits: torch.Tensor | None = ..., probs: torch.Tensor | None = ..., **kwargs) -> None:
        ...
    
    def log_prob(self, value: torch.Tensor) -> torch.Tensor:
        ...
    
    @property
    def mode(self) -> torch.Tensor:
        ...
    
    deterministic_sample = ...
    def sample(self, sample_shape: torch.Size | Sequence[int] | None = ...) -> torch.Tensor:
        ...
    
    def rsample(self, sample_shape: torch.Size | Sequence[int] | None = ...) -> torch.Tensor:
        ...
    


