"""
This type stub file was generated by pyright.
"""

import torch
from numbers import Number
from typing import Sequence
from torch.distributions import Distribution, constraints

CONST_SQRT_2 = ...
CONST_INV_SQRT_2PI = ...
CONST_INV_SQRT_2 = ...
CONST_LOG_INV_SQRT_2PI = ...
CONST_LOG_SQRT_2PI_E = ...
class TruncatedStandardNormal(Distribution):
    """Truncated Standard Normal distribution.

    Source: https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    """
    arg_constraints = ...
    has_rsample = ...
    eps = ...
    def __init__(self, a: Number | torch.Tensor, b: Number | torch.Tensor, validate_args: bool | None = ...) -> None:
        ...
    
    @constraints.dependent_property
    def support(self) -> constraints.Constraints:
        ...
    
    @property
    def mean(self) -> torch.Tensor:
        ...
    
    @property
    def variance(self) -> torch.Tensor:
        ...
    
    @property
    def entropy(self) -> torch.Tensor:
        ...
    
    @property
    def auc(self) -> torch.Tensor:
        ...
    
    def cdf(self, value: torch.Tensor) -> torch.Tensor:
        ...
    
    def icdf(self, value: torch.Tensor) -> torch.Tensor:
        ...
    
    def log_prob(self, value: torch.Tensor) -> torch.Tensor:
        ...
    
    def rsample(self, sample_shape: torch.Size | Sequence[int] | None = ...) -> torch.Tensor:
        ...
    


class TruncatedNormal(TruncatedStandardNormal):
    """Truncated Normal distribution.

    https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    """
    has_rsample = ...
    def __init__(self, loc: Number | torch.Tensor, scale: Number | torch.Tensor, a: Number | torch.Tensor, b: Number | torch.Tensor, validate_args: bool | None = ...) -> None:
        ...
    
    def cdf(self, value: torch.Tensor) -> torch.Tensor:
        ...
    
    def icdf(self, value: torch.Tensor) -> torch.Tensor:
        ...
    
    def log_prob(self, value: torch.Tensor) -> torch.Tensor:
        ...
    


