"""
This type stub file was generated by pyright.
"""

import torch
from torch import nn as nn

class CNN(nn.Sequential):
    """Convolutional Neural Network.

    The CNN network is a sequence of convolutional layers, optional normalization layers, optional activation functions,
    and optional pooling. The final output can be flattened.
    """
    def __init__(self, input_dim: tuple[int, int], input_channels: int, output_channels: tuple[int, ...] | list[int], kernel_size: int | tuple[int, ...] | list[int], stride: int | tuple[int, ...] | list[int] = ..., dilation: int | tuple[int, ...] | list[int] = ..., padding: str = ..., norm: str | tuple[str] | list[str] = ..., activation: str = ..., max_pool: bool | tuple[bool] | list[bool] = ..., global_pool: str = ..., flatten: bool = ...) -> None:
        """Initialize the CNN.

        Args:
            input_dim: Height and width of the input.
            input_channels: Number of input channels.
            output_channels: List of output channels for each convolutional layer.
            kernel_size: List of kernel sizes for each convolutional layer or a single kernel size for all layers.
            stride: List of strides for each convolutional layer or a single stride for all layers.
            dilation: List of dilations for each convolutional layer or a single dilation for all layers.
            padding: Padding type to use. Either 'none', 'zeros', 'reflect', 'replicate', or 'circular'.
            norm: List of normalization types for each convolutional layer or a single type for all layers. Either
                'none', 'batch', or 'layer'.
            activation: Activation function to use.
            max_pool: List of booleans indicating whether to apply max pooling after each convolutional layer or a
                single boolean for all layers.
            global_pool: Global pooling type to apply at the end. Either 'none', 'max', or 'avg'.
            flatten: Whether to flatten the output tensor.
        """
        ...
    
    @property
    def output_channels(self) -> int | None:
        """Get the number of output channels or None if output is flattened."""
        ...
    
    @property
    def output_dim(self) -> tuple[int, int] | int:
        """Get the output height and width or total output dimension if output is flattened."""
        ...
    
    def init_weights(self) -> None:
        """Initialize the weights of the CNN with Kaiming initialization."""
        ...
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Forward pass of the CNN."""
        ...
    


