"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn

class MLP(nn.Sequential):
    """Multi-Layer Perceptron.

    The MLP network is a sequence of linear layers and activation functions. The last layer is a linear layer that
    outputs the desired dimension unless the last activation function is specified.

    It provides additional conveniences:
    - If the hidden dimensions have a value of ``-1``, the dimension is inferred from the input dimension.
    - If the output dimension is a tuple, the output is reshaped to the desired shape.
    """
    def __init__(self, input_dim: int, output_dim: int | tuple[int, ...] | list[int], hidden_dims: tuple[int, ...] | list[int], activation: str = ..., last_activation: str | None = ...) -> None:
        """Initialize the MLP.

        Args:
            input_dim: Dimension of the input.
            output_dim: Dimension of the output.
            hidden_dims: Dimensions of the hidden layers. A value of ``-1`` indicates that the dimension should be
                inferred from the input dimension.
            activation: Activation function.
            last_activation: Activation function of the last layer. None results in a linear last layer.
        """
        ...
    
    def init_weights(self, scales: float | tuple[float]) -> None:
        """Initialize the weights of the MLP.

        Args:
            scales: Scale factor for the weights.
        """
        ...
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Forward pass of the MLP."""
        ...
    


