"""
This type stub file was generated by pyright.
"""

import torch
from torch import nn

class EmpiricalNormalization(nn.Module):
    """Normalize mean and variance of values based on empirical values."""
    def __init__(self, shape: int | tuple[int, ...] | list[int], eps: float = ..., until: int | None = ...) -> None:
        """Initialize EmpiricalNormalization module.

        .. note:: The normalization parameters are computed over the whole batch, not for each environment separately.

        Args:
            shape: Shape of input values except batch axis.
            eps: Small value for stability.
            until: If this arg is specified, the module learns input values until the sum of batch sizes exceeds it.
        """
        ...
    
    @property
    def mean(self) -> torch.Tensor:
        """Return the current running mean."""
        ...
    
    @property
    def std(self) -> torch.Tensor:
        """Return the current running standard deviation."""
        ...
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Normalize mean and variance of values based on empirical values."""
        ...
    
    @torch.jit.unused
    def update(self, x: torch.Tensor) -> None:
        """Learn input values without computing the output values of them."""
        ...
    
    @torch.jit.unused
    def inverse(self, y: torch.Tensor) -> torch.Tensor:
        """De-normalize values based on empirical values."""
        ...
    


class EmpiricalDiscountedVariationNormalization(nn.Module):
    """Reward normalization from Pathak's large scale study on PPO.

    Reward normalization. Since the reward function is non-stationary, it is useful to normalize the scale of the
    rewards so that the value function can learn quickly. We did this by dividing the rewards by a running estimate of
    the standard deviation of the sum of discounted rewards.
    """
    def __init__(self, shape: int | tuple[int, ...] | list[int], eps: float = ..., gamma: float = ..., until: int | None = ...) -> None:
        """Initialize discounted-reward normalization with running moments."""
        ...
    
    def forward(self, rew: torch.Tensor) -> torch.Tensor:
        """Normalize rewards using the running std of discounted returns."""
        ...
    


class _DiscountedAverage:
    r"""Discounted average of rewards.

    The discounted average is defined as:

    .. math::

        \bar{R}_t = \gamma \bar{R}_{t-1} + r_t
    """
    def __init__(self, gamma: float) -> None:
        """Initialize discounted accumulation with a fixed discount factor."""
        ...
    
    def update(self, rew: torch.Tensor) -> torch.Tensor:
        """Update and return the discounted running average."""
        ...
    


