"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn
from typing import Union

HiddenState = Union[torch.Tensor, tuple[torch.Tensor, torch.Tensor], None]
class RNN(nn.Module):
    """Recurrent Neural Network.

    This network is used to store the hidden state of the policy. It currently supports GRU and LSTM.
    """
    def __init__(self, input_size: int, hidden_dim: int = ..., num_layers: int = ..., type: str = ...) -> None:
        """Initialize a GRU or LSTM module with internal hidden-state storage."""
        ...
    
    def forward(self, input: torch.Tensor, masks: torch.Tensor | None = ..., hidden_state: HiddenState = ...) -> torch.Tensor:
        """Run recurrent inference in rollout mode or batched update mode."""
        ...
    
    def reset(self, dones: torch.Tensor | None = ..., hidden_state: HiddenState = ...) -> None:
        """Reset hidden states for all or done environments."""
        ...
    
    def detach_hidden_state(self, dones: torch.Tensor | None = ...) -> None:
        """Detach hidden states for all or done environments from the computation graph."""
        ...
    


