"""
This type stub file was generated by pyright.
"""

import torch
from tensordict import TensorDict
from rsl_rl.env import VecEnv
from rsl_rl.models import MLPModel
from rsl_rl.storage import RolloutStorage

class Distillation:
    """Distillation algorithm for training a student model to mimic a teacher model."""
    student: MLPModel
    teacher: MLPModel
    teacher_loaded: bool = ...
    def __init__(self, student: MLPModel, teacher: MLPModel, storage: RolloutStorage, num_learning_epochs: int = ..., gradient_length: int = ..., learning_rate: float = ..., max_grad_norm: float | None = ..., loss_type: str = ..., optimizer: str = ..., device: str = ..., multi_gpu_cfg: dict | None = ..., **kwargs: dict) -> None:
        """Initialize the algorithm with models, storage, and optimization settings."""
        ...
    
    def act(self, obs: TensorDict) -> torch.Tensor:
        """Sample actions and store transition data."""
        ...
    
    def process_env_step(self, obs: TensorDict, rewards: torch.Tensor, dones: torch.Tensor, extras: dict[str, torch.Tensor]) -> None:
        """Record one environment step and update the normalizers."""
        ...
    
    def compute_returns(self, obs: TensorDict) -> None:
        """No-op since distillation does not use return targets."""
        ...
    
    def update(self) -> dict[str, float]:
        """Run optimization epochs over stored batches and return mean losses."""
        ...
    
    def train_mode(self) -> None:
        """Set train mode for the student and keep the teacher in eval mode."""
        ...
    
    def eval_mode(self) -> None:
        """Set evaluation mode for student and teacher models."""
        ...
    
    def save(self) -> dict:
        """Return a dict of all models for saving."""
        ...
    
    def load(self, loaded_dict: dict, load_cfg: dict | None, strict: bool) -> bool:
        """Load specified models from a saved dict."""
        ...
    
    def get_policy(self) -> MLPModel:
        """Get the policy model."""
        ...
    
    @staticmethod
    def construct_algorithm(obs: TensorDict, env: VecEnv, cfg: dict, device: str) -> Distillation:
        """Construct the distillation algorithm."""
        ...
    
    def broadcast_parameters(self) -> None:
        """Broadcast model parameters to all GPUs."""
        ...
    
    def reduce_parameters(self) -> None:
        """Collect gradients from all GPUs and average them.

        This function is called after the backward pass to synchronize the gradients across all GPUs.
        """
        ...
    


