"""
This type stub file was generated by pyright.
"""

import torch
from tensordict import TensorDict
from rsl_rl.env import VecEnv
from rsl_rl.models import MLPModel
from rsl_rl.storage import RolloutStorage

class PPO:
    """Proximal Policy Optimization algorithm.

    Reference:
        - Schulman et al. "Proximal policy optimization algorithms." arXiv preprint arXiv:1707.06347 (2017).
    """
    actor: MLPModel
    critic: MLPModel
    def __init__(self, actor: MLPModel, critic: MLPModel, storage: RolloutStorage, num_learning_epochs: int = ..., num_mini_batches: int = ..., clip_param: float = ..., gamma: float = ..., lam: float = ..., value_loss_coef: float = ..., entropy_coef: float = ..., learning_rate: float = ..., max_grad_norm: float = ..., optimizer: str = ..., use_clipped_value_loss: bool = ..., schedule: str = ..., desired_kl: float = ..., normalize_advantage_per_mini_batch: bool = ..., device: str = ..., rnd_cfg: dict | None = ..., symmetry_cfg: dict | None = ..., multi_gpu_cfg: dict | None = ...) -> None:
        """Initialize the algorithm with models, storage, and optimization settings."""
        ...
    
    def act(self, obs: TensorDict) -> torch.Tensor:
        """Sample actions and store transition data."""
        ...
    
    def process_env_step(self, obs: TensorDict, rewards: torch.Tensor, dones: torch.Tensor, extras: dict[str, torch.Tensor]) -> None:
        """Record one environment step and update the normalizers."""
        ...
    
    def compute_returns(self, obs: TensorDict) -> None:
        """Compute return and advantage targets from stored transitions."""
        ...
    
    def update(self) -> dict[str, float]:
        """Run optimization epochs over stored batches and return mean losses."""
        ...
    
    def train_mode(self) -> None:
        """Set train mode for learnable models."""
        ...
    
    def eval_mode(self) -> None:
        """Set evaluation mode for learnable models."""
        ...
    
    def save(self) -> dict:
        """Return a dict of all models for saving."""
        ...
    
    def load(self, loaded_dict: dict, load_cfg: dict | None, strict: bool) -> bool:
        """Load specified models from a saved dict."""
        ...
    
    def get_policy(self) -> MLPModel:
        """Get the policy model."""
        ...
    
    @staticmethod
    def construct_algorithm(obs: TensorDict, env: VecEnv, cfg: dict, device: str) -> PPO:
        """Construct the PPO algorithm."""
        ...
    
    def broadcast_parameters(self) -> None:
        """Broadcast model parameters to all GPUs."""
        ...
    
    def reduce_parameters(self) -> None:
        """Collect gradients from all GPUs and average them.

        This function is called after the backward pass to synchronize the gradients across all GPUs.
        """
        ...
    


