"""
This type stub file was generated by pyright.
"""

from typing import Any
from tensordict.nn import TensorDictModuleBase
from tensordict.tensordict import TensorDictBase
from tensordict.utils import NestedKey
from torch import fx, nn

__all__ = ["symbolic_trace"]
class TDGraphModule(nn.Module):
    """A graph module for TensorDict."""
    def __init__(self, graph_module: fx.GraphModule, out_keys: list[NestedKey]) -> None:
        ...
    
    def forward(self, tensordict: TensorDictBase, tensordict_out: TensorDictBase | None = ..., **kwargs) -> TensorDictBase:
        ...
    
    def __getattr__(self, name: str) -> Any:
        ...
    


def symbolic_trace(td_module: TensorDictModuleBase) -> TDGraphModule:
    """A symbolic tracer for TensorDictModule."""
    ...

