"""
This type stub file was generated by pyright.
"""

import ctypes
import ctypes.util
import os
import platform
import subprocess
import warnings
import zipfile
import numpy as np
from typing import Any, IO, Sequence, Union
from typing_extensions import TypeAlias
from mujoco import _specs, _structs
from mujoco._callbacks import *
from mujoco._constants import *
from mujoco._enums import *
from mujoco._errors import *
from mujoco._functions import *
from mujoco._specs import *
from mujoco._structs import *
from mujoco._render import *
from mujoco.rendering.classic.renderer import Renderer
from mujoco.rendering.classic.gl_context import *

"""Python bindings for MuJoCo."""
__path__ = ...
_SYSTEM = ...
if _SYSTEM == 'Windows':
  ...
else:
  proc_translated = ...
  is_rosetta = ...
MJTNUM_DTYPE = ...
MjStruct: TypeAlias = Union[_specs.MjsBody, _specs.MjsFrame, _specs.MjsGeom, _specs.MjsJoint, _specs.MjsLight, _specs.MjsMaterial, _specs.MjsSite, _specs.MjsMesh, _specs.MjsSkin, _specs.MjsTexture, _specs.MjsText, _specs.MjsTuple, _specs.MjsCamera, _specs.MjsFlex, _specs.MjsHField, _specs.MjsKey, _specs.MjsNumeric, _specs.MjsPair, _specs.MjsExclude, _specs.MjsEquality, _specs.MjsTendon, _specs.MjsSensor, _specs.MjsActuator, _specs.MjsPlugin,]
def to_zip(spec: _specs.MjSpec, file: Union[str, IO[bytes]]) -> None:
  """Converts an MjSpec to a zip file.

  Args:
    spec: The mjSpec to save to a file.
    file: The path to the file to save to or the file object to write to.
  """
  ...

def from_zip(file: Union[str, IO[bytes]]) -> _specs.MjSpec:
  """Reads a zip file and returns an MjSpec.

  Args:
    file: The path to the file to read from or the file object to read from.
  Returns:
    An MjSpec object.
  """
  ...

class _MjBindModel:
  """Wrapper for MjModel that allows binding multiple specs."""
  def __init__(self, elements: Sequence[Any]) -> None:
    ...
  
  def __getattr__(self, key: str): # -> list[Any]:
    ...
  
  def __setattr__(self, key: str, value: Any):
    ...
  


class _MjBindData:
  """Wrapper for MjData that allows binding multiple specs."""
  def __init__(self, elements: Sequence[Any]) -> None:
    ...
  
  def __getattr__(self, key: str): # -> list[Any]:
    ...
  
  def __setattr__(self, key: str, value: Any): # -> None:
    ...
  


HEADERS_DIR = ...
PLUGINS_DIR = ...
PLUGIN_HANDLES = ...
__version__ = ...


# the C extension modules above are opaque to pyright's stub generator, so
# their re-exported names (MjModel, mjtObj, mj_name2id, ...) fall back to Any
def __getattr__(name: str) -> Any: ...
