import mujoco._structs
import numpy
import numpy.typing
import typing
from typing import overload

class MjrContext:
    auxColor: numpy.typing.NDArray[numpy.uint32]
    auxColor_r: numpy.typing.NDArray[numpy.uint32]
    auxFBO: numpy.typing.NDArray[numpy.uint32]
    auxFBO_r: numpy.typing.NDArray[numpy.uint32]
    auxHeight: numpy.typing.NDArray[numpy.int32]
    auxSamples: numpy.typing.NDArray[numpy.int32]
    auxWidth: numpy.typing.NDArray[numpy.int32]
    baseBuiltin: int
    baseFontBig: int
    baseFontNormal: int
    baseFontShadow: int
    baseHField: int
    baseMesh: int
    basePlane: int
    charHeight: int
    charHeightBig: int
    charWidth: numpy.typing.NDArray[numpy.int32]
    charWidthBig: numpy.typing.NDArray[numpy.int32]
    currentBuffer: int
    fogEnd: float
    fogRGBA: numpy.typing.NDArray[numpy.float32]
    fogStart: float
    fontScale: int
    glInitialized: int
    lineWidth: float
    mat_texid: numpy.typing.NDArray[numpy.int32]
    mat_texrepeat: numpy.typing.NDArray[numpy.float32]
    mat_texuniform: numpy.typing.NDArray[numpy.int32]
    ntexture: int
    offColor: int
    offColor_r: int
    offDepthStencil: int
    offDepthStencil_r: int
    offFBO: int
    offFBO_r: int
    offHeight: int
    offSamples: int
    offWidth: int
    rangeBuiltin: int
    rangeFont: int
    rangeHField: int
    rangeMesh: int
    rangePlane: int
    readDepthMap: int
    readPixelFormat: int
    shadowClip: float
    shadowFBO: int
    shadowScale: float
    shadowSize: int
    shadowTex: int
    texture: numpy.typing.NDArray[numpy.uint32]
    textureType: numpy.typing.NDArray[numpy.int32]
    windowAvailable: int
    windowDoublebuffer: int
    windowSamples: int
    windowStereo: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: mujoco._structs.MjModel, arg1: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def free(self) -> None: ...
    @property
    def nskin(self) -> int: ...
    @property
    def skinfaceVBO(self) -> tuple: ...
    @property
    def skinnormalVBO(self) -> tuple: ...
    @property
    def skintexcoordVBO(self) -> tuple: ...
    @property
    def skinvertVBO(self) -> tuple: ...

def mjr_addAux(index: typing.SupportsInt | typing.SupportsIndex, width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex, samples: typing.SupportsInt | typing.SupportsIndex, con: MjrContext) -> None: ...
def mjr_blitAux(index: typing.SupportsInt | typing.SupportsIndex, src: mujoco._structs.MjrRect, left: typing.SupportsInt | typing.SupportsIndex, bottom: typing.SupportsInt | typing.SupportsIndex, con: MjrContext) -> None: ...
def mjr_blitBuffer(src: mujoco._structs.MjrRect, dst: mujoco._structs.MjrRect, flg_color: typing.SupportsInt | typing.SupportsIndex, flg_depth: typing.SupportsInt | typing.SupportsIndex, con: MjrContext) -> None: ...
def mjr_changeFont(fontscale: typing.SupportsInt | typing.SupportsIndex, con: MjrContext) -> None: ...
def mjr_drawPixels(rgb: typing.Annotated[numpy.typing.NDArray[numpy.uint8], '[m, 1]'] | None, depth: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[m, 1]'] | None, viewport: mujoco._structs.MjrRect, con: MjrContext) -> None: ...
def mjr_figure(viewport: mujoco._structs.MjrRect, fig: mujoco._structs.MjvFigure, con: MjrContext) -> None: ...
def mjr_findRect(x: typing.SupportsInt | typing.SupportsIndex, y: typing.SupportsInt | typing.SupportsIndex, nrect: typing.SupportsInt | typing.SupportsIndex, rect: mujoco._structs.MjrRect) -> int: ...
def mjr_finish() -> None: ...
def mjr_getError() -> int: ...
def mjr_label(viewport: mujoco._structs.MjrRect, font: typing.SupportsInt | typing.SupportsIndex, txt: str, r: typing.SupportsFloat | typing.SupportsIndex, g: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex, a: typing.SupportsFloat | typing.SupportsIndex, rt: typing.SupportsFloat | typing.SupportsIndex, gt: typing.SupportsFloat | typing.SupportsIndex, bt: typing.SupportsFloat | typing.SupportsIndex, con: MjrContext) -> None: ...
def mjr_maxViewport(con: MjrContext) -> mujoco._structs.MjrRect: ...
def mjr_overlay(font: typing.SupportsInt | typing.SupportsIndex, gridpos: typing.SupportsInt | typing.SupportsIndex, viewport: mujoco._structs.MjrRect, overlay: str, overlay2: str, con: MjrContext) -> None: ...
def mjr_readPixels(rgb: typing.Annotated[numpy.typing.ArrayLike, numpy.uint8] | None, depth: typing.Annotated[numpy.typing.ArrayLike, numpy.float32] | None, viewport: mujoco._structs.MjrRect, con: MjrContext) -> None: ...
def mjr_rectangle(viewport: mujoco._structs.MjrRect, r: typing.SupportsFloat | typing.SupportsIndex, g: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex, a: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
def mjr_render(viewport: mujoco._structs.MjrRect, scn: mujoco._structs.MjvScene, con: MjrContext) -> None: ...
def mjr_resizeOffscreen(width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex, con: MjrContext) -> None: ...
def mjr_restoreBuffer(con: MjrContext) -> None: ...
def mjr_setAux(index: typing.SupportsInt | typing.SupportsIndex, con: MjrContext) -> None: ...
def mjr_setBuffer(framebuffer: typing.SupportsInt | typing.SupportsIndex, con: MjrContext) -> None: ...
def mjr_text(font: typing.SupportsInt | typing.SupportsIndex, txt: str, con: MjrContext, x: typing.SupportsFloat | typing.SupportsIndex, y: typing.SupportsFloat | typing.SupportsIndex, r: typing.SupportsFloat | typing.SupportsIndex, g: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
def mjr_uploadHField(m: mujoco._structs.MjModel, con: MjrContext, hfieldid: typing.SupportsInt | typing.SupportsIndex) -> None: ...
def mjr_uploadMesh(m: mujoco._structs.MjModel, con: MjrContext, meshid: typing.SupportsInt | typing.SupportsIndex) -> None: ...
def mjr_uploadTexture(m: mujoco._structs.MjModel, con: MjrContext, texid: typing.SupportsInt | typing.SupportsIndex) -> None: ...
