import collections.abc
import mujoco._enums
import mujoco._structs
import numpy
import numpy.typing
import typing
from typing import Callable, ClassVar, overload

class MjByteVec:
    def __init__(self, arg0, arg1: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __getitem__(self, index): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __setitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1) -> None: ...

class MjCharVec:
    def __init__(self, arg0: str, arg1: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> str: ...
    def __iter__(self) -> collections.abc.Iterator[str]: ...
    def __len__(self) -> int: ...
    def __setitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: str) -> None: ...

class MjDoubleVec:
    def __init__(self, arg0: typing.SupportsFloat | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> float: ...
    def __iter__(self) -> collections.abc.Iterator[float]: ...
    def __len__(self) -> int: ...
    def __setitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class MjFloatVec:
    def __init__(self, arg0: typing.SupportsFloat | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> float: ...
    def __iter__(self) -> collections.abc.Iterator[float]: ...
    def __len__(self) -> int: ...
    def __setitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class MjIntVec:
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> int: ...
    def __iter__(self) -> collections.abc.Iterator[int]: ...
    def __len__(self) -> int: ...
    def __setitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None: ...

class MjOption:
    ccd_iterations: int
    ccd_tolerance: float
    cone: int
    density: float
    disableactuator: int
    disableflags: int
    enableflags: int
    gravity: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    impratio: float
    integrator: int
    iterations: int
    jacobian: int
    ls_iterations: int
    ls_tolerance: float
    magnetic: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    noslip_iterations: int
    noslip_tolerance: float
    o_friction: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[5, 1]', 'flags.writeable']
    o_margin: float
    o_solimp: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[5, 1]', 'flags.writeable']
    o_solref: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    sdf_initpoints: int
    sdf_iterations: int
    sleep_tolerance: float
    solver: int
    timestep: float
    tolerance: float
    viscosity: float
    wind: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    def __init__(self, *args, **kwargs) -> None: ...

class MjSpec:
    from_zip: ClassVar[Callable] = ...
    to_zip: ClassVar[Callable] = ...
    assets: dict
    authored: MjsAuthored
    comment: str
    compiler: MjsCompiler
    copy_during_attach: None
    hasImplicitPluginElem: int
    memory: int
    meshdir: str
    modelfiledir: str
    modelname: str
    nconmax: int
    nemax: int
    njmax: int
    nkey: int
    nstack: int
    nuser_actuator: int
    nuser_body: int
    nuser_cam: int
    nuser_geom: int
    nuser_jnt: int
    nuser_sensor: int
    nuser_site: int
    nuser_tendon: int
    nuserdata: int
    option: MjOption
    override_assets: bool
    stat: MjStatistic
    strippath: int
    texturedir: str
    visual: MjVisual
    def __init__(self) -> None: ...
    def activate_plugin(self, name: str) -> None: ...
    def actuator(self, arg0: str) -> MjsActuator: ...
    def add_actuator(self, default: MjsDefault = ..., name: str | None = ..., gaintype: typing.SupportsInt | typing.SupportsIndex | None = ..., gainprm: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., biastype: typing.SupportsInt | typing.SupportsIndex | None = ..., biasprm: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., dyntype: typing.SupportsInt | typing.SupportsIndex | None = ..., dynprm: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., actdim: typing.SupportsInt | typing.SupportsIndex | None = ..., actearly: typing.SupportsInt | typing.SupportsIndex | None = ..., trntype: typing.SupportsInt | typing.SupportsIndex | None = ..., gear: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., target: str | None = ..., refsite: str | None = ..., slidersite: str | None = ..., cranklength: typing.SupportsFloat | typing.SupportsIndex | None = ..., lengthrange: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., inheritrange: typing.SupportsFloat | typing.SupportsIndex | None = ..., damping: object | None = ..., armature: typing.SupportsFloat | typing.SupportsIndex | None = ..., ctrllimited: typing.SupportsInt | typing.SupportsIndex | None = ..., ctrlrange: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., forcelimited: typing.SupportsInt | typing.SupportsIndex | None = ..., forcerange: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., actlimited: typing.SupportsInt | typing.SupportsIndex | None = ..., actrange: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., group: typing.SupportsInt | typing.SupportsIndex | None = ..., nsample: typing.SupportsInt | typing.SupportsIndex | None = ..., interp: typing.SupportsInt | typing.SupportsIndex | None = ..., delay: typing.SupportsFloat | typing.SupportsIndex | None = ..., userdata: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., plugin: MjsPlugin | None = ..., info: str | None = ...) -> MjsActuator: ...
    def add_default(self, arg0: str, arg1: MjsDefault) -> MjsDefault: ...
    def add_equality(self, default: MjsDefault = ..., name: str | None = ..., type: typing.SupportsInt | typing.SupportsIndex | None = ..., data: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., active: typing.SupportsInt | typing.SupportsIndex | None = ..., name1: str | None = ..., name2: str | None = ..., objtype: typing.SupportsInt | typing.SupportsIndex | None = ..., solref: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solimp: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsEquality: ...
    def add_exclude(self, name: str | None = ..., bodyname1: str | None = ..., bodyname2: str | None = ..., info: str | None = ...) -> MjsExclude: ...
    def add_flex(self, name: str | None = ..., contype: typing.SupportsInt | typing.SupportsIndex | None = ..., conaffinity: typing.SupportsInt | typing.SupportsIndex | None = ..., condim: typing.SupportsInt | typing.SupportsIndex | None = ..., priority: typing.SupportsInt | typing.SupportsIndex | None = ..., friction: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solmix: typing.SupportsFloat | typing.SupportsIndex | None = ..., solref: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solimp: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., margin: typing.SupportsFloat | typing.SupportsIndex | None = ..., gap: typing.SupportsFloat | typing.SupportsIndex | None = ..., dim: typing.SupportsInt | typing.SupportsIndex | None = ..., radius: typing.SupportsFloat | typing.SupportsIndex | None = ..., size: object | None = ..., internal: typing.SupportsInt | typing.SupportsIndex | None = ..., flatskin: typing.SupportsInt | typing.SupportsIndex | None = ..., selfcollide: typing.SupportsInt | typing.SupportsIndex | None = ..., passive: typing.SupportsInt | typing.SupportsIndex | None = ..., activelayers: typing.SupportsInt | typing.SupportsIndex | None = ..., group: typing.SupportsInt | typing.SupportsIndex | None = ..., edgestiffness: typing.SupportsFloat | typing.SupportsIndex | None = ..., edgedamping: typing.SupportsFloat | typing.SupportsIndex | None = ..., rgba: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., material: str | None = ..., young: typing.SupportsFloat | typing.SupportsIndex | None = ..., poisson: typing.SupportsFloat | typing.SupportsIndex | None = ..., damping: typing.SupportsFloat | typing.SupportsIndex | None = ..., thickness: typing.SupportsFloat | typing.SupportsIndex | None = ..., elastic2d: typing.SupportsInt | typing.SupportsIndex | None = ..., cellcount: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., order: typing.SupportsInt | typing.SupportsIndex | None = ..., nodebody: collections.abc.Sequence[str] | None = ..., vertbody: collections.abc.Sequence[str] | None = ..., node: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., vert: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., elem: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = ..., texcoord: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., elemtexcoord: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsFlex: ...
    def add_hfield(self, name: str | None = ..., content_type: str | None = ..., file: str | None = ..., size: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., nrow: typing.SupportsInt | typing.SupportsIndex | None = ..., ncol: typing.SupportsInt | typing.SupportsIndex | None = ..., userdata: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsHField: ...
    def add_key(self, name: str | None = ..., time: typing.SupportsFloat | typing.SupportsIndex | None = ..., qpos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., qvel: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., act: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., mpos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., mquat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., ctrl: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsKey: ...
    def add_material(self, default: MjsDefault = ..., name: str | None = ..., textures: collections.abc.Sequence[str] | None = ..., texuniform: typing.SupportsInt | typing.SupportsIndex | None = ..., texrepeat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., emission: typing.SupportsFloat | typing.SupportsIndex | None = ..., specular: typing.SupportsFloat | typing.SupportsIndex | None = ..., shininess: typing.SupportsFloat | typing.SupportsIndex | None = ..., reflectance: typing.SupportsFloat | typing.SupportsIndex | None = ..., metallic: typing.SupportsFloat | typing.SupportsIndex | None = ..., roughness: typing.SupportsFloat | typing.SupportsIndex | None = ..., rgba: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsMaterial: ...
    def add_mesh(self, default: MjsDefault = ..., name: str | None = ..., content_type: str | None = ..., file: str | None = ..., refpos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., refquat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., scale: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., inertia: typing.SupportsInt | typing.SupportsIndex | None = ..., smoothnormal: typing.SupportsInt | typing.SupportsIndex | None = ..., needsdf: typing.SupportsInt | typing.SupportsIndex | None = ..., maxhullvert: typing.SupportsInt | typing.SupportsIndex | None = ..., uservert: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., usernormal: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., usertexcoord: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., userface: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = ..., userfacenormal: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = ..., userfacetexcoord: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = ..., plugin: MjsPlugin | None = ..., material: str | None = ..., octree_maxdepth: typing.SupportsInt | typing.SupportsIndex | None = ..., info: str | None = ...) -> MjsMesh: ...
    def add_numeric(self, name: str | None = ..., data: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., size: typing.SupportsInt | typing.SupportsIndex | None = ..., info: str | None = ...) -> MjsNumeric: ...
    def add_pair(self, default: MjsDefault = ..., name: str | None = ..., geomname1: str | None = ..., geomname2: str | None = ..., condim: typing.SupportsInt | typing.SupportsIndex | None = ..., solref: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solreffriction: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solimp: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., margin: typing.SupportsFloat | typing.SupportsIndex | None = ..., gap: typing.SupportsFloat | typing.SupportsIndex | None = ..., friction: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsPair: ...
    def add_plugin(self, name: str | None = ..., plugin_name: str | None = ..., active: typing.SupportsInt | typing.SupportsIndex | None = ..., info: str | None = ...) -> MjsPlugin: ...
    def add_sensor(self, name: str | None = ..., type: typing.SupportsInt | typing.SupportsIndex | None = ..., objtype: typing.SupportsInt | typing.SupportsIndex | None = ..., objname: str | None = ..., reftype: typing.SupportsInt | typing.SupportsIndex | None = ..., refname: str | None = ..., intprm: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., datatype: typing.SupportsInt | typing.SupportsIndex | None = ..., needstage: typing.SupportsInt | typing.SupportsIndex | None = ..., dim: typing.SupportsInt | typing.SupportsIndex | None = ..., cutoff: typing.SupportsFloat | typing.SupportsIndex | None = ..., noise: typing.SupportsFloat | typing.SupportsIndex | None = ..., nsample: typing.SupportsInt | typing.SupportsIndex | None = ..., interp: typing.SupportsInt | typing.SupportsIndex | None = ..., delay: typing.SupportsFloat | typing.SupportsIndex | None = ..., interval: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., userdata: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., plugin: MjsPlugin | None = ..., info: str | None = ...) -> MjsSensor: ...
    def add_skin(self, name: str | None = ..., file: str | None = ..., material: str | None = ..., rgba: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., inflate: typing.SupportsFloat | typing.SupportsIndex | None = ..., group: typing.SupportsInt | typing.SupportsIndex | None = ..., vert: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., texcoord: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., face: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = ..., bodyname: collections.abc.Sequence[str] | None = ..., bindpos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., bindquat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., vertid: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]] | None = ..., vertweight: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]] | None = ..., info: str | None = ...) -> MjsSkin: ...
    def add_tendon(self, default: MjsDefault = ..., name: str | None = ..., stiffness: object | None = ..., springlength: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., damping: object | None = ..., frictionloss: typing.SupportsFloat | typing.SupportsIndex | None = ..., solref_friction: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solimp_friction: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., armature: typing.SupportsFloat | typing.SupportsIndex | None = ..., limited: typing.SupportsInt | typing.SupportsIndex | None = ..., actfrclimited: typing.SupportsInt | typing.SupportsIndex | None = ..., range: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., actfrcrange: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., margin: typing.SupportsFloat | typing.SupportsIndex | None = ..., solref_limit: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solimp_limit: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., material: str | None = ..., width: typing.SupportsFloat | typing.SupportsIndex | None = ..., rgba: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., group: typing.SupportsInt | typing.SupportsIndex | None = ..., userdata: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsTendon: ...
    def add_text(self, name: str | None = ..., data: str | None = ..., info: str | None = ...) -> MjsText: ...
    def add_texture(self, name: str | None = ..., type: typing.SupportsInt | typing.SupportsIndex | None = ..., colorspace: typing.SupportsInt | typing.SupportsIndex | None = ..., builtin: typing.SupportsInt | typing.SupportsIndex | None = ..., mark: typing.SupportsInt | typing.SupportsIndex | None = ..., rgb1: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., rgb2: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., markrgb: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., random: typing.SupportsFloat | typing.SupportsIndex | None = ..., height: typing.SupportsInt | typing.SupportsIndex | None = ..., width: typing.SupportsInt | typing.SupportsIndex | None = ..., nchannel: typing.SupportsInt | typing.SupportsIndex | None = ..., content_type: str | None = ..., file: str | None = ..., gridsize: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., gridlayout: object = ..., cubefiles: collections.abc.Sequence[str] | None = ..., data: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = ..., hflip: typing.SupportsInt | typing.SupportsIndex | None = ..., vflip: typing.SupportsInt | typing.SupportsIndex | None = ..., info: str | None = ...) -> MjsTexture: ...
    def add_tuple(self, name: str | None = ..., objtype: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = ..., objname: collections.abc.Sequence[str] | None = ..., objprm: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsTuple: ...
    def attach(self, child: MjSpec, prefix: str | None = ..., suffix: str | None = ..., site: object | None = ..., frame: object | None = ...) -> MjsFrame: ...
    def body(self, arg0: str) -> MjsBody: ...
    def camera(self, arg0: str) -> MjsCamera: ...
    def compile(self, vfs: MjVfs | None = ...) -> mujoco._structs.MjModel: ...
    def copy(self) -> MjSpec: ...
    @overload
    def delete(self, arg0: MjsDefault) -> None: ...
    @overload
    def delete(self, arg0: MjsBody) -> None: ...
    @overload
    def delete(self, arg0: MjsFrame) -> None: ...
    @overload
    def delete(self, arg0: MjsGeom) -> None: ...
    @overload
    def delete(self, arg0: MjsJoint) -> None: ...
    @overload
    def delete(self, arg0: MjsSite) -> None: ...
    @overload
    def delete(self, arg0: MjsCamera) -> None: ...
    @overload
    def delete(self, arg0: MjsLight) -> None: ...
    @overload
    def delete(self, arg0: MjsMaterial) -> None: ...
    @overload
    def delete(self, arg0: MjsMesh) -> None: ...
    @overload
    def delete(self, arg0: MjsPair) -> None: ...
    @overload
    def delete(self, arg0: MjsEquality) -> None: ...
    @overload
    def delete(self, arg0: MjsActuator) -> None: ...
    @overload
    def delete(self, arg0: MjsTendon) -> None: ...
    @overload
    def delete(self, arg0: MjsSensor) -> None: ...
    @overload
    def delete(self, arg0: MjsFlex) -> None: ...
    @overload
    def delete(self, arg0: MjsHField) -> None: ...
    @overload
    def delete(self, arg0: MjsSkin) -> None: ...
    @overload
    def delete(self, arg0: MjsTexture) -> None: ...
    @overload
    def delete(self, arg0: MjsKey) -> None: ...
    @overload
    def delete(self, arg0: MjsText) -> None: ...
    @overload
    def delete(self, arg0: MjsNumeric) -> None: ...
    @overload
    def delete(self, arg0: MjsExclude) -> None: ...
    @overload
    def delete(self, arg0: MjsTuple) -> None: ...
    @overload
    def delete(self, arg0: MjsPlugin) -> None: ...
    def encode(self, filename: str, model: object | None = ..., content_type: str | None = ...) -> int: ...
    def equality(self, arg0: str) -> MjsEquality: ...
    def exclude(self, arg0: str) -> MjsExclude: ...
    def find_default(self, arg0: str) -> MjsDefault: ...
    def flex(self, arg0: str) -> MjsFlex: ...
    def frame(self, arg0: str) -> MjsFrame: ...
    @staticmethod
    def from_file(filename: str, include: collections.abc.Mapping[str, bytes] | None = ..., assets: dict | None = ..., vfs: MjVfs = ...) -> MjSpec: ...
    @staticmethod
    def from_string(xml: str, include: collections.abc.Mapping[str, bytes] | None = ..., assets: dict | None = ..., vfs: MjVfs = ...) -> MjSpec: ...
    def geom(self, arg0: str) -> MjsGeom: ...
    def hfield(self, arg0: str) -> MjsHField: ...
    def joint(self, arg0: str) -> MjsJoint: ...
    def key(self, arg0: str) -> MjsKey: ...
    def light(self, arg0: str) -> MjsLight: ...
    def material(self, arg0: str) -> MjsMaterial: ...
    def mesh(self, arg0: str) -> MjsMesh: ...
    def numeric(self, arg0: str) -> MjsNumeric: ...
    def pair(self, arg0: str) -> MjsPair: ...
    def plugin(self, arg0: str) -> MjsPlugin: ...
    def recompile(self, arg0: object, arg1: object) -> object: ...
    @staticmethod
    def resolve_orientation(*args, **kwargs): ...
    def sensor(self, arg0: str) -> MjsSensor: ...
    def site(self, arg0: str) -> MjsSite: ...
    def skin(self, arg0: str) -> MjsSkin: ...
    def tendon(self, arg0: str) -> MjsTendon: ...
    def text(self, arg0: str) -> MjsText: ...
    def texture(self, arg0: str) -> MjsTexture: ...
    def to_file(self, arg0: str) -> None: ...
    def to_xml(self) -> str: ...
    def tuple(self, arg0: str) -> MjsTuple: ...
    @property
    def actuators(self) -> list: ...
    @property
    def bodies(self) -> list: ...
    @property
    def cameras(self) -> list: ...
    @property
    def default(self) -> MjsDefault: ...
    @property
    def equalities(self) -> list: ...
    @property
    def excludes(self) -> list: ...
    @property
    def flexes(self) -> list: ...
    @property
    def frames(self) -> list: ...
    @property
    def geoms(self) -> list: ...
    @property
    def hfields(self) -> list: ...
    @property
    def joints(self) -> list: ...
    @property
    def keys(self) -> list: ...
    @property
    def lights(self) -> list: ...
    @property
    def materials(self) -> list: ...
    @property
    def meshes(self) -> list: ...
    @property
    def numerics(self) -> list: ...
    @property
    def pairs(self) -> list: ...
    @property
    def parent(self) -> MjSpec: ...
    @property
    def plugins(self) -> list: ...
    @property
    def sensors(self) -> list: ...
    @property
    def sites(self) -> list: ...
    @property
    def skins(self) -> list: ...
    @property
    def tendons(self) -> list: ...
    @property
    def texts(self) -> list: ...
    @property
    def textures(self) -> list: ...
    @property
    def timer(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], '[9, 1]', 'flags.writeable']: ...
    @property
    def tuples(self) -> list: ...
    @property
    def worldbody(self) -> MjsBody: ...

class MjStatistic:
    center: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    extent: float
    meaninertia: float
    meanmass: float
    meansize: float
    def __init__(self, *args, **kwargs) -> None: ...

class MjStringVec:
    def __init__(self, arg0: str, arg1: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> str: ...
    def __iter__(self) -> collections.abc.Iterator[str]: ...
    def __len__(self) -> int: ...
    def __setitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: str) -> None: ...

class MjVfs:
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def __contains__(self, arg0: str) -> bool: ...
    def __delitem__(self, arg0: str) -> None: ...
    def __enter__(self) -> MjVfs: ...
    def __exit__(self, arg0: object, arg1: object, arg2: object) -> None: ...
    def __setitem__(self, arg0: str, arg1: bytes) -> None: ...

class MjVisual:
    global_: mujoco._structs.MjVisual.Global
    headlight: MjVisualHeadlight
    map: mujoco._structs.MjVisual.Map
    quality: mujoco._structs.MjVisual.Quality
    rgba: MjVisualRgba
    scale: mujoco._structs.MjVisual.Scale
    def __init__(self, *args, **kwargs) -> None: ...

class MjVisualHeadlight:
    active: int
    ambient: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[3, 1]', 'flags.writeable']
    diffuse: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[3, 1]', 'flags.writeable']
    specular: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[3, 1]', 'flags.writeable']
    def __init__(self, *args, **kwargs) -> None: ...

class MjVisualRgba:
    actuator: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    actuatornegative: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    actuatorpositive: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    bv: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    bvactive: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    camera: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    com: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    connect: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    constraint: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    contactforce: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    contactfriction: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    contactgap: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    contactpoint: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    contacttorque: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    crankbroken: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    fog: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    force: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    frustum: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    haze: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    inertia: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    joint: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    light: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    rangefinder: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    selectpoint: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    slidercrank: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    def __init__(self, *args, **kwargs) -> None: ...

class MjsActuator:
    actdim: int
    actearly: int
    actlimited: int
    actrange: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    armature: float
    biasprm: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[10, 1]', 'flags.writeable']
    biastype: mujoco._enums.mjtBias
    classname: MjsDefault
    cranklength: float
    ctrllimited: int
    ctrlrange: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    damping: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    delay: float
    dynprm: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[10, 1]', 'flags.writeable']
    dyntype: mujoco._enums.mjtDyn
    forcelimited: int
    forcerange: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    gainprm: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[10, 1]', 'flags.writeable']
    gaintype: mujoco._enums.mjtGain
    gear: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[6, 1]', 'flags.writeable']
    group: int
    info: str
    inheritrange: float
    interp: int
    lengthrange: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    name: str
    nsample: int
    plugin: MjsPlugin
    refsite: str
    slidersite: str
    target: str
    trntype: mujoco._enums.mjtTrn
    userdata: MjDoubleVec
    def __init__(self, *args, **kwargs) -> None: ...
    def set_to_adhesion(self, gain: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def set_to_cylinder(self, timeconst: typing.SupportsFloat | typing.SupportsIndex, bias: typing.SupportsFloat | typing.SupportsIndex, area: typing.SupportsFloat | typing.SupportsIndex, diameter: typing.SupportsFloat | typing.SupportsIndex = ...) -> None: ...
    def set_to_damper(self, kv: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def set_to_dcmotor(self, motorconst, resistance: typing.SupportsFloat | typing.SupportsIndex, nominal=..., saturation=..., inductance=..., cogging=..., controller=..., thermal=..., lugre=..., input_mode: typing.SupportsInt | typing.SupportsIndex = ...) -> None: ...
    def set_to_intvelocity(self, kp: typing.SupportsFloat | typing.SupportsIndex, kv: typing.SupportsFloat | typing.SupportsIndex = ..., dampratio: typing.SupportsFloat | typing.SupportsIndex = ..., timeconst: typing.SupportsFloat | typing.SupportsIndex = ..., inheritrange: bool = ...) -> None: ...
    def set_to_motor(self) -> None: ...
    def set_to_muscle(self, timeconst=..., tausmooth: typing.SupportsFloat | typing.SupportsIndex, range=..., force: typing.SupportsFloat | typing.SupportsIndex = ..., scale: typing.SupportsFloat | typing.SupportsIndex = ..., lmin: typing.SupportsFloat | typing.SupportsIndex = ..., lmax: typing.SupportsFloat | typing.SupportsIndex = ..., vmax: typing.SupportsFloat | typing.SupportsIndex = ..., fpmax: typing.SupportsFloat | typing.SupportsIndex = ..., fvmax: typing.SupportsFloat | typing.SupportsIndex = ...) -> None: ...
    def set_to_position(self, kp: typing.SupportsFloat | typing.SupportsIndex, kv: typing.SupportsFloat | typing.SupportsIndex = ..., dampratio: typing.SupportsFloat | typing.SupportsIndex = ..., timeconst: typing.SupportsFloat | typing.SupportsIndex = ..., inheritrange: bool = ...) -> None: ...
    def set_to_velocity(self, kv: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsAuthored:
    disableactuator: int
    disableflags: int
    enableflags: int
    option: int
    visual_global: int
    visual_headlight: int
    visual_map: int
    visual_quality: int
    visual_rgba: int
    visual_scale: int
    def __init__(self, *args, **kwargs) -> None: ...

class MjsBody:
    alt: MjsOrientation
    childclass: str
    classname: MjsDefault
    explicitinertial: int
    fullinertia: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[6, 1]', 'flags.writeable']
    gravcomp: float
    ialt: MjsOrientation
    inertia: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    info: str
    ipos: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    iquat: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[4, 1]', 'flags.writeable']
    mass: float
    mocap: int
    name: str
    plugin: MjsPlugin
    pos: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    quat: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[4, 1]', 'flags.writeable']
    sleep: mujoco._enums.mjtSleepPolicy
    userdata: MjDoubleVec
    def __init__(self, *args, **kwargs) -> None: ...
    def add_body(self, default: MjsDefault = ..., name: str | None = ..., childclass: str | None = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., quat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., axisangle: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., xyaxes: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., zaxis: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., euler: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., mass: typing.SupportsFloat | typing.SupportsIndex | None = ..., ipos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., iquat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., inertia: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., iaxisangle: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., ixyaxes: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., izaxis: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., ieuler: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., fullinertia: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., mocap: typing.SupportsInt | typing.SupportsIndex | None = ..., gravcomp: typing.SupportsFloat | typing.SupportsIndex | None = ..., sleep: typing.SupportsInt | typing.SupportsIndex | None = ..., userdata: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., explicitinertial: typing.SupportsInt | typing.SupportsIndex | None = ..., plugin: MjsPlugin | None = ..., info: str | None = ...) -> MjsBody: ...
    def add_camera(self, default: MjsDefault = ..., name: str | None = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., quat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., axisangle: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., xyaxes: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., zaxis: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., euler: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., mode: typing.SupportsInt | typing.SupportsIndex | None = ..., targetbody: str | None = ..., proj: typing.SupportsInt | typing.SupportsIndex | None = ..., resolution: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., output: typing.SupportsInt | typing.SupportsIndex | None = ..., fovy: typing.SupportsFloat | typing.SupportsIndex | None = ..., ipd: typing.SupportsFloat | typing.SupportsIndex | None = ..., intrinsic: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., sensor_size: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., focal_length: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., focal_pixel: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., principal_length: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., principal_pixel: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., userdata: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsCamera: ...
    def add_frame(self, default: MjsFrame = ..., name: str | None = ..., childclass: str | None = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., quat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., axisangle: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., xyaxes: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., zaxis: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., euler: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsFrame: ...
    def add_freejoint(self, **kwargs) -> MjsJoint: ...
    def add_geom(self, default: MjsDefault = ..., name: str | None = ..., type: typing.SupportsInt | typing.SupportsIndex | None = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., quat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., axisangle: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., xyaxes: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., zaxis: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., euler: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., fromto: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., size: object | None = ..., contype: typing.SupportsInt | typing.SupportsIndex | None = ..., conaffinity: typing.SupportsInt | typing.SupportsIndex | None = ..., condim: typing.SupportsInt | typing.SupportsIndex | None = ..., priority: typing.SupportsInt | typing.SupportsIndex | None = ..., friction: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solmix: typing.SupportsFloat | typing.SupportsIndex | None = ..., solref: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solimp: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., margin: typing.SupportsFloat | typing.SupportsIndex | None = ..., gap: typing.SupportsFloat | typing.SupportsIndex | None = ..., mass: typing.SupportsFloat | typing.SupportsIndex | None = ..., density: typing.SupportsFloat | typing.SupportsIndex | None = ..., typeinertia: typing.SupportsInt | typing.SupportsIndex | None = ..., fluid_ellipsoid: typing.SupportsInt | typing.SupportsIndex | None = ..., fluid_coefs: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., material: str | None = ..., rgba: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., group: typing.SupportsInt | typing.SupportsIndex | None = ..., hfieldname: str | None = ..., meshname: str | None = ..., fitscale: typing.SupportsFloat | typing.SupportsIndex | None = ..., userdata: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., plugin: MjsPlugin | None = ..., info: str | None = ...) -> MjsGeom: ...
    def add_joint(self, default: MjsDefault = ..., name: str | None = ..., type: typing.SupportsInt | typing.SupportsIndex | None = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., axis: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., ref: typing.SupportsFloat | typing.SupportsIndex | None = ..., align: typing.SupportsInt | typing.SupportsIndex | None = ..., stiffness: object | None = ..., springref: typing.SupportsFloat | typing.SupportsIndex | None = ..., springdamper: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., limited: typing.SupportsInt | typing.SupportsIndex | None = ..., range: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., margin: typing.SupportsFloat | typing.SupportsIndex | None = ..., solref_limit: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solimp_limit: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., actfrclimited: typing.SupportsInt | typing.SupportsIndex | None = ..., actfrcrange: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., armature: typing.SupportsFloat | typing.SupportsIndex | None = ..., damping: object | None = ..., frictionloss: typing.SupportsFloat | typing.SupportsIndex | None = ..., solref_friction: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solimp_friction: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., group: typing.SupportsInt | typing.SupportsIndex | None = ..., actgravcomp: typing.SupportsInt | typing.SupportsIndex | None = ..., userdata: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsJoint: ...
    def add_light(self, default: MjsDefault = ..., name: str | None = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., dir: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., mode: typing.SupportsInt | typing.SupportsIndex | None = ..., targetbody: str | None = ..., active: typing.SupportsInt | typing.SupportsIndex | None = ..., type: typing.SupportsInt | typing.SupportsIndex | None = ..., texture: str | None = ..., castshadow: typing.SupportsInt | typing.SupportsIndex | None = ..., bulbradius: typing.SupportsFloat | typing.SupportsIndex | None = ..., intensity: typing.SupportsFloat | typing.SupportsIndex | None = ..., range: typing.SupportsFloat | typing.SupportsIndex | None = ..., attenuation: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., cutoff: typing.SupportsFloat | typing.SupportsIndex | None = ..., exponent: typing.SupportsFloat | typing.SupportsIndex | None = ..., ambient: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., diffuse: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., specular: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsLight: ...
    def add_site(self, default: MjsDefault = ..., name: str | None = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., quat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., axisangle: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., xyaxes: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., zaxis: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., euler: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., fromto: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., size: object | None = ..., type: typing.SupportsInt | typing.SupportsIndex | None = ..., material: str | None = ..., group: typing.SupportsInt | typing.SupportsIndex | None = ..., rgba: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., userdata: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsSite: ...
    def attach_frame(self, frame: MjsFrame, prefix: str | None = ..., suffix: str | None = ...) -> MjsFrame: ...
    @overload
    def find_all(self, arg0: mujoco._enums.mjtObj) -> list: ...
    @overload
    def find_all(self, arg0: str) -> list: ...
    def find_child(self, arg0: str) -> MjsBody: ...
    def first_body(self) -> MjsBody: ...
    def first_camera(self) -> MjsCamera: ...
    def first_frame(self) -> MjsFrame: ...
    def first_geom(self) -> MjsGeom: ...
    def first_joint(self) -> MjsJoint: ...
    def first_light(self) -> MjsLight: ...
    def first_site(self) -> MjsSite: ...
    def make_flex(self, name: str, type: str | None = ..., dim: typing.SupportsInt | typing.SupportsIndex = ..., dof: str | None = ..., count: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = ..., cellcount: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] | None = ..., spacing: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., scale: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., radius: typing.SupportsFloat | typing.SupportsIndex = ..., mass: typing.SupportsFloat | typing.SupportsIndex = ..., inertiabox: typing.SupportsFloat | typing.SupportsIndex = ..., equality: typing.SupportsInt | typing.SupportsIndex = ..., rigid: typing.SupportsInt | typing.SupportsIndex = ..., flatskin: typing.SupportsInt | typing.SupportsIndex = ..., elastic2d: typing.SupportsInt | typing.SupportsIndex = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., quat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., origin: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., file: str | None = ..., vfs: MjVfs = ...) -> MjsFlex: ...
    def next_body(self, arg0: MjsBody) -> MjsBody: ...
    def next_camera(self, arg0: MjsCamera) -> MjsCamera: ...
    def next_frame(self, arg0: MjsFrame) -> MjsFrame: ...
    def next_geom(self, arg0: MjsGeom) -> MjsGeom: ...
    def next_joint(self, arg0: MjsJoint) -> MjsJoint: ...
    def next_light(self, arg0: MjsLight) -> MjsLight: ...
    def next_site(self, arg0: MjsSite) -> MjsSite: ...
    def set_frame(self, arg0: MjsFrame) -> None: ...
    def to_frame(self) -> MjsFrame: ...
    @property
    def bodies(self) -> list: ...
    @property
    def cameras(self) -> list: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def frame(self) -> MjsFrame: ...
    @property
    def frames(self) -> list: ...
    @property
    def geoms(self) -> list: ...
    @property
    def id(self) -> int: ...
    @property
    def joints(self) -> list: ...
    @property
    def lights(self) -> list: ...
    @property
    def parent(self) -> MjsBody: ...
    @property
    def signature(self) -> int: ...
    @property
    def sites(self) -> list: ...

class MjsCamera:
    alt: MjsOrientation
    classname: MjsDefault
    focal_length: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[2, 1]', 'flags.writeable']
    focal_pixel: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[2, 1]', 'flags.writeable']
    fovy: float
    info: str
    intrinsic: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    ipd: float
    mode: mujoco._enums.mjtCamLight
    name: str
    output: int
    pos: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    principal_length: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[2, 1]', 'flags.writeable']
    principal_pixel: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[2, 1]', 'flags.writeable']
    proj: mujoco._enums.mjtProjection
    quat: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[4, 1]', 'flags.writeable']
    resolution: typing.Annotated[numpy.typing.NDArray[numpy.int32], '[2, 1]', 'flags.writeable']
    sensor_size: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[2, 1]', 'flags.writeable']
    targetbody: str
    userdata: MjDoubleVec
    def __init__(self, *args, **kwargs) -> None: ...
    def set_frame(self, arg0: MjsFrame) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def frame(self) -> MjsFrame: ...
    @property
    def id(self) -> int: ...
    @property
    def parent(self) -> MjsBody: ...
    @property
    def signature(self) -> int: ...

class MjsCompiler:
    LRopt: mujoco._structs.MjLROpt
    alignfree: int
    authored: int
    autolimits: int
    balanceinertia: int
    boundinertia: float
    boundmass: float
    conflict: int
    degree: int
    discardvisual: int
    eulerseq: MjCharVec
    fitaabb: int
    fusestatic: int
    inertiafromgeom: int
    inertiagrouprange: typing.Annotated[numpy.typing.NDArray[numpy.int32], '[2, 1]', 'flags.writeable']
    meshdir: str
    saveinertial: int
    settotalmass: float
    texturedir: str
    usethread: int
    def __init__(self, *args, **kwargs) -> None: ...

class MjsDefault:
    actuator: MjsActuator
    camera: MjsCamera
    equality: MjsEquality
    flex: MjsFlex
    geom: MjsGeom
    joint: MjsJoint
    light: MjsLight
    material: MjsMaterial
    mesh: MjsMesh
    name: str
    pair: MjsPair
    site: MjsSite
    tendon: MjsTendon
    def __init__(self, *args, **kwargs) -> None: ...

class MjsElement:
    def __init__(self, *args, **kwargs) -> None: ...

class MjsEquality:
    active: int
    classname: MjsDefault
    data: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[11, 1]', 'flags.writeable']
    info: str
    name: str
    name1: str
    name2: str
    objtype: mujoco._enums.mjtObj
    solimp: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[5, 1]', 'flags.writeable']
    solref: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    type: mujoco._enums.mjtEq
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsExclude:
    bodyname1: str
    bodyname2: str
    info: str
    name: str
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsFlex:
    activelayers: int
    cellcount: typing.Annotated[numpy.typing.NDArray[numpy.int32], '[3, 1]', 'flags.writeable']
    conaffinity: int
    condim: int
    contype: int
    damping: float
    dim: int
    edgedamping: float
    edgestiffness: float
    elastic2d: int
    elem: MjIntVec
    elemtexcoord: MjIntVec
    flatskin: int
    friction: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    gap: float
    group: int
    info: str
    internal: int
    margin: float
    material: str
    name: str
    node: MjDoubleVec
    nodebody: MjStringVec
    order: int
    passive: int
    poisson: float
    priority: int
    radius: float
    rgba: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    selfcollide: int
    size: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    solimp: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[5, 1]', 'flags.writeable']
    solmix: float
    solref: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    texcoord: MjFloatVec
    thickness: float
    vert: MjDoubleVec
    vertbody: MjStringVec
    young: float
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsFrame:
    alt: MjsOrientation
    childclass: str
    info: str
    name: str
    pos: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    quat: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[4, 1]', 'flags.writeable']
    def __init__(self, *args, **kwargs) -> None: ...
    def add_body(self, default: MjsDefault = ..., name: str | None = ..., childclass: str | None = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., quat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., axisangle: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., xyaxes: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., zaxis: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., euler: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., mass: typing.SupportsFloat | typing.SupportsIndex | None = ..., ipos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., iquat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., inertia: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., iaxisangle: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., ixyaxes: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., izaxis: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., ieuler: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., fullinertia: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., mocap: typing.SupportsInt | typing.SupportsIndex | None = ..., gravcomp: typing.SupportsFloat | typing.SupportsIndex | None = ..., sleep: typing.SupportsInt | typing.SupportsIndex | None = ..., userdata: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., explicitinertial: typing.SupportsInt | typing.SupportsIndex | None = ..., plugin: MjsPlugin | None = ..., info: str | None = ...) -> MjsBody: ...
    def add_camera(self, default: MjsDefault = ..., name: str | None = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., quat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., axisangle: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., xyaxes: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., zaxis: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., euler: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., mode: typing.SupportsInt | typing.SupportsIndex | None = ..., targetbody: str | None = ..., proj: typing.SupportsInt | typing.SupportsIndex | None = ..., resolution: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., output: typing.SupportsInt | typing.SupportsIndex | None = ..., fovy: typing.SupportsFloat | typing.SupportsIndex | None = ..., ipd: typing.SupportsFloat | typing.SupportsIndex | None = ..., intrinsic: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., sensor_size: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., focal_length: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., focal_pixel: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., principal_length: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., principal_pixel: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., userdata: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsCamera: ...
    def add_frame(self, default: MjsFrame = ..., name: str | None = ..., childclass: str | None = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., quat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., axisangle: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., xyaxes: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., zaxis: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., euler: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsFrame: ...
    def add_geom(self, default: MjsDefault = ..., name: str | None = ..., type: typing.SupportsInt | typing.SupportsIndex | None = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., quat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., axisangle: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., xyaxes: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., zaxis: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., euler: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., fromto: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., size: object | None = ..., contype: typing.SupportsInt | typing.SupportsIndex | None = ..., conaffinity: typing.SupportsInt | typing.SupportsIndex | None = ..., condim: typing.SupportsInt | typing.SupportsIndex | None = ..., priority: typing.SupportsInt | typing.SupportsIndex | None = ..., friction: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solmix: typing.SupportsFloat | typing.SupportsIndex | None = ..., solref: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solimp: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., margin: typing.SupportsFloat | typing.SupportsIndex | None = ..., gap: typing.SupportsFloat | typing.SupportsIndex | None = ..., mass: typing.SupportsFloat | typing.SupportsIndex | None = ..., density: typing.SupportsFloat | typing.SupportsIndex | None = ..., typeinertia: typing.SupportsInt | typing.SupportsIndex | None = ..., fluid_ellipsoid: typing.SupportsInt | typing.SupportsIndex | None = ..., fluid_coefs: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., material: str | None = ..., rgba: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., group: typing.SupportsInt | typing.SupportsIndex | None = ..., hfieldname: str | None = ..., meshname: str | None = ..., fitscale: typing.SupportsFloat | typing.SupportsIndex | None = ..., userdata: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., plugin: MjsPlugin | None = ..., info: str | None = ...) -> MjsGeom: ...
    def add_joint(self, default: MjsDefault = ..., name: str | None = ..., type: typing.SupportsInt | typing.SupportsIndex | None = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., axis: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., ref: typing.SupportsFloat | typing.SupportsIndex | None = ..., align: typing.SupportsInt | typing.SupportsIndex | None = ..., stiffness: object | None = ..., springref: typing.SupportsFloat | typing.SupportsIndex | None = ..., springdamper: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., limited: typing.SupportsInt | typing.SupportsIndex | None = ..., range: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., margin: typing.SupportsFloat | typing.SupportsIndex | None = ..., solref_limit: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solimp_limit: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., actfrclimited: typing.SupportsInt | typing.SupportsIndex | None = ..., actfrcrange: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., armature: typing.SupportsFloat | typing.SupportsIndex | None = ..., damping: object | None = ..., frictionloss: typing.SupportsFloat | typing.SupportsIndex | None = ..., solref_friction: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., solimp_friction: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., group: typing.SupportsInt | typing.SupportsIndex | None = ..., actgravcomp: typing.SupportsInt | typing.SupportsIndex | None = ..., userdata: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsJoint: ...
    def add_light(self, default: MjsDefault = ..., name: str | None = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., dir: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., mode: typing.SupportsInt | typing.SupportsIndex | None = ..., targetbody: str | None = ..., active: typing.SupportsInt | typing.SupportsIndex | None = ..., type: typing.SupportsInt | typing.SupportsIndex | None = ..., texture: str | None = ..., castshadow: typing.SupportsInt | typing.SupportsIndex | None = ..., bulbradius: typing.SupportsFloat | typing.SupportsIndex | None = ..., intensity: typing.SupportsFloat | typing.SupportsIndex | None = ..., range: typing.SupportsFloat | typing.SupportsIndex | None = ..., attenuation: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., cutoff: typing.SupportsFloat | typing.SupportsIndex | None = ..., exponent: typing.SupportsFloat | typing.SupportsIndex | None = ..., ambient: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., diffuse: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., specular: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsLight: ...
    def add_site(self, default: MjsDefault = ..., name: str | None = ..., pos: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., quat: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., axisangle: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., xyaxes: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., zaxis: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., euler: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., fromto: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., size: object | None = ..., type: typing.SupportsInt | typing.SupportsIndex | None = ..., material: str | None = ..., group: typing.SupportsInt | typing.SupportsIndex | None = ..., rgba: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., userdata: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex] | None = ..., info: str | None = ...) -> MjsSite: ...
    def attach_body(self, body: MjsBody, prefix: str | None = ..., suffix: str | None = ...) -> MjsBody: ...
    def set_frame(self, arg0: MjsFrame) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def frame(self) -> MjsFrame: ...
    @property
    def id(self) -> int: ...
    @property
    def parent(self) -> MjsBody: ...
    @property
    def signature(self) -> int: ...

class MjsGeom:
    alt: MjsOrientation
    classname: MjsDefault
    conaffinity: int
    condim: int
    contype: int
    density: float
    fitscale: float
    fluid_coefs: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[5, 1]', 'flags.writeable']
    fluid_ellipsoid: float
    friction: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    fromto: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[6, 1]', 'flags.writeable']
    gap: float
    group: int
    hfieldname: str
    info: str
    margin: float
    mass: float
    material: str
    meshname: str
    name: str
    plugin: MjsPlugin
    pos: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    priority: int
    quat: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[4, 1]', 'flags.writeable']
    rgba: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    size: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    solimp: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[5, 1]', 'flags.writeable']
    solmix: float
    solref: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    type: mujoco._enums.mjtGeom
    typeinertia: mujoco._enums.mjtGeomInertia
    userdata: MjDoubleVec
    def __init__(self, *args, **kwargs) -> None: ...
    def set_frame(self, arg0: MjsFrame) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def frame(self) -> MjsFrame: ...
    @property
    def id(self) -> int: ...
    @property
    def parent(self) -> MjsBody: ...
    @property
    def signature(self) -> int: ...

class MjsHField:
    content_type: str
    file: str
    info: str
    name: str
    ncol: int
    nrow: int
    size: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[4, 1]', 'flags.writeable']
    userdata: MjFloatVec
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsJoint:
    actfrclimited: int
    actfrcrange: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    actgravcomp: int
    align: int
    armature: float
    axis: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    classname: MjsDefault
    damping: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    frictionloss: float
    group: int
    info: str
    limited: int
    margin: float
    name: str
    pos: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    range: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    ref: float
    solimp_friction: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[5, 1]', 'flags.writeable']
    solimp_limit: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[5, 1]', 'flags.writeable']
    solref_friction: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    solref_limit: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    springdamper: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    springref: float
    stiffness: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    type: mujoco._enums.mjtJoint
    userdata: MjDoubleVec
    def __init__(self, *args, **kwargs) -> None: ...
    def set_frame(self, arg0: MjsFrame) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def frame(self) -> MjsFrame: ...
    @property
    def id(self) -> int: ...
    @property
    def parent(self) -> MjsBody: ...
    @property
    def signature(self) -> int: ...

class MjsKey:
    act: MjDoubleVec
    ctrl: MjDoubleVec
    info: str
    mpos: MjDoubleVec
    mquat: MjDoubleVec
    name: str
    qpos: MjDoubleVec
    qvel: MjDoubleVec
    time: float
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsLight:
    active: int
    ambient: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[3, 1]', 'flags.writeable']
    attenuation: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[3, 1]', 'flags.writeable']
    bulbradius: float
    castshadow: int
    classname: MjsDefault
    cutoff: float
    diffuse: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[3, 1]', 'flags.writeable']
    dir: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    exponent: float
    info: str
    intensity: float
    mode: mujoco._enums.mjtCamLight
    name: str
    pos: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    range: float
    specular: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[3, 1]', 'flags.writeable']
    targetbody: str
    texture: str
    type: mujoco._enums.mjtLightType
    def __init__(self, *args, **kwargs) -> None: ...
    def set_frame(self, arg0: MjsFrame) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def frame(self) -> MjsFrame: ...
    @property
    def id(self) -> int: ...
    @property
    def parent(self) -> MjsBody: ...
    @property
    def signature(self) -> int: ...

class MjsMaterial:
    classname: MjsDefault
    emission: float
    info: str
    metallic: float
    name: str
    reflectance: float
    rgba: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    roughness: float
    shininess: float
    specular: float
    texrepeat: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[2, 1]', 'flags.writeable']
    textures: MjStringVec
    texuniform: int
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsMesh:
    classname: MjsDefault
    content_type: str
    file: str
    inertia: mujoco._enums.mjtMeshInertia
    info: str
    material: str
    maxhullvert: int
    name: str
    needsdf: int
    octree_maxdepth: int
    plugin: MjsPlugin
    refpos: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    refquat: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[4, 1]', 'flags.writeable']
    scale: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    smoothnormal: int
    userface: MjIntVec
    userfacenormal: MjIntVec
    userfacetexcoord: MjIntVec
    usernormal: MjFloatVec
    usertexcoord: MjFloatVec
    uservert: MjFloatVec
    def __init__(self, *args, **kwargs) -> None: ...
    def make_cone(self, nedge: typing.SupportsInt | typing.SupportsIndex, radius: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def make_hemisphere(self, resolution: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def make_plate(self, resolution=...) -> None: ...
    def make_sphere(self, subdivision: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def make_supersphere(self, resolution: typing.SupportsInt | typing.SupportsIndex, e: typing.SupportsFloat | typing.SupportsIndex, n: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def make_supertorus(self, resolution: typing.SupportsInt | typing.SupportsIndex, radius: typing.SupportsFloat | typing.SupportsIndex, s: typing.SupportsFloat | typing.SupportsIndex, t: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def make_wedge(self, resolution=..., fov=..., gamma: typing.SupportsFloat | typing.SupportsIndex = ...) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsNumeric:
    data: MjDoubleVec
    info: str
    name: str
    size: int
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsOrientation:
    axisangle: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[4, 1]', 'flags.writeable']
    euler: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    type: mujoco._enums.mjtOrientation
    xyaxes: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[6, 1]', 'flags.writeable']
    zaxis: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    def __init__(self, *args, **kwargs) -> None: ...

class MjsPair:
    classname: MjsDefault
    condim: int
    friction: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[5, 1]', 'flags.writeable']
    gap: float
    geomname1: str
    geomname2: str
    info: str
    margin: float
    name: str
    solimp: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[5, 1]', 'flags.writeable']
    solref: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    solreffriction: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsPlugin:
    active: int
    config: dict
    id: int
    info: str
    name: str
    plugin_name: str
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def signature(self) -> int: ...

class MjsSensor:
    cutoff: float
    datatype: mujoco._enums.mjtDataType
    delay: float
    dim: int
    info: str
    interp: int
    interval: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    intprm: typing.Annotated[numpy.typing.NDArray[numpy.int32], '[3, 1]', 'flags.writeable']
    name: str
    needstage: mujoco._enums.mjtStage
    noise: float
    nsample: int
    objname: str
    objtype: mujoco._enums.mjtObj
    plugin: MjsPlugin
    refname: str
    reftype: mujoco._enums.mjtObj
    type: mujoco._enums.mjtSensor
    userdata: MjDoubleVec
    def __init__(self, *args, **kwargs) -> None: ...
    def get_data_size(self) -> int: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsSite:
    alt: MjsOrientation
    classname: MjsDefault
    fromto: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[6, 1]', 'flags.writeable']
    group: int
    info: str
    material: str
    name: str
    pos: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    quat: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[4, 1]', 'flags.writeable']
    rgba: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    size: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    type: mujoco._enums.mjtGeom
    userdata: MjDoubleVec
    def __init__(self, *args, **kwargs) -> None: ...
    def attach_body(self, body: MjsBody, prefix: str | None = ..., suffix: str | None = ...) -> MjsBody: ...
    def set_frame(self, arg0: MjsFrame) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def frame(self) -> MjsFrame: ...
    @property
    def id(self) -> int: ...
    @property
    def parent(self) -> MjsBody: ...
    @property
    def signature(self) -> int: ...

class MjsSkin:
    bindpos: MjFloatVec
    bindquat: MjFloatVec
    bodyname: MjStringVec
    face: MjIntVec
    file: str
    group: int
    inflate: float
    info: str
    material: str
    name: str
    rgba: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    texcoord: MjFloatVec
    vert: MjFloatVec
    vertid: list
    vertweight: list
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsTendon:
    actfrclimited: int
    actfrcrange: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    armature: float
    damping: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    frictionloss: float
    group: int
    info: str
    limited: int
    margin: float
    material: str
    name: str
    range: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    rgba: typing.Annotated[numpy.typing.NDArray[numpy.float32], '[4, 1]', 'flags.writeable']
    solimp_friction: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[5, 1]', 'flags.writeable']
    solimp_limit: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[5, 1]', 'flags.writeable']
    solref_friction: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    solref_limit: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    springlength: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]', 'flags.writeable']
    stiffness: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    userdata: MjDoubleVec
    width: float
    def __init__(self, *args, **kwargs) -> None: ...
    def default(self) -> MjsDefault: ...
    def wrap_geom(self, arg0: str, arg1: str) -> MjsWrap: ...
    def wrap_joint(self, arg0: str, arg1: typing.SupportsFloat | typing.SupportsIndex) -> MjsWrap: ...
    def wrap_pulley(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> MjsWrap: ...
    def wrap_site(self, arg0: str) -> MjsWrap: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def path(self) -> MjsTendonPath: ...
    @property
    def signature(self) -> int: ...

class MjsTendonPath:
    def __init__(self, *args, **kwargs) -> None: ...
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> MjsWrap: ...
    def __len__(self) -> int: ...

class MjsText:
    data: str
    info: str
    name: str
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsTexture:
    builtin: int
    colorspace: mujoco._enums.mjtColorSpace
    content_type: str
    cubefiles: MjStringVec
    data: bytes
    file: str
    gridlayout: MjCharVec
    gridsize: typing.Annotated[numpy.typing.NDArray[numpy.int32], '[2, 1]', 'flags.writeable']
    height: int
    hflip: int
    info: str
    mark: int
    markrgb: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    name: str
    nchannel: int
    random: float
    rgb1: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    rgb2: typing.Annotated[numpy.typing.NDArray[numpy.float64], '[3, 1]', 'flags.writeable']
    type: mujoco._enums.mjtTexture
    vflip: int
    width: int
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsTuple:
    info: str
    name: str
    objname: MjStringVec
    objprm: MjDoubleVec
    objtype: MjIntVec
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def compiler(self) -> MjsCompiler: ...
    @property
    def id(self) -> int: ...
    @property
    def signature(self) -> int: ...

class MjsWrap:
    info: str
    type: mujoco._enums.mjtWrap
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def coef(self) -> object: ...
    @property
    def divisor(self) -> object: ...
    @property
    def sidesite(self) -> MjsSite: ...
    @property
    def target(self) -> object: ...
