from bam.actuator import CurrentControlledActuator as CurrentControlledActuator, VoltageControlledActuator as VoltageControlledActuator
from bam.message import bright as bright, print_parameter as print_parameter, yellow as yellow
from bam.parameter import Parameter as Parameter
from bam.testbench import Pendulum as Pendulum, Testbench as Testbench

class MXActuator(VoltageControlledActuator):
    def __init__(self, testbench_class: Testbench) -> None: ...
    def initialize(self) -> None: ...
    def get_extra_inertia(self) -> float: ...

class XL320Actuator(VoltageControlledActuator):
    def __init__(self, testbench_class: Testbench) -> None: ...
    def initialize(self) -> None: ...
    def get_extra_inertia(self) -> float: ...

XL330_ENCODER_COUNTS_PER_REV: int
XL330_KP_DIVISOR: int
XL330_PWM_LIMIT: int

class XL330Actuator(VoltageControlledActuator):
    def __init__(self, testbench_class: Testbench) -> None: ...
    def initialize(self) -> None: ...
    def get_extra_inertia(self) -> float: ...

class XL330CurrentActuator(CurrentControlledActuator):
    def __init__(self, testbench_class: Testbench) -> None: ...
    def initialize(self) -> None: ...
    def get_extra_inertia(self) -> float: ...
