from _typeshed import Incomplete
from bam.actuator import Actuator as Actuator, ArrayLike as ArrayLike
from bam.parameter import Parameter as Parameter
from bam.testbench import Pendulum as Pendulum, Testbench as Testbench

class ErobActuator(Actuator):
    max_amps: float
    max_volts: float
    damping: Incomplete
    def __init__(self, testbench_class: Testbench, damping: float = 2.0) -> None: ...
    def initialize(self) -> None: ...
    kp: Incomplete
    def load_log(self, log: dict): ...
    def control_unit(self) -> str: ...
    def compute_control(self, q_target: ArrayLike, q: ArrayLike, dq: ArrayLike, dt: float) -> ArrayLike | None: ...
    def compute_torque(self, control: ArrayLike | None, torque_enable: bool, q: ArrayLike, dq: ArrayLike) -> ArrayLike: ...
    def get_extra_inertia(self) -> float: ...
