from _typeshed import Incomplete
from bam.trajectory import cubic_interpolate as cubic_interpolate

class Client:
    context: Incomplete
    socket: Incomplete
    running: bool
    lock: Incomplete
    wait_lock: Incomplete
    orders: Incomplete
    statuses: Incomplete
    def __init__(self, host: str) -> None: ...
    def set_order(self, index: int, mode: str = 'position', target: float = 0.0): ...
    def position_control(self, index: int, target_position: float, target_velocity: float = 0.0, kp: float = 10.0, damping: float = 2.0, max_amps: float = 12.0): ...
    def stop(self, index: int): ...
    def send(self) -> None: ...
    def get_statuses(self): ...
    def run(self) -> None: ...
    def sync(self) -> None: ...
    def wait_stability(self, index: int): ...
    def goto_safe(self, index: int, target: float, duration: float = 3.0): ...
    def run_background(self) -> None: ...
    def stop(self) -> None: ...
