from .message import print_parameter as print_parameter, yellow as yellow
from .testbench import Testbench as Testbench
from _typeshed import Incomplete
from bam.parameter import Parameter as Parameter

ArrayLike: Incomplete

class Backend:
    def clamp(self, x: ArrayLike, low: ArrayLike, high: ArrayLike) -> ArrayLike: ...

class NumpyBackend(Backend):
    def clamp(self, x: ArrayLike, low: ArrayLike, high: ArrayLike) -> ArrayLike: ...

class TorchBackend(Backend):
    def clamp(self, x: ArrayLike, low: ArrayLike, high: ArrayLike) -> ArrayLike: ...

class Actuator:
    testbench_class: Incomplete
    testbench: Testbench | None
    backend: Backend
    def __init__(self, testbench_class: Testbench) -> None: ...
    model: Incomplete
    def set_model(self, model) -> None: ...
    def reset(self) -> None: ...
    def load_log(self, log: dict): ...
    def initialize(self) -> None: ...
    def control_unit(self) -> str: ...
    def compute_control(self, q_target: ArrayLike, q: ArrayLike, dq: ArrayLike, dt: float) -> ArrayLike | None: ...
    def compute_torque(self, control: ArrayLike | None, torque_enable: bool, q: ArrayLike, dq: ArrayLike) -> ArrayLike: ...
    def get_extra_inertia(self) -> float: ...
    def to_mujoco(self) -> None: ...

class DCMotorActuator(Actuator):
    vin: Incomplete
    kp: Incomplete
    def __init__(self, testbench_class: Testbench, vin: float, kp: float) -> None: ...
    def load_log(self, log: dict): ...
    def initialize(self) -> None: ...

class VoltageControlledActuator(DCMotorActuator):
    error_gain: Incomplete
    max_pwm: Incomplete
    max_current: Incomplete
    def __init__(self, testbench_class: Testbench, vin: float, kp: float, error_gain: float, max_pwm: float = 1.0, max_current: float | None = None) -> None: ...
    def control_unit(self) -> str: ...
    def compute_control(self, q_target: ArrayLike, q: ArrayLike, dq: ArrayLike, dt: float) -> ArrayLike | None: ...
    def compute_torque(self, control: ArrayLike | None, torque_enable: bool, q: ArrayLike, dq: ArrayLike) -> ArrayLike: ...
    def to_mujoco(self) -> None: ...

class CurrentControlledActuator(DCMotorActuator):
    error_gain: Incomplete
    def __init__(self, testbench_class: Testbench, vin: float, kp: float, error_gain: float) -> None: ...
    def control_unit(self) -> str: ...
    def initialize(self) -> None: ...
    def compute_control(self, q_target: ArrayLike, q: ArrayLike, dq: ArrayLike, dt: float) -> ArrayLike | None: ...
    def compute_torque(self, control: ArrayLike | None, torque_enable: bool, q: ArrayLike, dq: ArrayLike) -> ArrayLike: ...
    def to_mujoco(self) -> None: ...
