"""
This type stub file was generated by pyright.
"""

import numpy as np
import torch
from typing import TYPE_CHECKING, Union
from .testbench import Testbench

if TYPE_CHECKING:
    ...
ArrayLike = Union[float, np.ndarray, "torch.Tensor"]
class Backend:
    """Abstracts the array library so the actuator math is vectorization-agnostic.

    Only operations that differ between numpy and torch (currently ``clamp``)
    live here; plain arithmetic (``+``, ``*``, ``**``, ``np.sign`` …) broadcasts
    the same way for both, so it is written directly in the actuator methods.
    """
    def clamp(self, x: ArrayLike, low: ArrayLike, high: ArrayLike) -> ArrayLike:
        ...
    


class NumpyBackend(Backend):
    def clamp(self, x: ArrayLike, low: ArrayLike, high: ArrayLike) -> ArrayLike:
        ...
    


class TorchBackend(Backend):
    def clamp(self, x: ArrayLike, low: ArrayLike, high: ArrayLike) -> ArrayLike:
        ...
    


class Actuator:
    """Abstract base class for all BAM actuator models.

    Subclasses implement the firmware control law and the motor torque equation
    for a specific actuator family.  An actuator is always attached to a
    :class:`~bam.model.Model` via :meth:`~bam.model.Model.set_actuator`, which
    calls :meth:`initialize` to create the motor parameters (``kt``, ``R``, …)
    on the model.

    :param testbench_class: Class used to instantiate the testbench when a log
        is loaded (typically :class:`~bam.testbench.Pendulum`).
    """
    def __init__(self, testbench_class: Testbench) -> None:
        ...
    
    def set_model(self, model): # -> None:
        """Attach this actuator to a model and run :meth:`initialize`.

        :param model: :class:`~bam.model.Model` instance to attach to.
        """
        ...
    
    def reset(self): # -> None:
        ...
    
    def load_log(self, log: dict): # -> None:
        """Called when a log is loaded.

        Instantiates the testbench from the log metadata (mass, length, …)
        and updates actuator settings (kp, vin) from the log.

        :param log: Log dict as loaded from a processed JSON file.
        """
        ...
    
    def initialize(self):
        """Create motor parameters on the attached model.

        Called automatically by :meth:`set_model`. Must create at minimum
        ``self.model.kt`` and ``self.model.R`` as :class:`~bam.parameter.Parameter`
        instances.
        """
        ...
    
    def control_unit(self) -> str:
        """Return the physical unit of the control signal (e.g. ``"volts"``, ``"amps"``)."""
        ...
    
    def compute_control(self, q_target: ArrayLike, q: ArrayLike, dq: ArrayLike, dt: float) -> ArrayLike | None:
        """Compute the control signal from the current state and target.

        The state arguments (``q_target``, ``q``, ``dq``) may be Python floats,
        numpy arrays or torch tensors; the computation is elementwise and the
        result matches their (broadcast) type. Use :class:`TorchBackend` for a
        fully vectorized, autograd-friendly evaluation.

        :param q_target: Target joint angle(s) [rad].
        :param q: Current joint angle(s) [rad].
        :param dq: Current joint velocity(ies) [rad/s].
        :param dt: Timestep [s].
        :returns: Control signal in the unit given by :meth:`control_unit`.
        """
        ...
    
    def compute_torque(self, control: ArrayLike | None, torque_enable: bool, q: ArrayLike, dq: ArrayLike) -> ArrayLike:
        """Compute the motor torque from the control signal and current state.

        As with :meth:`compute_control`, the array arguments accept floats, numpy
        arrays or torch tensors and the result follows their (broadcast) type.

        :param control: Control signal (volts, amps, or Nm depending on the actuator).
        :param torque_enable: Whether the actuator is powered.
        :param q: Current joint angle(s) [rad].
        :param dq: Current joint velocity(ies) [rad/s].
        :returns: Motor torque [Nm].
        """
        ...
    
    def get_extra_inertia(self) -> float:
        """Return the actuator's apparent inertia added to the load [kg·m²]."""
        ...
    
    def to_mujoco(self):
        ...
    


class DCMotorActuator(Actuator):
    """Base class for DC motor actuators with a supply voltage and a P-gain.

    Loads ``kp`` and ``vin`` from the log metadata when :meth:`load_log` is called.

    :param testbench_class: Testbench class (see :class:`Actuator`).
    :param vin: Default supply voltage [V].
    :param kp: Default firmware proportional gain.
    """
    def __init__(self, testbench_class: Testbench, vin: float, kp: float) -> None:
        ...
    
    def load_log(self, log: dict): # -> None:
        ...
    
    def initialize(self): # -> None:
        """Create ``kt`` and ``R`` parameters on the attached model."""
        ...
    


class VoltageControlledActuator(DCMotorActuator):
    """Voltage-controlled servo with a firmware P-position controller.

    Implements the control law
    ``duty_cycle = clip(error_gain * kp * Δq, -max_pwm, max_pwm)``
    and the DC motor torque equation with back-EMF.

    :param testbench_class: Testbench class (see :class:`Actuator`).
    :param vin: Supply voltage [V].
    :param kp: Firmware proportional gain.
    :param error_gain: Converts ``kp * Δq`` to a duty cycle in [−1, 1].
        Depends on the servo's internal encoder resolution and gain scaling.
    :param max_pwm: Maximum duty cycle magnitude (default 1.0).
    :param max_current: Firmware current limit [A]. If not None, the firmware
        limiter is modelled in :meth:`compute_control` as a constraint on the PWM
        duty cycle that *attempts* to keep the motor current within
        ``[-max_current, max_current]``. Because the firmware can only bound the
        duty cycle (not synthesize arbitrary voltage), the limit is only reached
        when the battery voltage allows it; at high speed the back-EMF can make
        it unreachable. ``None`` (default) → no current limiting.
    """
    def __init__(self, testbench_class: Testbench, vin: float, kp: float, error_gain: float, max_pwm: float = ..., max_current: float | None = ...) -> None:
        ...
    
    def control_unit(self) -> str:
        ...
    
    def compute_control(self, q_target: ArrayLike, q: ArrayLike, dq: ArrayLike, dt: float) -> ArrayLike | None:
        """Compute the voltage command from position error.

        When ``max_current`` is set, the firmware current limiter is modelled as
        a constraint on the duty cycle rather than a clamp on the output torque.
        The firmware can only act on the PWM duty cycle, so the achievable
        current is bounded by the battery voltage: solving :math:`|I| \\le
        I_\\text{max}` for :math:`I = (\\text{duty} \\cdot v_\\text{in} - k_t
        \\dot{q}) / R` gives the duty window

        .. math::

            \\frac{k_t \\dot{q} - R\\,I_\\text{max}}{v_\\text{in}}
            \\le \\text{duty} \\le
            \\frac{k_t \\dot{q} + R\\,I_\\text{max}}{v_\\text{in}}

        The commanded duty is clamped to this window (the limiter *attempt*) and
        then to the physical ``[-max_pwm, max_pwm]`` range (the battery reality),
        applied last. When back-EMF is large the window can fall outside the
        physical range, so the limiter saturates without actually holding the
        current at ``max_current`` — exactly as the real firmware behaves.

        :param q_target: Target joint angle(s) [rad].
        :param q: Current joint angle(s) [rad].
        :param dq: Current joint velocity(ies) [rad/s]. Used by the current
            limiter (back-EMF term); otherwise unused.
        :param dt: Timestep [s] (unused here).
        :returns: Voltage [V] sent to the motor.
        """
        ...
    
    def compute_torque(self, control: ArrayLike | None, torque_enable: bool, q: ArrayLike, dq: ArrayLike) -> ArrayLike:
        """Compute motor torque using the DC motor equation with back-EMF.

        :math:`\\tau = k_t V / R - k_t^2 \\dot{q} / R`

        The firmware current limit is *not* applied here: it is modelled as a
        duty-cycle constraint in :meth:`compute_control`, so the voltage
        ``control`` already reflects the (possibly saturated) current limiter and
        the torque follows directly from the DC motor equation.

        :param control: Voltage(s) [V].
        :param torque_enable: If ``False``, returns zero torque.
        :param q: Current joint angle(s) [rad] (unused here).
        :param dq: Current joint velocity(ies) [rad/s].
        :returns: Motor torque [Nm].
        """
        ...
    
    def to_mujoco(self): # -> None:
        ...
    


class CurrentControlledActuator(DCMotorActuator):
    """Current-controlled servo with a firmware P-position controller.

    The controller outputs a target current proportional to position error,
    clipped by both the voltage limits and a user-configurable current cap.

    :param testbench_class: Testbench class (see :class:`Actuator`).
    :param vin: Supply voltage [V], used to compute the current saturation.
    :param kp: Firmware proportional gain.
    :param error_gain: Converts ``kp * Δq`` to a target current [A].
    """
    def __init__(self, testbench_class: Testbench, vin: float, kp: float, error_gain: float) -> None:
        ...
    
    def control_unit(self) -> str:
        ...
    
    def initialize(self): # -> None:
        ...
    
    def compute_control(self, q_target: ArrayLike, q: ArrayLike, dq: ArrayLike, dt: float) -> ArrayLike | None:
        """Compute the current command from position error.

        Clips the P-controller output by both the back-EMF voltage limit and
        the ``current_limit`` parameter. The voltage-limit bounds are themselves
        elementwise (they depend on ``dq``), so with the torch backend the clamp
        broadcasts per environment.

        :param q_target: Target joint angle(s) [rad].
        :param q: Current joint angle(s) [rad].
        :param dq: Current joint velocity(ies) [rad/s].
        :param dt: Timestep [s] (unused here).
        :returns: Target current [A].
        """
        ...
    
    def compute_torque(self, control: ArrayLike | None, torque_enable: bool, q: ArrayLike, dq: ArrayLike) -> ArrayLike:
        """Compute motor torque from current command.

        :math:`\\tau = k_t I - b_{\\text{active}} \\dot{q}`

        :param control: Current command(s) [A].
        :param torque_enable: If ``False``, returns zero torque.
        :param q: Current joint angle(s) [rad] (unused here).
        :param dq: Current joint velocity(ies) [rad/s].
        :returns: Motor torque [Nm].
        """
        ...
    
    def to_mujoco(self): # -> None:
        ...
    


