from colorama import Back as Back

def error(message) -> None: ...
def bright(message) -> None: ...
def run_or_fail(cmd) -> None: ...
def emphasis(text): ...
def yellow(text): ...
def red(text): ...
def success(text): ...
def die(message) -> None: ...
def print_parameter(name, value, infos=None, warning=None) -> None: ...
