"""
This type stub file was generated by pyright.
"""

def error(message): # -> None:
    ...

def bright(message): # -> None:
    ...

def run_or_fail(cmd): # -> None:
    ...

def emphasis(text):
    ...

def yellow(text):
    ...

def red(text):
    ...

def success(text):
    ...

def die(message):
    ...

def print_parameter(name, value, infos=..., warning=...): # -> None:
    ...

