"""
This type stub file was generated by pyright.
"""

import mujoco
import mujoco_warp as mjwarp
import torch
from dataclasses import dataclass
from typing import TYPE_CHECKING
from mjlab.actuator.actuator import Actuator, ActuatorCfg, ActuatorCmd, CommandField
from mjlab.entity import Entity
from .model import Model

"""BAM actuator models for mjlab (MuJoCo Warp).

Wraps any BAM Model (m1–m6) into mjlab's actuator framework. All friction
computations are fully vectorized over the (num_envs, num_joints) batch
dimension using PyTorch.

Usage example — bundled motor::

    from bam.mjlab import make_bam_actuator_cfg

    actuator_cfg = make_bam_actuator_cfg(
        motor_name="xl330",
        model="m6",
        target_names_expr=(r".*",),
    )

Usage example — custom JSON path::

    actuator_cfg = make_bam_actuator_cfg(
        json_path="params/xl330/m6.json",
        target_names_expr=(r".*",),
    )
"""
if TYPE_CHECKING:
    ...
_FRICTION_DOF_CONSTRAINT = ...
@dataclass(kw_only=True)
class BamActuatorCfg(ActuatorCfg):
    """Configuration for a BAM actuator compatible with mjlab.

    Specify the model with **one** of two mutually exclusive approaches:

    * **Bundled motor**: set ``motor_name`` (e.g. "xl330") and ``model``
      (e.g. "m6"). The path is resolved automatically from the ``params/``
      directory bundled with the library.
    * **Custom JSON**: set ``json_path`` to a BAM params JSON file produced by
      ``bam.fit``.

    :param motor_name: Name of the bundled motor. Currently supported: "xl330", "xl320", "mx106", "mx64", "erob80:50", and "erob80:100". Mutually exclusive with ``json_path``.
    :param model: Model variant to use with ``motor_name``, one of "m1"–"m6". Mutually exclusive with ``json_path``.
    :param json_path: Path to a custom BAM params JSON file produced by ``bam.fit``. Mutually exclusive with ``motor_name`` and ``model``.
    :param target_names_expr: Tuple of regex patterns to match actuated joint names.
    :param vin: Supply voltage override [V]. ``None`` → uses the value in the JSON.
    :param kp_fw: Firmware P-gain override. ``None`` → uses the value in the JSON.
    :param vin_range: If set, a per-env battery voltage is sampled uniformly from this
        range at startup and held constant across resets. Takes precedence over ``vin``.
    :param vin_drop_gain_range: If set, a per-env internal-resistance gain [V/Nm] is sampled uniformly
        from this range at startup. Models the voltage drop V_drop = gain * Σ|τ| due to
        battery + cable resistance. Gain should be approximately resistance / Kt.
        Held constant across resets.
    :param vin_min: Hard lower bound on the effective supply voltage [V] after applying the
        voltage drop. Ensures ``vin`` never falls below this value regardless of the load.
        ``None`` → no lower bound.
    :param delay_min_lag: Minimum command delay in simulation steps. Models the latency
        between the policy output and the motor response. ``0`` → no delay.
    :param delay_max_lag: Maximum command delay in simulation steps. Set greater than
        ``delay_min_lag`` to randomize the delay across environments.
    :param delay_hold_prob: Probability of keeping the same lag value at each step.
        ``0.0`` → lag is resampled every ``delay_update_period`` steps.
    :param delay_update_period: Number of steps between lag updates. ``0`` → updated
        every step.
    :param delay_per_env_phase: Whether each environment starts with an independent
        delay phase offset. ``True`` → environments are not synchronized.
    :param stiff_frictionloss: When ``True`` (default), stiffen the joint-friction
        constraint (``solref_friction`` / ``solimp_friction``). MuJoCo Warp has no
        noslip solver, so the frictionloss constraint stays soft and a statically-held
        joint creeps; this is the GPU-side substitute. Uses MuJoCo's direct
        (timestep-independent) solref form so it works regardless of the sim ``dt``.
        Set ``False`` to keep MuJoCo's soft defaults.
    """
    motor_name: str | None = ...
    model: str | None = ...
    json_path: str | None = ...
    vin: float | None = ...
    kp_fw: float | None = ...
    vin_range: tuple[float, float] | None = ...
    vin_drop_gain_range: tuple[float, float] | None = ...
    vin_min: float | None = ...
    stiff_frictionloss: bool = ...
    def __post_init__(self) -> None:
        ...
    
    def build(self, entity: Entity, target_ids: list[int], target_names: list[str]) -> BamActuator:
        ...
    


class BamActuator(Actuator):
    """BAM actuator for mjlab — fully vectorized over all parallel environments.

    Implements the BAM torque pipeline:

    1. **Voltage control law** — firmware P-controller (position error → duty
       cycle → voltage).
    2. **DC motor torque** — back-EMF equation (voltage → torque).
    3. **Friction budget** — BAM m1–m6 friction model (Coulomb, Stribeck,
       load-dependent, directional, quadratic).

    Rather than injecting a passive friction torque into the returned motor
    torque, the friction budget is written into MuJoCo's native
    ``dof_frictionloss`` (dry friction) and ``dof_damping`` (viscous) each step,
    exactly like :class:`bam.mujoco.MujocoController`. MuJoCo's constraint solver
    then applies the static-friction clipping (BAM Algorithm 1) itself.

    .. important::
        Because every environment carries a different friction budget, the
        ``dof_frictionloss`` and ``dof_damping`` model fields must be expanded
        per world *before* stepping. After building the environment, call::

            env.sim.expand_model_fields(("dof_frictionloss", "dof_damping"))

        (or add a ``randomize_field`` event for those fields). Otherwise the
        fields alias a single shared buffer and per-env writes are invalid.

    Per-environment gain scaling is supported via :meth:`set_gains`.
    """
    cfg: BamActuatorCfg
    def __init__(self, cfg: BamActuatorCfg, entity: Entity, target_ids: list[int], target_names: list[str]) -> None:
        ...
    
    _STIFF_SOLREF_FRICTION = ...
    _STIFF_SOLIMP_FRICTION = ...
    def edit_spec(self, spec: mujoco.MjSpec, target_names: list[str]) -> None:
        """Convert position actuators to motor mode and zero MuJoCo friction.

        The ``frictionloss`` and ``damping`` are zeroed here only as an initial
        value; :meth:`compute` rewrites them every step with the BAM friction
        budget so MuJoCo's solver applies the friction natively. When
        ``cfg.stiff_frictionloss`` is set, the friction constraint's
        ``solref_friction`` / ``solimp_friction`` are stiffened here too (see
        :meth:`_set_friction_stiffness`).
        """
        ...
    
    def initialize(self, mj_model: mujoco.MjModel, model: mjwarp.Model, data: mjwarp.Data, device: str) -> None:
        ...
    
    def reset(self, env_ids: torch.Tensor | slice | None = ...) -> None:
        ...
    
    @property
    def command_field(self) -> CommandField:
        ...
    
    def set_gains(self, env_ids: torch.Tensor | slice, kp_scale: torch.Tensor | None = ..., kd_scale: torch.Tensor | None = ...) -> None:
        """Scale firmware gains for a subset of environments."""
        ...
    
    def reset_gains(self, env_ids: torch.Tensor | slice) -> None:
        """Restore default gains for a subset of environments."""
        ...
    
    def compute(self, cmd: ActuatorCmd) -> torch.Tensor:
        """Compute output torques for all environments — shape ``(N, J)``.

        The firmware control law and the DC-motor torque equation are delegated
        to the underlying BAM actuator's :meth:`~bam.actuator.Actuator.compute_control`
        and :meth:`~bam.actuator.Actuator.compute_torque` (running on the Torch
        backend, so their clamps vectorize over ``(N, J)``). This backend only
        injects the mjlab-specific per-environment quantities around those calls:

        * ``vin`` (with the optional battery drop) → ``actuator.vin``
        * ``kp * kp_scale`` → ``actuator.kp``
        * ``kd_scale`` → applied to the back-EMF via a scaled velocity
        """
        ...
    


_ENTITY_NAME = ...
_JOINT_NAME = ...
class Simulator:
    """mjlab (MuJoCo Warp) GPU simulator, mirroring :class:`bam.simulate.Simulator`.

    Builds the *same* pendulum spec as :class:`bam.testbench_mujoco.Pendulum`,
    drives the hinge with a :class:`BamActuator` (via :class:`BamActuatorCfg`),
    and steps everything on mjlab's vectorized MuJoCo-Warp pipeline.

    The point of this backend is to exploit mjlab's GPU parallelization: a whole
    batch of logs is rolled out **at once**, one environment per log. Every
    environment shares the same motor model (kt, R, friction budget) but carries
    its own pendulum parameters (``mass``/``arm_mass``/``length``) and firmware
    gains (``kp``/``vin``). This is exactly what makes evaluating a model over a
    directory of logs (as in :mod:`bam.mae`) embarrassingly parallel here.

    How the per-environment "specs" are made different
    --------------------------------------------------
    mjlab replicates one compiled model across all worlds, so per-log physical
    parameters are injected *after* building the sim by expanding the relevant
    model fields per world and writing each environment's values:

    * ``body_mass`` / ``body_ipos`` / ``body_inertia`` — the pendulum inertial,
      computed by :meth:`bam.testbench_mujoco.Pendulum.inertial_params`, followed
      by :meth:`mjlab.sim.Simulation.recompute_constants` to refresh the derived
      mass matrix.
    * ``kp`` — applied through the actuator's per-env ``kp_scale``.
    * ``vin`` — written into the actuator's per-env ``vin_tensor``.

    :param json_path: Path to a BAM params JSON file (produced by ``bam.fit``).
        Mutually exclusive with ``motor_name`` / ``model``.
    :param motor_name: Bundled motor name (e.g. ``"mx106"``). Combine with ``model``.
    :param model: Bundled model variant (``"m1"``–``"m6"``). Combine with ``motor_name``.
    :param device: Torch device, defaults to ``"cuda"`` when available else ``"cpu"``.
    :param integrator: MuJoCo integrator, ``"euler"`` (default, matching the CPU
        backend) or ``"implicitfast"``.
    :param stiff_frictionloss: Forwarded to :class:`BamActuatorCfg`. When ``True``
        (default), the joint-friction constraint is stiffened to counter MuJoCo
        Warp's lack of a noslip solver (see :attr:`BamActuatorCfg.stiff_frictionloss`).
    """
    def __init__(self, json_path: str | None = ..., *, motor_name: str | None = ..., model: str | None = ..., device: str | None = ..., integrator: str = ..., stiff_frictionloss: bool = ...) -> None:
        ...
    
    def rollout_log(self, log: dict, reset_period: float | None = ...) -> tuple:
        """Roll out a single log. See :meth:`rollout_logs`.

        :returns: Tuple ``(positions, velocities, controls)`` — lists over timesteps.
        """
        ...
    
    def rollout_logs(self, logs: list[dict], reset_period: float | None = ...) -> tuple[list, list, list]:
        """Roll out a batch of logs in parallel — one environment per log.

        All logs must share the same timestep ``dt`` (a single MuJoCo timestep is
        used for the whole batch) but may otherwise differ in pendulum parameters,
        firmware gains, initial state, goal trajectory and length. Logs of
        different lengths are padded (holding the last command) and their outputs
        trimmed back to their own length.

        :param logs: List of processed log dicts.
        :param reset_period: If set, re-synchronize each environment's state to its
            log at this interval [s] (mirrors the reference simulator).
        :returns: Tuple ``(positions, velocities, controls)`` — each a list (one
            entry per log) of per-timestep values. ``controls`` are the applied
            joint torques [Nm] (the BAM actuator drives MuJoCo in motor mode).
        """
        ...
    


