import mujoco
import mujoco_warp as mjwarp
import torch
from .actuator import TorchBackend as TorchBackend, VoltageControlledActuator as VoltageControlledActuator
from .model import Model as Model, load_model as load_model
from .testbench_mujoco import Pendulum as Pendulum
from _typeshed import Incomplete
from dataclasses import dataclass
from mjlab.actuator.actuator import Actuator, ActuatorCfg, ActuatorCmd as ActuatorCmd, CommandField as CommandField
from mjlab.entity import Entity as Entity
from pathlib import Path as Path

@dataclass(kw_only=True)
class BamActuatorCfg(ActuatorCfg):
    motor_name: str | None = ...
    model: str | None = ...
    json_path: str | None = ...
    vin: float | None = ...
    kp_fw: float | None = ...
    vin_range: tuple[float, float] | None = ...
    vin_drop_gain_range: tuple[float, float] | None = ...
    vin_min: float | None = ...
    stiff_frictionloss: bool = ...
    def __post_init__(self) -> None: ...
    def build(self, entity: Entity, target_ids: list[int], target_names: list[str]) -> BamActuator: ...

class BamActuator(Actuator):
    cfg: BamActuatorCfg
    vin_tensor: torch.Tensor | None
    vin_drop_gain: torch.Tensor | None
    kp_scale: torch.Tensor | None
    kd_scale: torch.Tensor | None
    default_kp_scale: torch.Tensor | None
    default_kd_scale: torch.Tensor | None
    def __init__(self, cfg: BamActuatorCfg, entity: Entity, target_ids: list[int], target_names: list[str]) -> None: ...
    def edit_spec(self, spec: mujoco.MjSpec, target_names: list[str]) -> None: ...
    def initialize(self, mj_model: mujoco.MjModel, model: mjwarp.Model, data: mjwarp.Data, device: str) -> None: ...
    def reset(self, env_ids: torch.Tensor | slice | None = None) -> None: ...
    @property
    def command_field(self) -> CommandField: ...
    def set_gains(self, env_ids: torch.Tensor | slice, kp_scale: torch.Tensor | None = None, kd_scale: torch.Tensor | None = None) -> None: ...
    def reset_gains(self, env_ids: torch.Tensor | slice) -> None: ...
    def compute(self, cmd: ActuatorCmd) -> torch.Tensor: ...
    # stubgen drops leading-underscore members; FrictionDRBamActuator in
    # src/robot_actuator.py overrides this hook, so it has to be declared.
    def _compute_friction_budget(self, motor_torque: torch.Tensor, external_torque: torch.Tensor, stribeck_coeff: torch.Tensor) -> torch.Tensor: ...

class Simulator:
    device: Incomplete
    integrator: Incomplete
    stiff_frictionloss: Incomplete
    def __init__(self, json_path: str | None = None, *, motor_name: str | None = None, model: str | None = None, device: str | None = None, integrator: str = 'euler', stiff_frictionloss: bool = True) -> None: ...
    def rollout_log(self, log: dict, reset_period: float | None = None) -> tuple: ...
    def rollout_logs(self, logs: list[dict], reset_period: float | None = None) -> tuple[list, list, list]: ...
