"""
This type stub file was generated by pyright.
"""

import mujoco
from .model import Model

class MujocoController:
    """
    A MujocoController is a class allowing to apply the torque and update frictions
    from the computed model during a simulation.

    :param bam.Model model: Model to use (can be loaded using load_model)
    :param str actuator: Actuator to control. The actuated joint properties will be updated. This can be a list of actuators
    :param mujoco.MjModel mujoco_model: The mujoco model
    :param mujoco.MjData mujoco_data: The mujoco data
    :param float | None vin_drop_gain: The voltage drop gain, if not None the voltage will be reduced by 
        vin_drop_gain * load, where load is the sum of the absolute value of the motor torques
    :param float | None vin_min: the minimum voltage, if not None the voltage will not go below this value
    """
    def __init__(self, model: Model, actuator: str, mujoco_model: mujoco.MjModel, mujoco_data: mujoco.MjData, vin_drop_gain: float | None = ..., vin_min: float | None = ...) -> None:
        ...
    
    def get_q_target(self, name: str) -> float:
        """Return the current target position for a named actuator [rad].

        :param name: Actuator name as passed to the constructor.
        """
        ...
    
    def set_q_target(self, name: str, q_target: float): # -> None:
        """Set the target position for a named actuator.

        :param name: Actuator name as passed to the constructor.
        :param q_target: Desired joint angle [rad].
        """
        ...
    
    def reset(self, qpos): # -> None:
        """Reset the controller to a given joint position state.

        Should be called after every ``mujoco.mj_resetData`` to clear the
        internal target and voltage-drop state.

        :param qpos: Full ``mj_data.qpos`` array. The controller extracts
            the positions of its controlled joints.
        """
        ...
    
    def update(self): # -> None:
        """
        Update the controlled actuator(s) data:
        - Torque to apply
        - Friction parameters
        - Damping
        """
        ...
    


class Simulator:
    """MuJoCo mirror of :class:`bam.simulate.Simulator`.

    Rolls out a BAM model against the same testbench, but uses MuJoCo physics
    (from :class:`bam.testbench_mujoco.Pendulum`) instead of the hand-written
    Euler integrator, with the actuator driven by a :class:`MujocoController`.

    Vectorization is handled the naive way: one independent ``(MjModel, MjData,
    MujocoController)`` triplet is created per environment and they are ticked
    one by one. This is intentionally not efficient — the point of this
    simulator is to validate that the MuJoCo spec and the controller reproduce
    the reference simulation.

    :param model: BAM friction model to simulate.
    :param actuator: Name used for the hinge joint and the motor actuator in
        the generated spec (and the name the :class:`MujocoController` controls).
    """
    def __init__(self, model: Model, actuator: str = ...) -> None:
        ...
    
    def reset(self, q: float = ..., dq: float = ...): # -> None:
        """(Re)build the environments and reset them to a given state.

        ``q`` and ``dq`` may be scalars or arrays; the number of environments is
        the length of the (broadcast) inputs.

        :param q: Initial joint angle(s) [rad].
        :param dq: Initial joint velocity(ies) [rad/s].
        """
        ...
    
    @property
    def q(self): # -> NDArray[Any]:
        """Current joint angle(s) [rad] (scalar if a single environment)."""
        ...
    
    @property
    def dq(self): # -> NDArray[Any]:
        """Current joint velocity(ies) [rad/s] (scalar if a single environment)."""
        ...
    
    def step(self, goal_position, torque_enable, dt: float): # -> None:
        """Advance every environment by one timestep.

        Unlike :meth:`bam.simulate.Simulator.step` (which is fed a raw control
        signal), the actuator here is a position controller: the input is the
        goal position and the :class:`MujocoController` computes the control and
        the applied torque internally.

        :param goal_position: Target joint angle(s) [rad], scalar or per-environment.
        :param torque_enable: Whether the actuator is powered (scalar or per-env).
            When ``False`` the applied torque is zeroed and only gravity and
            friction act.
        :param dt: Timestep [s].
        """
        ...
    
    def rollout_log(self, log: dict, reset_period: float = ...): # -> tuple[list[Any], list[Any], list[Any]]:
        """Roll out the model against a recorded log and return predicted trajectories.

        Mirrors :meth:`bam.simulate.Simulator.rollout_log`, but drives the
        actuator through the :class:`MujocoController` (position control from the
        recorded ``goal_position``), so it is equivalent to the reference
        simulator's ``simulate_control=True`` mode.

        :param log: Processed log dict (see :meth:`bam.logs.Logs.make_batch`).
        :param reset_period: If set, re-synchronize the state to the log at this
            interval [s].
        :returns: Tuple ``(positions, velocities, controls)`` — lists of values
            at each timestep. ``controls`` are the voltages/currents computed by
            the controller.
        """
        ...
    


def load_config(path: str, mujoco_model: mujoco.MjModel, mujoco_data: mujoco.MjData, kp: float, vin: float) -> tuple:
    """
    Loads a BAM configuration file and returns the list of controllers and the mapping dicts.

    Args:
        path (str): path to the configuration file
        mujoco_model (mujoco.MjModel): the mujoco model
        mujoco_data (mujoco.MjData): the mujoco data
        kp (float): the proportional gain
        vin (float): the input voltage

    Returns:
        list: list of controllers, dofs to model mapping, dofs to id mapping
    """
    ...

