"""
This type stub file was generated by pyright.
"""

class Parameter:
    """A scalar model parameter with bounds and an optimization flag.

    Parameters are attached to a :class:`~bam.model.Model` by
    :meth:`~bam.model.Model.set_actuator` and collected by
    :meth:`~bam.model.Model.get_parameters` for optimization.

    :param value: Initial value.
    :param min: Lower bound used by the optimizer.
    :param max: Upper bound used by the optimizer.
    :param optimize: If ``False`` the parameter is held fixed during fitting.
    """
    def __init__(self, value: float, min: float, max: float, optimize: bool = ...) -> None:
        ...
    


