"""
This type stub file was generated by pyright.
"""

from .model import Model

class Simulator:
    """Single-axis pendulum simulator used during identification.

    Implements the BAM simulation loop: firmware control law → motor torque →
    friction budget → stopping-torque clipping → Euler integration.  Used by
    ``bam.fit`` to roll out a model against recorded logs and compute the
    identification loss.

    :param model: BAM friction model to simulate.
    """
    def __init__(self, model: Model) -> None:
        ...
    
    def reset(self, q: float = ..., dq: float = ...): # -> None:
        """
        Resets the simulation to a given state
        """
        ...
    
    def step(self, control: None | float, torque_enable: bool, dt: float): # -> None:
        """Advance the simulation by one timestep.

        :param control: Control signal sent to the actuator (voltage, current,
            or torque depending on the actuator type). ``None`` is treated as zero.
        :param torque_enable: Whether the actuator is powered. When ``False``
            the motor torque is zero and only gravity and friction act.
        :param dt: Timestep [s].
        """
        ...
    
    def rollout_log(self, log: dict, reset_period: float = ..., simulate_control: bool = ...): # -> tuple[list[Any], list[Any], list[Any]]:
        """Roll out the model against a recorded log and return predicted trajectories.

        :param log: Processed log dict as returned by :meth:`bam.logs.Logs.make_batch`
            or loaded directly from a processed JSON file.
        :param reset_period: If set, re-synchronize the simulator state to the
            log at this interval [s]. Useful when error accumulation destabilizes
            long rollouts.
        :param simulate_control: If ``True``, recompute the control signal from
            the simulated state using the firmware control law. If ``False``,
            use the control values recorded in the log.
        :returns: Tuple ``(positions, velocities, controls)`` — lists of values
            at each timestep.
        """
        ...
    


