from _typeshed import Incomplete

class Testbench:
    def compute_mass(self, q: float, dq: float) -> float: ...
    def compute_bias(self, q: float, dq: float) -> float: ...

class Pendulum(Testbench):
    mass: Incomplete
    arm_mass: Incomplete
    length: Incomplete
    def __init__(self, log: dict) -> None: ...
    def compute_mass(self, q: float, dq: float) -> float: ...
    def compute_bias(self, q: float, dq: float) -> float: ...
