"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn
from tensordict import TensorDict
from typing import Any, NoReturn
from rsl_rl.env import VecEnv

class RandomNetworkDistillation(nn.Module):
    """Implementation of Random Network Distillation (RND).

    References:
        - Schwarke et al. "Curiosity-Driven Learning of Joint Locomotion and Manipulation Tasks." CoRL (2023).
        - Burda et al. "Exploration by Random Network Distillation." arXiv preprint arXiv:1810.12894 (2018).
    """
    def __init__(self, num_states: int, obs_groups: dict, num_outputs: int, predictor_hidden_dims: tuple[int, ...] | list[int], target_hidden_dims: tuple[int, ...] | list[int], activation: str = ..., weight: float = ..., state_normalization: bool = ..., reward_normalization: bool = ..., device: str = ..., weight_schedule: dict | None = ...) -> None:
        """Initialize the RND module.

        - If :attr:`state_normalization` is True, then the input state is normalized using an Empirical Normalization
          layer.
        - If :attr:`reward_normalization` is True, then the intrinsic reward is normalized using an Empirical Discounted
          Variation Normalization layer.
        - If the hidden dimensions are -1 in the predictor and target networks configuration, then the number of states
          is used as the hidden dimension.

        Args:
            num_states: Number of states/inputs to the predictor and target networks.
            obs_groups: Dictionary of observation groups.
            num_outputs: Number of outputs (embedding size) of the predictor and target networks.
            predictor_hidden_dims: List of hidden dimensions of the predictor network.
            target_hidden_dims: List of hidden dimensions of the target network.
            activation: Activation function.
            weight: Scaling factor of the intrinsic reward.
            state_normalization: Whether to normalize the input state.
            reward_normalization: Whether to normalize the intrinsic reward.
            device: Device to use.
            weight_schedule: Type of schedule to use for the RND weight parameter.
                It is a dictionary with the following keys:

                - "mode": Type of schedule to use for the RND weight parameter.
                    - "constant": Constant weight schedule.
                    - "step": Step weight schedule.
                    - "linear": Linear weight schedule.

                For the "step" weight schedule, the following parameters are required:

                - "final_step": Step at which the weight parameter is set to the final value.
                - "final_value": Final value of the weight parameter.

                For the "linear" weight schedule, the following parameters are required:
                - "initial_step": Step at which the weight parameter is set to the initial value.
                - "final_step": Step at which the weight parameter is set to the final value.
                - "final_value": Final value of the weight parameter.
        """
        ...
    
    def get_intrinsic_reward(self, obs: TensorDict) -> torch.Tensor:
        """Compute weighted intrinsic rewards from prediction error in embedding space."""
        ...
    
    def forward(self, *args: Any, **kwargs: dict[str, Any]) -> NoReturn:
        """Disallow generic forward calls for this module."""
        ...
    
    def train(self, mode: bool = ...) -> RandomNetworkDistillation:
        """Set training mode for predictor and optional normalizers."""
        ...
    
    def eval(self) -> RandomNetworkDistillation:
        """Set the module to evaluation mode."""
        ...
    
    def get_rnd_state(self, obs: TensorDict) -> torch.Tensor:
        """Extract and concatenate observation groups used as theRND state."""
        ...
    
    def update_normalization(self, obs: TensorDict) -> None:
        """Update state-normalization statistics from observations."""
        ...
    


def resolve_rnd_config(alg_cfg: dict, obs: TensorDict, obs_groups: dict[str, list[str]], env: VecEnv) -> dict:
    """Resolve the RND configuration.

    Args:
        alg_cfg: Algorithm configuration dictionary.
        obs: Observation dictionary.
        obs_groups: Observation groups dictionary.
        env: Environment object.

    Returns:
        The resolved algorithm configuration dictionary.
    """
    ...

