"""
This type stub file was generated by pyright.
"""

import tensordict._reductions
from tensordict._lazy import LazyStackedTensorDict
from tensordict._nestedkey import NestedKey
from tensordict._td import TensorDict, cat, from_consolidated, from_module, from_modules, from_pytree, fromkeys, is_tensor_collection, lazy_stack, load, load_memmap, maybe_dense_stack, memmap, save, stack
from tensordict._unbatched import UnbatchedTensor
from tensordict.base import TensorDictBase, _default_is_leaf as default_is_leaf, _is_leaf_nontensor as is_leaf_nontensor, from_any, from_dict, from_h5, from_namedtuple, from_struct_array, from_tuple, get_defaults_to_none, set_get_defaults_to_none
from tensordict.functional import dense_stack_tds, make_tensordict, merge_tensordicts, pad, pad_sequence
from tensordict.memmap import MemoryMappedTensor
from tensordict.persistent import PersistentTensorDict
from tensordict.tensorclass import MetaData, NonTensorData, NonTensorDataBase, NonTensorStack, TensorClass, from_dataclass, tensorclass
from tensordict.utils import assert_allclose_td, assert_close, capture_non_tensor_stack, is_batchedtensor, is_non_tensor, is_tensorclass, lazy_legacy, list_to_stack, parse_tensor_dict_string, set_capture_non_tensor_stack, set_lazy_legacy, set_list_to_stack, unravel_key, unravel_key_list
from tensordict._pytree import *
from tensordict.nn import TensorDictParams, as_tensordict_module
from tensordict._version import __version__

__all__ = ["TensorDict", "TensorDictBase", "LazyStackedTensorDict", "UnbatchedTensor", "TensorClass", "MemoryMappedTensor", "PersistentTensorDict", "NestedKey", "from_dict", "from_any", "from_h5", "from_namedtuple", "from_struct_array", "from_tuple", "from_dataclass", "fromkeys", "from_module", "from_modules", "from_pytree", "from_consolidated", "make_tensordict", "stack", "cat", "lazy_stack", "maybe_dense_stack", "dense_stack_tds", "memmap", "load_memmap", "save", "load", "merge_tensordicts", "pad", "pad_sequence", "is_tensor_collection", "is_batchedtensor", "is_non_tensor", "is_tensorclass", "assert_close", "assert_allclose_td", "unravel_key", "unravel_key_list", "parse_tensor_dict_string", "default_is_leaf", "is_leaf_nontensor", "get_defaults_to_none", "set_get_defaults_to_none", "capture_non_tensor_stack", "set_capture_non_tensor_stack", "lazy_legacy", "set_lazy_legacy", "list_to_stack", "set_list_to_stack", "tensorclass", "MetaData", "NonTensorData", "NonTensorDataBase", "NonTensorStack", "as_tensordict_module", "TensorDictParams", "__version__"]
