"""
This type stub file was generated by pyright.
"""

import torch
from typing import Any, Callable, Dict, List, Literal, Mapping, OrderedDict, Self, Sequence, TYPE_CHECKING, Tuple, Type
from tensordict._td import _TensorDictKeysView
from tensordict._tensorcollection import TensorCollection
from tensordict.base import CompatibleType, T, TensorDictBase
from tensordict.memmap import MemoryMappedTensor
from tensordict.utils import DeviceType, IndexType, NestedKey, _as_context_manager, cache, erase_cache, lock_blocked
from torch import Tensor
from torch._C._functorch import _add_batch_dim, _remove_batch_dim

_has_funcdim = ...
_has_functorch = ...
_has_functorch = ...
if TYPE_CHECKING:
    ...
else:
    ...
class _LazyStackedTensorDictKeysView(_TensorDictKeysView):
    tensordict: LazyStackedTensorDict
    def __len__(self) -> int:
        ...
    
    def __contains__(self, item): # -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class LazyStackedTensorDict(TensorDictBase):
    """A Lazy stack of TensorDicts.

    When stacking TensorDicts together, the default behaviour is to put them
    in a stack that is not instantiated.
    This allows to seamlessly work with stacks of tensordicts with operations
    that will affect the original tensordicts.

    Args:
         *tensordicts (TensorDict instances): a list of tensordict with
            same batch size.
         stack_dim (int): a dimension (between `-td.ndimension()` and
            `td.ndimension()-1` along which the stack should be performed.
         hook_out (callable, optional): a callable to execute after :meth:`~.get`.
         hook_in (callable, optional): a callable to execute before :meth:`~.set`.
         stack_dim_name (str, optional): the name of the stack dimension.
            Defaults to ``None``.
        strict_shape (bool, optional): if ``True``, every tensordict's shapes must match.
            Defaults to ``False``.

    Examples:
        >>> from tensordict import TensorDict
        >>> import torch
        >>> tds = [TensorDict({'a': torch.randn(3, 4)}, batch_size=[3])
        ...     for _ in range(10)]
        >>> td_stack = torch.stack(tds, -1)
        >>> print(td_stack.shape)
        torch.Size([3, 10])
        >>> print(td_stack.get("a").shape)
        torch.Size([3, 10, 4])
        >>> print(td_stack[:, 0] is tds[0])
        True

    .. note:: Lazy stacks support assignment via lists. For consistency, the lists should be
        presented as `tensor.tolist()` data structure. This means that the length of the first
        level of the nested lists should match the first dimension of the lazy stack (whether or
        not this is the stack dimension).

            >>> td = LazyStackedTensorDict(TensorDict(), TensorDict(), stack_dim=0)
            >>> td["a"] = [torch.ones(2), torch.zeros(1)]
            >>> assert td[1]["a"] == torch.zeros(1)
            >>> td["b"] = ["a string", "another string"]
            >>> assert td[1]["b"] == "another string"

    .. note:: When using the :meth:`~.get` method, one can pass `as_nested_tensor`, `as_padded_tensor`
        or the `as_list` arguments to control how the data should be presented if the dimensions of the
        tensors mismatch. When passed, the nesting/padding will occur regardless of whether the
        dimensions mismatch or not.

    """
    _is_vmapped: bool = ...
    _device: torch.device | None = ...
    @classmethod
    def __torch_function__(cls, func: Callable, types: tuple[type, ...], args: tuple[Any, ...] = ..., kwargs: dict[str, Any] | None = ...) -> Callable:
        ...
    
    _td_dim_name = ...
    _safe = ...
    _lazy = ...
    def __init__(self, *tensordicts: T, stack_dim: int = ..., hook_out: callable | None = ..., hook_in: callable | None = ..., batch_size: Sequence[int] | None = ..., device: torch.device | None = ..., names: Sequence[str] | None = ..., stack_dim_name: str | None = ..., strict_shape: bool = ...) -> None:
        ...
    
    @_fails_exclusive_keys
    def to_dict(self, *, retain_none: bool = ..., convert_tensors: bool | Literal["numpy"] = ..., tolist_first: bool = ...) -> dict[str, Any]:
        ...
    
    @classmethod
    def from_dict(cls, input_dict: Dict[str, Dict[NestedKey, Any]] | List[Dict[NestedKey, Any]], *other, auto_batch_size: bool = ..., batch_size=..., device=..., batch_dims=..., stack_dim_name=..., stack_dim=..., names: list[str] | None = ...): # -> None:
        ...
    
    @classmethod
    def from_list(cls, input: list[Mapping], *, auto_batch_size: bool | None = ..., batch_size: torch.Size | None = ..., device: torch.device | None = ..., batch_dims: int | None = ..., names: list[str] | None = ..., lazy: bool | None = ...) -> Self:
        ...
    
    @_fails_exclusive_keys
    def state_dict(self, destination=..., prefix=..., keep_vars=..., flatten=...) -> OrderedDict[str, Any]:
        ...
    
    @_fails_exclusive_keys
    def flatten_keys(self, separator: str = ..., inplace: bool = ..., is_leaf: Callable[[Type], bool] | None = ...) -> Self:
        ...
    
    @_fails_exclusive_keys
    def unflatten_keys(self, separator: str = ..., inplace: bool = ...) -> Self:
        ...
    
    @property
    def device(self) -> torch.device | None:
        ...
    
    @device.setter
    def device(self, value: DeviceType) -> None:
        ...
    
    def clear_device_(self) -> Self:
        ...
    
    @property
    def batch_size(self) -> torch.Size:
        ...
    
    @batch_size.setter
    def batch_size(self, new_size: torch.Size) -> None:
        ...
    
    @property
    @cache
    def names(self): # -> list[Any]:
        ...
    
    @names.setter
    @erase_cache
    def names(self, value): # -> None:
        ...
    
    def get_item_shape(self, key): # -> Size:
        """Gets the shape of an item in the lazy stack.

        Heterogeneous dimensions are returned as -1.

        This implementation is inefficient as it will attempt to stack the items
        to compute their shape, and should only be used for printing.
        """
        ...
    
    def is_shared(self) -> bool:
        ...
    
    def is_memmap(self) -> bool:
        ...
    
    def get(self, key: NestedKey, *args, as_list: bool = ..., as_padded_tensor: bool = ..., as_nested_tensor: bool = ..., padding_side: str = ..., layout: torch.layout = ..., padding_value: float | int | bool = ..., **kwargs) -> CompatibleType:
        """Gets the value stored with the input key.

        Args:
            key (str, tuple of str): key to be queried. If tuple of str it is
                equivalent to chained calls of getattr.
            default: default value if the key is not found in the tensordict. Defaults to ``None``.

                .. warning::
                    Previously, if a key was not present in the tensordict and no default
                    was passed, a `KeyError` was raised. From v0.7, this behaviour has been changed
                    and a `None` value is returned instead (in accordance with the what dict.get behavior).
                    To adopt the old behavior, set the environment variable `export TD_GET_DEFAULTS_TO_NONE='0'` or call
                    :func`~tensordict.set_get_defaults_to_none(False)`.

        Keyword Args:
            as_list (bool, optional): if ``True``, ragged tensors will be returned as list.
                Exclusive with `as_padded_tensor` and `as_nested_tensor`.
                Defaults to ``False``.
            as_padded_tensor (bool, optional):  if ``True``, ragged tensors will be returned as padded tensors.
                The padding value can be controlled via the `padding_value` keyword argument, and the padding
                side via the `padding_side` argument.
                Exclusive with `as_list` and `as_nested_tensor`.
                Defaults to ``False``.
            as_nested_tensor (bool, optional): if ``True``, ragged tensors will be returned as list.
                Exclusive with `as_list` and `as_padded_tensor`.
                The layout can be controlled via the `torch.layout` argument.
                Defaults to ``False``.
            layout (torch.layout, optional): the layout when `as_nested_tensor=True`.
            padding_side (str): The side of padding. Must be `"left"` or `"right"`. Defaults to `"right"`.
            padding_value (scalar or bool, optional): The padding value. Defaults to 0.0.

        Examples:
            >>> from tensordict import TensorDict, lazy_stack
            >>> import torch
            >>> td = lazy_stack([
            ...     TensorDict({"x": torch.ones(1,)}),
            ...     TensorDict({"x": torch.ones(2,) * 2}),
            ... ])
            >>> td.get("x", as_nested_tensor=True)
            NestedTensor(size=(2, j1), offsets=tensor([0, 1, 3]), contiguous=True)
            >>> td.get("x", as_padded_tensor=True)
            tensor([[1., 0.],
                    [2., 2.]])

        """
        ...
    
    @classmethod
    def lazy_stack(cls, items: Sequence[TensorDictBase], dim: int = ..., *, device: DeviceType | None = ..., out: T | None = ..., stack_dim_name: str | None = ..., strict_shape: bool = ..., as_list: bool = ..., as_padded_tensor: bool = ..., as_nested_tensor: bool = ..., padding_side: str = ..., layout: torch.layout | None = ..., padding_value: float | int | bool = ...) -> Self:
        """Stacks tensordicts in a LazyStackedTensorDict.

        Args:
            items (Sequence of TensorDictBase instances): A sequence of TensorDictBase
                instances to stack.
            dim (int, optional): the dim along which to perform the lazy stack.
                Defaults to 0.

        Keyword Args:
            device (torch.device, optional): a device to set in the `LazyStackedTensorDict`
                in case it cannot be inferred from the tensordict list (e.g., the list is empty).
            out (TensorDictBase, optional): a `LazyStackedTensorDict` where to write the data.
            stack_dim_name (str, optional): a name for the stacked dimension.
            strict_shape (bool, optional): if ``True``, every tensordict's shapes must match.
                Defaults to ``False``.
            as_list (bool, optional): if ``True``, ragged tensors will be returned as list.
                Exclusive with `as_padded_tensor` and `as_nested_tensor`.
                Defaults to ``False``.
            as_padded_tensor (bool, optional):  if ``True``, ragged tensors will be returned as padded tensors.
                The padding value can be controlled via the `padding_value` keyword argument, and the padding
                side via the `padding_side` argument.
                Exclusive with `as_list` and `as_nested_tensor`.
                Defaults to ``False``.
            as_nested_tensor (bool, optional): if ``True``, ragged tensors will be returned as list.
                Exclusive with `as_list` and `as_padded_tensor`.
                The layout can be controlled via the `torch.layout` argument.
                Defaults to ``False``.
            layout (torch.layout, optional): the layout when `as_nested_tensor=True`.
            padding_side (str): The side of padding. Must be `"left"` or `"right"`. Defaults to `"right"`.
            padding_value (scalar or bool, optional): The padding value. Defaults to 0.0.

        """
        ...
    
    @classmethod
    def maybe_dense_stack(cls, items: Sequence[TensorDictBase], dim: int = ..., out: T | None = ..., strict: bool = ...) -> Self:
        """Stacks tensors or tensordicts densly if possible, or onto a LazyStackedTensorDict otherwise.

        Examples:
            >>> td0 = TensorDict({"a": 0}, [])
            >>> td1 = TensorDict({"b": 0}, [])
            >>> LazyStackedTensorDict.maybe_dense_stack([td0, td0])  # returns a TensorDict with shape [2]
            >>> LazyStackedTensorDict.maybe_dense_stack([td0, td1])  # returns a LazyStackedTensorDict with shape [2]
            >>> LazyStackedTensorDict.maybe_dense_stack(list(torch.randn(2)))  # returns a torch.Tensor with shape [2]
        """
        ...
    
    def get_nestedtensor(self, key: NestedKey, default: Any = ..., *, layout: torch.layout | None = ...) -> CompatibleType:
        """Returns a nested tensor when stacking cannot be achieved.

        Args:
            key (NestedKey): the entry to nest.
            default (Any, optiona): the default value to return in case the key
                isn't in all sub-tensordicts.

                .. note::
                    In case the default is a tensor, this method will attempt
                    the construction of a nestedtensor with it. Otherwise, the default
                    value will be returned.

        Keyword Args:
            layout (torch.layout, optional): the layout for the nested tensor.

        Examples:
            >>> td0 = TensorDict({"a": torch.zeros(4), "b": torch.zeros(4)}, [])
            >>> td1 = TensorDict({"a": torch.ones(5)}, [])
            >>> td = torch.stack([td0, td1], 0)
            >>> a = td.get_nestedtensor("a")
            >>> # using a tensor as default uses this default to build the nested tensor
            >>> b = td.get_nestedtensor("b", default=torch.ones(4))
            >>> assert (a == b).all()
            >>> # using anything else as default returns the default
            >>> b2 = td.get_nestedtensor("b", None)
            >>> assert b2 is None

        """
        ...
    
    def is_contiguous(self) -> bool:
        ...
    
    def contiguous(self) -> Self:
        ...
    
    def densify(self, *, layout: torch.layout = ...): # -> TensorDict:
        """Attempts to represent the lazy stack with contiguous tensors (plain tensors or nested).

        Keyword Args:
            layout (torch.layout): the layout of the nested tensors, if any. Defaults to
                :class:`~torch.strided`.

        """
        ...
    
    def empty(self, recurse=..., *, batch_size=..., device=..., names=...) -> Self:
        ...
    
    def to(self, *args, **kwargs) -> Self:
        ...
    
    def keys(self, include_nested: bool = ..., leaves_only: bool = ..., is_leaf: Callable[[Type], bool] | None = ..., *, sort: bool = ...) -> _LazyStackedTensorDictKeysView:
        ...
    
    def values(self, include_nested=..., leaves_only=..., is_leaf=..., *, sort: bool = ...): # -> Generator[CompatibleType, Any, None]:
        ...
    
    def items(self, include_nested=..., leaves_only=..., is_leaf=..., *, sort: bool = ...): # -> Generator[tuple[str, CompatibleType] | tuple[tuple[str, str] | tuple[str, *tuple[Any, ...]], CompatibleType], Any, None]:
        ...
    
    valid_keys = ...
    def non_tensor_items(self, include_nested: bool = ...): # -> tuple[tuple[str, Tensor], ...]:
        """Returns all non-tensor leaves, maybe recursively."""
        ...
    
    @lock_blocked
    def popitem(self) -> Tuple[NestedKey, CompatibleType]:
        ...
    
    def entry_class(self, key: NestedKey) -> type:
        ...
    
    def apply_(self, fn: Callable, *others, **kwargs): # -> Self:
        ...
    
    def __setitem__(self, index: IndexType, value: T) -> Self:
        ...
    
    def __contains__(self, item: IndexType) -> bool:
        ...
    
    def __getitem__(self, index: IndexType) -> Self | Tensor | TensorCollection | Any:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    def __or__(self, other): # -> Any | LazyStackedTensorDict:
        ...
    
    def __xor__(self, other): # -> Any | LazyStackedTensorDict:
        ...
    
    def __ge__(self, other) -> bool:
        ...
    
    def __gt__(self, other) -> bool:
        ...
    
    def __le__(self, other) -> bool:
        ...
    
    def __lt__(self, other) -> bool:
        ...
    
    def all(self, dim: int | None = ...) -> bool | TensorDictBase:
        ...
    
    def any(self, dim: int | None = ...) -> bool | TensorDictBase:
        ...
    
    @lock_blocked
    def del_(self, key: NestedKey, **kwargs: Any) -> Self:
        ...
    
    def pop(self, key: NestedKey, default: Any = ...) -> CompatibleType:
        ...
    
    def share_memory_(self) -> Self:
        ...
    
    def detach_(self) -> Self:
        ...
    
    def make_memmap(self, key: NestedKey, shape: torch.Size | torch.Tensor, *, dtype: torch.dtype | None = ...) -> MemoryMappedTensor:
        ...
    
    def make_memmap_from_storage(self, key: NestedKey, storage: torch.UntypedStorage, shape: torch.Size | torch.Tensor, *, dtype: torch.dtype | None = ...) -> MemoryMappedTensor:
        ...
    
    def make_memmap_from_tensor(self, key: NestedKey, tensor: torch.Tensor, *, copy_data: bool = ...) -> MemoryMappedTensor:
        ...
    
    def expand(self, *args: int, inplace: bool = ...) -> Self:
        ...
    
    @lock_blocked
    def update(self, input_dict_or_td: T, clone: bool = ..., *, keys_to_update: Sequence[NestedKey] | None = ..., non_blocking: bool = ..., is_leaf: Callable[[Type], bool] | None = ..., update_batch_size: bool = ..., **kwargs: Any) -> Self:
        ...
    
    def update_(self, input_dict_or_td: dict[str, CompatibleType] | TensorDictBase, clone: bool = ..., *, non_blocking: bool = ..., **kwargs: Any) -> Self:
        ...
    
    def update_at_(self, input_dict_or_td: dict[str, CompatibleType] | TensorDictBase, index: IndexType, clone: bool = ..., *, non_blocking: bool = ...) -> Self:
        ...
    
    def rename_key_(self, old_key: NestedKey, new_key: NestedKey, safe: bool = ...) -> Self:
        ...
    
    rename_key = ...
    def where(self, condition: Tensor, other: Tensor | TensorDictBase, *, out: TensorDictBase | None = ..., pad: int | bool = ..., update_batch_size: bool = ...): # -> TensorDictBase | Tensor:
        ...
    
    def masked_fill_(self, mask: Tensor, value: float | bool) -> Self:
        ...
    
    def masked_fill(self, mask: Tensor, value: float | bool) -> Self:
        ...
    
    @lock_blocked
    def insert(self, index: int, tensordict: T) -> None:
        """Insert a TensorDict into the stack at the specified index.

        Analogous to list.insert. The inserted TensorDict must have compatible
        batch_size and device. Insertion is in-place, nothing is returned.

        Args:
            index (int): The index at which the new TensorDict should be inserted.
            tensordict (TensorDictBase): The TensorDict to be inserted into the stack.

        """
        ...
    
    @lock_blocked
    def append(self, tensordict: T) -> None:
        """Append a TensorDict onto the stack.

        Analogous to list.append. The appended TensorDict must have compatible
        batch_size and device. The append operation is in-place, nothing is returned.

        Args:
            tensordict (TensorDictBase): The TensorDict to be appended onto the stack.

        """
        ...
    
    @lock_blocked
    def extend(self, tensordict: list[T] | T) -> None:
        """Extends the lazy stack with new tensordicts."""
        ...
    
    @property
    def is_locked(self) -> bool:
        ...
    
    @is_locked.setter
    def is_locked(self, value: bool) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def reshape(self, *args, **kwargs) -> Self:
        ...
    
    def flatten(self, start_dim: int = ..., end_dim=...):
        ...
    
    def unflatten(self, dim, unflattened_size):
        ...
    
    def repeat_interleave(self, repeats: torch.Tensor | int, dim: int | None = ..., *, output_size: int | None = ...) -> TensorDictBase:
        ...
    
    def split(self, split_size: int | list[int], dim: int = ...) -> list[TensorDictBase]:
        ...
    
    def chunk(self, chunks: int, dim: int = ...) -> tuple[TensorCollection, ...]:
        ...
    
    lock_ = ...
    lock = ...
    unlock_ = ...
    unlock = ...
    _check_device = ...
    _check_is_shared = ...
    _convert_to_tensordict = ...
    _index_tensordict = ...
    masked_select = ...
    _to_module = ...
    from_dict_instance = ...


class _CustomOpTensorDict(TensorDictBase):
    """Encodes lazy operations on tensors contained in a TensorDict."""
    _safe = ...
    _lazy = ...
    def __init__(self, source: T, custom_op: str, inv_op: str | None = ..., custom_op_kwargs: dict | None = ..., inv_op_kwargs: dict | None = ..., batch_size: Sequence[int] | None = ...) -> None:
        ...
    
    def is_empty(self) -> bool:
        ...
    
    def is_memmap(self) -> bool:
        ...
    
    def is_shared(self) -> bool:
        ...
    
    def entry_class(self, key: NestedKey) -> type:
        ...
    
    @classmethod
    def from_dict(cls, input_dict, batch_size=..., device=..., batch_dims=..., names=...):
        ...
    
    @property
    def device(self) -> torch.device | None:
        ...
    
    @device.setter
    def device(self, value: DeviceType) -> None:
        ...
    
    @property
    def batch_size(self) -> torch.Size:
        ...
    
    @batch_size.setter
    def batch_size(self, new_size: torch.Size) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def keys(self, include_nested: bool = ..., leaves_only: bool = ..., is_leaf: Callable[[Type], bool] | None = ..., *, sort: bool = ...) -> _TensorDictKeysView:
        ...
    
    def is_contiguous(self) -> bool:
        ...
    
    def contiguous(self) -> Self:
        ...
    
    def rename_key_(self, old_key: NestedKey, new_key: NestedKey, safe: bool = ...) -> _CustomOpTensorDict:
        ...
    
    rename_key = ...
    @lock_blocked
    def del_(self, key: NestedKey) -> _CustomOpTensorDict:
        ...
    
    def to(self, *args, **kwargs) -> Self:
        ...
    
    def pin_memory(self, *, num_threads: int | str = ..., inplace: bool = ...) -> _CustomOpTensorDict:
        ...
    
    @lock_blocked
    def popitem(self) -> Tuple[NestedKey, CompatibleType]:
        ...
    
    def detach_(self) -> _CustomOpTensorDict:
        ...
    
    def where(self, condition: Tensor, other: Tensor | TensorDictBase, *, out: TensorDictBase | None = ..., pad: int | bool = ..., update_batch_size: bool = ...):
        ...
    
    def masked_fill_(self, mask: Tensor, value: float | bool) -> _CustomOpTensorDict:
        ...
    
    def masked_fill(self, mask: Tensor, value: float | bool) -> Self:
        ...
    
    def make_memmap(self, key: NestedKey, shape: torch.Size | torch.Tensor, *, dtype: torch.dtype | None = ...) -> MemoryMappedTensor:
        ...
    
    def make_memmap_from_storage(self, key: NestedKey, storage: torch.UntypedStorage, shape: torch.Size | torch.Tensor, *, dtype: torch.dtype | None = ...) -> MemoryMappedTensor:
        ...
    
    def make_memmap_from_tensor(self, key: NestedKey, tensor: torch.Tensor, *, copy_data: bool = ...) -> MemoryMappedTensor:
        ...
    
    def share_memory_(self) -> _CustomOpTensorDict:
        ...
    
    @property
    def is_locked(self) -> bool:
        ...
    
    @is_locked.setter
    def is_locked(self, value) -> bool:
        ...
    
    @_as_context_manager("is_locked")
    def lock_(self) -> Self:
        ...
    
    @erase_cache
    @_as_context_manager("is_locked")
    def unlock_(self) -> Self:
        ...
    
    lock = ...
    unlock = ...
    def __del__(self): # -> None:
        ...
    
    @property
    def sorted_keys(self): # -> list[NestedKey]:
        ...
    
    def chunk(self, chunks: int, dim: int = ...) -> tuple[TensorDictBase, ...]:
        ...
    
    __xor__ = ...
    __or__ = ...
    __eq__ = ...
    __ne__ = ...
    __ge__ = ...
    __gt__ = ...
    __le__ = ...
    __lt__ = ...
    __setitem__ = ...
    _add_batch_dim = ...
    _check_device = ...
    _check_is_shared = ...
    _convert_to_tensordict = ...
    _index_tensordict = ...
    _apply_nest = ...
    _get_names_idx = ...
    _maybe_remove_batch_dim = ...
    _multithread_apply_flat = ...
    _multithread_rebuild = ...
    _remove_batch_dim = ...
    _to_module = ...
    _unbind = ...
    all = ...
    any = ...
    expand = ...
    from_dict_instance = ...
    masked_select = ...
    _repeat = ...
    repeat_interleave = ...
    reshape = ...
    split = ...


class _UnsqueezedTensorDict(_CustomOpTensorDict):
    """A lazy view on an unsqueezed TensorDict.

    When calling `tensordict.unsqueeze(dim)`, a lazy view of this operation is
    returned such that the following code snippet works without raising an
    exception:

        >>> assert tensordict.unsqueeze(dim).squeeze(dim) is tensordict

    Examples:
        >>> from tensordict import TensorDict
        >>> import torch
        >>> td = TensorDict({'a': torch.randn(3, 4)}, batch_size=[3])
        >>> td_unsqueeze = td.unsqueeze(-1)
        >>> print(td_unsqueeze.shape)
        torch.Size([3, 1])
        >>> print(td_unsqueeze.squeeze(-1) is td)
        True
    """
    @property
    def names(self):
        ...
    
    @names.setter
    def names(self, value): # -> None:
        ...
    


class _SqueezedTensorDict(_CustomOpTensorDict):
    """A lazy view on a squeezed TensorDict.

    See the `UnsqueezedTensorDict` class documentation for more information.

    """
    @property
    def names(self):
        ...
    
    @names.setter
    def names(self, value): # -> None:
        ...
    


class _ViewedTensorDict(_CustomOpTensorDict):
    @property
    def names(self): # -> list[None]:
        ...
    
    @names.setter
    def names(self, value):
        ...
    


class _TransposedTensorDict(_CustomOpTensorDict):
    """A lazy view on a TensorDict with two batch dimensions transposed.

    When calling `tensordict.permute(dims_list, dim)`, a lazy view of this operation is
    returned such that the following code snippet works without raising an
    exception:

        >>> assert tensordict.transpose(dims_list, dim).transpose(dims_list, dim) is tensordict

    """
    def add_missing_dims(self, num_dims: int, batch_dims: tuple[int, ...]) -> tuple[int, ...]:
        ...
    
    @property
    def names(self): # -> list[Any]:
        ...
    
    @names.setter
    def names(self, value):
        ...
    


class _PermutedTensorDict(_CustomOpTensorDict):
    """A lazy view on a TensorDict with the batch dimensions permuted.

    When calling `tensordict.permute(dims_list, dim)`, a lazy view of this operation is
    returned such that the following code snippet works without raising an
    exception:

        >>> assert tensordict.permute(dims_list, dim).permute(dims_list, dim) is tensordict

    Examples:
        >>> from tensordict import TensorDict
        >>> import torch
        >>> td = TensorDict({'a': torch.randn(4, 5, 6, 9)}, batch_size=[3])
        >>> td_permute = td.permute(dims=(2, 1, 0))
        >>> print(td_permute.shape)
        torch.Size([6, 5, 4])
        >>> print(td_permute.permute(dims=(2, 1, 0)) is td)
        True

    """
    def add_missing_dims(self, num_dims: int, batch_dims: tuple[int, ...]) -> tuple[int, ...]:
        ...
    
    @property
    def names(self): # -> list[Any]:
        ...
    
    @names.setter
    def names(self, value): # -> None:
        ...
    


