"""
This type stub file was generated by pyright.
"""

import torch
from pathlib import Path
from typing import Any, Callable, Iterator, List, Self, Sequence, TYPE_CHECKING, Tuple, Type
from tensordict._nestedkey import NestedKey
from tensordict._tensorcollection import TensorCollection
from tensordict.base import CompatibleType, T, TensorDictBase, _maybe_broadcast_other
from tensordict.memmap import MemoryMappedTensor
from tensordict.utils import DeviceType, IndexType, _as_context_manager, _is_shared, lock_blocked
from torch import Tensor, nn
from torch._C._functorch import _add_batch_dim

_has_funcdim = ...
if TYPE_CHECKING:
    ...
else:
    ...
__base__setattr__ = ...
_has_functorch = ...
_has_functorch = ...
class TensorDict(TensorDictBase):
    """A batched dictionary of tensors.

    TensorDict is a tensor container where all tensors are stored in a
    key-value pair fashion and where each element shares the same first ``N``
    leading dimensions shape, where is an arbitrary number with ``N >= 0``.

    Additionally, if the tensordict has a specified device, then each element
    must share that device.

    TensorDict instances support many regular tensor operations with the notable
    exception of algebraic operations:

    - operations on shape: when a shape operation is called (indexing,
      reshape, view, expand, transpose, permute,
      unsqueeze, squeeze, masking etc), the operations is done as if it
      was executed on a tensor of the same shape as the batch size then
      expended to the right, e.g.:

        >>> td = TensorDict({'a': torch.zeros(3, 4, 5)}, batch_size=[3, 4])
        >>> # returns a TensorDict of batch size [3, 4, 1]:
        >>> td_unsqueeze = td.unsqueeze(-1)
        >>> # returns a TensorDict of batch size [12]
        >>> td_view = td.view(-1)
        >>> # returns a tensor of batch size [12, 4]
        >>> a_view = td.view(-1).get("a")

    - casting operations: a TensorDict can be cast on a different device using

        >>> td_cpu = td.to("cpu")
        >>> dictionary = td.to_dict()

      A call of the `.to()` method with a dtype will return an error.

    - Cloning (:meth:`~TensorDictBase.clone`), contiguous (:meth:`~TensorDictBase.contiguous`);

    - Reading: `td.get(key)`, `td.get_at(key, index)`

    - Content modification: :obj:`td.set(key, value)`, :obj:`td.set_(key, value)`,
      :obj:`td.update(td_or_dict)`, :obj:`td.update_(td_or_dict)`, :obj:`td.fill_(key,
      value)`, :obj:`td.rename_key_(old_name, new_name)`, etc.

    - Operations on multiple tensordicts: `torch.cat(tensordict_list, dim)`,
      `torch.stack(tensordict_list, dim)`, `td1 == td2`, `td.apply(lambda x+y, other_td)` etc.

    Args:
        source (TensorDict or Dict[NestedKey, Union[Tensor, TensorDictBase]]): a
            data source. If empty, the tensordict can be populated subsequently.
            A ``TensorDict`` can also be built via a sequence of keyword arguments,
            as it is the case for ``dict(...)``.
        batch_size (iterable of int, optional): a batch size for the
            tensordict. The batch size can be modified subsequently as long
            as it is compatible with its content.
            If not batch-size is provided, an empty batch-size is assumed (it
            is not inferred automatically from the data). To automatically set
            the batch-size, refer to :meth:`~.auto_batch_size_`.
        device (torch.device or compatible type, optional): a device for the
            TensorDict. If provided, all tensors will be stored on that device.
            If not, tensors on different devices are allowed.
        names (lsit of str, optional): the names of the dimensions of the
            tensordict. If provided, its length must match the one of the
            ``batch_size``. Defaults to ``None`` (no dimension name, or ``None``
            for every dimension).
        non_blocking (bool, optional): if ``True`` and a device is passed, the tensordict
            is delivered without synchronization. This is the fastest option but is only
            safe when casting from cpu to cuda (otherwise a synchronization call must be
            implemented by the user).
            If ``False`` is passed, every tensor movement will be done synchronously.
            If ``None`` (default), the device casting will be done asynchronously but
            a synchronization will be executed after creation if required. This option
            should generally be faster than ``False`` and potentially slower than ``True``.
        lock (bool, optional): if ``True``, the resulting tensordict will be
            locked.

    Examples:
        >>> import torch
        >>> from tensordict import TensorDict
        >>> source = {'random': torch.randn(3, 4),
        ...     'zeros': torch.zeros(3, 4, 5)}
        >>> batch_size = [3]
        >>> td = TensorDict(source, batch_size=batch_size)
        >>> print(td.shape)  # equivalent to td.batch_size
        torch.Size([3])
        >>> td_unqueeze = td.unsqueeze(-1)
        >>> print(td_unqueeze.get("zeros").shape)
        torch.Size([3, 1, 4, 5])
        >>> print(td_unqueeze[0].shape)
        torch.Size([1])
        >>> print(td_unqueeze.view(-1).shape)
        torch.Size([3])
        >>> print((td.clone()==td).all())
        True

    """
    _td_dim_names = ...
    _is_shared = ...
    _is_memmap = ...
    _has_exclusive_keys = ...
    def __init__(self, source: T | dict[NestedKey, CompatibleType] | None = ..., batch_size: Sequence[int] | torch.Size | int | None = ..., device: DeviceType | None = ..., names: Sequence[str] | None = ..., non_blocking: bool | None = ..., lock: bool = ..., **kwargs: Any) -> None:
        ...
    
    @classmethod
    def from_module(cls, module: torch.nn.Module, as_module: bool = ..., lock: bool = ..., use_state_dict: bool = ..., filter_empty: bool = ...): # -> TensorDict | TensorDictParams | dict[Any, Any]:
        ...
    
    def is_empty(self): # -> bool:
        ...
    
    @_maybe_broadcast_other("__ne__")
    def __ne__(self, other: Any) -> Self | bool:
        ...
    
    @_maybe_broadcast_other("__xor__")
    def __xor__(self, other: Any) -> Self | bool:
        ...
    
    @_maybe_broadcast_other("__or__")
    def __or__(self, other: Any) -> Self | bool:
        ...
    
    @_maybe_broadcast_other("__eq__")
    def __eq__(self, other: Any) -> Self | bool:
        ...
    
    @_maybe_broadcast_other("__ge__")
    def __ge__(self, other: Any) -> Self | bool:
        ...
    
    @_maybe_broadcast_other("__gt__")
    def __gt__(self, other: Any) -> Self | bool:
        ...
    
    @_maybe_broadcast_other("__le__")
    def __le__(self, other: Any) -> Self | bool:
        ...
    
    @_maybe_broadcast_other("__lt__")
    def __lt__(self, other: Any) -> Self | bool:
        ...
    
    def __setitem__(self, index: IndexType, value: Any) -> None:
        ...
    
    def all(self, dim: int | None = ...) -> bool | TensorCollection:
        ...
    
    def any(self, dim: int | None = ...) -> bool | TensorCollection:
        ...
    
    def expand(self, *args, **kwargs) -> Self:
        ...
    
    def split(self, split_size: int | list[int], dim: int = ...) -> tuple[TensorDictBase, ...]:
        ...
    
    def chunk(self, chunks: int, dim: int = ...) -> tuple[TensorCollection, ...]:
        ...
    
    def masked_select(self, mask: Tensor) -> Self:
        ...
    
    def reshape(self, *args, **kwargs) -> Self:
        ...
    
    def repeat_interleave(self, repeats: torch.Tensor | int, dim: int | None = ..., *, output_size: int | None = ...) -> Self:
        ...
    
    @classmethod
    def from_dict(cls, input_dict: dict[NestedKey, CompatibleType] | TensorDictBase, *, auto_batch_size: bool | None = ..., batch_size: Sequence[int] | torch.Size | None = ..., device: torch.device | None = ..., batch_dims: int | None = ..., names: Sequence[str] | None = ...) -> Self:
        ...
    
    def from_dict_instance(self, input_dict, *, auto_batch_size: bool | None = ..., batch_size=..., device=..., batch_dims=..., names=...): # -> TensorDict:
        ...
    
    @property
    def batch_dims(self) -> int:
        ...
    
    @batch_dims.setter
    def batch_dims(self, value: int) -> None:
        ...
    
    @property
    def names(self): # -> list[None] | list[Any]:
        ...
    
    @names.setter
    def names(self, value): # -> None:
        ...
    
    @property
    def device(self) -> torch.device | None:
        """Device of the tensordict.

        Returns `None` if device hasn't been provided in the constructor or set via `tensordict.to(device)`.

        """
        ...
    
    @device.setter
    def device(self, value: DeviceType) -> None:
        ...
    
    @property
    def batch_size(self) -> torch.Size:
        ...
    
    @batch_size.setter
    def batch_size(self, new_size: torch.Size) -> None:
        ...
    
    @lock_blocked
    def popitem(self) -> Tuple[NestedKey, CompatibleType]:
        ...
    
    _SHARED_INPLACE_ERROR = ...
    @lock_blocked
    def del_(self, key: NestedKey) -> Self:
        ...
    
    @lock_blocked
    def rename_key_(self, old_key: NestedKey, new_key: NestedKey, safe: bool = ...) -> Self:
        ...
    
    def entry_class(self, key: NestedKey) -> type:
        ...
    
    def share_memory_(self) -> Self:
        ...
    
    def detach_(self) -> Self:
        ...
    
    def make_memmap(self, key: NestedKey, shape: torch.Size | torch.Tensor, *, dtype: torch.dtype | None = ...) -> MemoryMappedTensor:
        ...
    
    def make_memmap_from_storage(self, key: NestedKey, storage: torch.UntypedStorage, shape: torch.Size | torch.Tensor, *, dtype: torch.dtype | None = ...) -> MemoryMappedTensor:
        ...
    
    def make_memmap_from_tensor(self, key: NestedKey, tensor: torch.Tensor, *, copy_data: bool = ..., existsok: bool = ...) -> MemoryMappedTensor:
        ...
    
    def where(self, condition: Tensor, other: Tensor | TensorCollection, *, out: TensorCollection | None = ..., pad: int | bool = ..., update_batch_size: bool = ...) -> Self:
        ...
    
    def masked_fill_(self, mask: Tensor, value: float | int | bool) -> Self:
        ...
    
    def masked_fill(self, mask: Tensor, value: float | bool) -> Self:
        ...
    
    def is_contiguous(self) -> bool:
        ...
    
    def contiguous(self) -> Self:
        ...
    
    def empty(self, recurse=..., *, batch_size=..., device=..., names=...) -> Self:
        ...
    
    def keys(self, include_nested: bool = ..., leaves_only: bool = ..., is_leaf: Callable[[Type], bool] | None = ..., *, sort: bool = ...) -> _TensorDictKeysView:
        ...
    
    def items(self, include_nested: bool = ..., leaves_only: bool = ..., is_leaf: Callable[[Type], bool] | None = ..., *, sort: bool = ...) -> Iterator[tuple[str, CompatibleType]]:
        ...
    
    def values(self, include_nested: bool = ..., leaves_only: bool = ..., is_leaf: Callable[[Type], bool] | None = ..., *, sort: bool = ...) -> Iterator[tuple[str, CompatibleType]]:
        ...
    


class _SubTensorDict(TensorDictBase):
    """A TensorDict that only sees an index of the stored tensors."""
    _lazy = ...
    _inplace_set = ...
    _safe = ...
    def __init__(self, source: T, idx: IndexType, batch_size: Sequence[int] | None = ...) -> None:
        ...
    
    @property
    def batch_size(self) -> torch.Size:
        ...
    
    @batch_size.setter
    def batch_size(self, new_size: torch.Size) -> None:
        ...
    
    @property
    def names(self): # -> list[None]:
        ...
    
    @names.setter
    def names(self, value):
        ...
    
    @property
    def device(self) -> None | torch.device:
        ...
    
    @device.setter
    def device(self, value: DeviceType) -> None:
        ...
    
    from_dict_instance = ...
    def keys(self, include_nested: bool = ..., leaves_only: bool = ..., is_leaf: Callable[[Type], bool] | None = ..., *, sort: bool = ...) -> _TensorDictKeysView:
        ...
    
    def entry_class(self, key: NestedKey) -> type:
        ...
    
    def to(self, *args, **kwargs: Any) -> Self:
        ...
    
    @lock_blocked
    def update(self, input_dict_or_td: dict[str, CompatibleType] | TensorCollection, clone: bool = ..., inplace: bool = ..., *, non_blocking: bool = ..., keys_to_update: Sequence[NestedKey] | None = ..., is_leaf: Callable[[Type], bool] | None = ..., update_batch_size: bool = ..., ignore_lock: bool = ..., **kwargs) -> _SubTensorDict:
        ...
    
    def update_(self, input_dict: dict[str, CompatibleType] | TensorCollection, clone: bool = ..., *, non_blocking: bool = ..., keys_to_update: Sequence[NestedKey] | None = ...) -> _SubTensorDict:
        ...
    
    def update_at_(self, input_dict: dict[str, CompatibleType] | TensorCollection, idx: IndexType, *, discard_idx_attr: bool = ..., clone: bool = ..., non_blocking: bool = ..., keys_to_update: Sequence[NestedKey] | None = ...) -> _SubTensorDict:
        ...
    
    def get_parent_tensordict(self) -> Self:
        ...
    
    @lock_blocked
    def del_(self, key: NestedKey) -> Self:
        ...
    
    @lock_blocked
    def popitem(self) -> Tuple[NestedKey, CompatibleType]:
        ...
    
    def is_contiguous(self) -> bool:
        ...
    
    def contiguous(self) -> Self:
        ...
    
    def expand(self, *args: int, inplace: bool = ...) -> Self:
        ...
    
    @classmethod
    def from_dict(cls, input_dict, *others, auto_batch_size: bool = ..., batch_size=..., device=..., batch_dims=..., names=...):
        ...
    
    def is_shared(self) -> bool:
        ...
    
    def is_memmap(self) -> bool:
        ...
    
    def rename_key_(self, old_key: NestedKey, new_key: NestedKey, safe: bool = ...) -> _SubTensorDict:
        ...
    
    def pin_memory(self, *args, **kwargs) -> Self:
        ...
    
    def detach_(self) -> Self:
        ...
    
    def where(self, condition: Tensor, other: Tensor | TensorDictBase, *, out: TensorDictBase | None = ..., pad: int | bool = ..., update_batch_size: bool = ...):
        ...
    
    def masked_fill_(self, mask: Tensor, value: float | bool) -> Self:
        ...
    
    def masked_fill(self, mask: Tensor, value: float | bool) -> Self:
        ...
    
    def memmap_(self, prefix: str | None = ..., copy_existing: bool = ..., num_threads: int = ...) -> Self:
        ...
    
    def make_memmap(self, key: NestedKey, shape: torch.Size | torch.Tensor, *, dtype: torch.dtype | None = ...) -> MemoryMappedTensor:
        ...
    
    def make_memmap_from_storage(self, key: NestedKey, storage: torch.UntypedStorage, shape: torch.Size | torch.Tensor, *, dtype: torch.dtype | None = ...) -> MemoryMappedTensor:
        ...
    
    def make_memmap_from_tensor(self, key: NestedKey, tensor: torch.Tensor, *, copy_data: bool = ...) -> MemoryMappedTensor:
        ...
    
    def share_memory_(self) -> Self:
        ...
    
    @property
    def is_locked(self) -> bool:
        ...
    
    @is_locked.setter
    def is_locked(self, value) -> bool:
        ...
    
    @_as_context_manager("is_locked")
    def lock_(self) -> Self:
        ...
    
    @_as_context_manager("is_locked")
    def unlock_(self) -> Self:
        ...
    
    def __del__(self): # -> None:
        ...
    
    __eq__ = ...
    __ne__ = ...
    __ge__ = ...
    __gt__ = ...
    __le__ = ...
    __lt__ = ...
    __setitem__ = ...
    __xor__ = ...
    __or__ = ...
    _check_device = ...
    _check_is_shared = ...
    _to_module = ...
    _unbind = ...
    all = ...
    any = ...
    masked_select = ...
    memmap_like = ...
    repeat_interleave = ...
    _repeat = ...
    reshape = ...
    split = ...
    def chunk(self, chunks: int, dim: int = ...) -> tuple[TensorCollection, ...]:
        ...
    
    _add_batch_dim = ...
    _apply_nest = ...
    _multithread_apply_flat = ...
    _multithread_rebuild = ...
    _convert_to_tensordict = ...
    _get_names_idx = ...


class _TensorDictKeysView:
    """A Key view for TensorDictBase instance.

    _TensorDictKeysView is returned when accessing tensordict.keys() and holds a
    reference to the original TensorDict. This class enables us to support nested keys
    when performing membership checks and when iterating over keys.

    Examples:
        >>> import torch
        >>> from tensordict import TensorDict

        >>> td = TensorDict(
        >>>     {"a": TensorDict({"b": torch.rand(1, 2)}, [1, 2]), "c": torch.rand(1)},
        >>>     [1],
        >>> )

        >>> assert "a" in td.keys()
        >>> assert ("a",) in td.keys()
        >>> assert ("a", "b") in td.keys()
        >>> assert ("a", "c") not in td.keys()

        >>> assert set(td.keys()) == {("a", "b"), "c"}
    """
    def __init__(self, tensordict: T, include_nested: bool, leaves_only: bool, is_leaf: Callable[[Type], bool] | None = ..., sort: bool = ...) -> None:
        ...
    
    def __iter__(self) -> Iterator[str | tuple[str, ...]]:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __contains__(self, key: NestedKey) -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    


def from_module(module, as_module: bool = ..., lock: bool = ..., use_state_dict: bool = ...): # -> TensorDict | TensorDictParams | dict[Any, Any]:
    """Copies the params and buffers of a module in a tensordict.

    Args:
        module (nn.Module): the module to get the parameters from.
        as_module (bool, optional): if ``True``, a :class:`~tensordict.nn.TensorDictParams`
            instance will be returned which can be used to store parameters
            within a :class:`torch.nn.Module`. Defaults to ``False``.
        lock (bool, optional): if ``True``, the resulting tensordict will be locked.
            Defaults to ``True``.
        use_state_dict (bool, optional): if ``True``, the state-dict from the
            module will be used and unflattened into a TensorDict with
            the tree structure of the model. Defaults to ``False``.

            .. note::
                This is particularly useful when state-dict hooks have to be used.

    Examples:
        >>> from torch import nn
        >>> module = nn.TransformerDecoder(
        ...     decoder_layer=nn.TransformerDecoderLayer(nhead=4, d_model=4),
        ...     num_layers=1)
        >>> params = from_module(module)
        >>> print(params["layers", "0", "linear1"])
        TensorDict(
            fields={
                bias: Parameter(shape=torch.Size([2048]), device=cpu, dtype=torch.float32, is_shared=False),
                weight: Parameter(shape=torch.Size([2048, 4]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([]),
            device=None,
            is_shared=False)
    """
    ...

def from_modules(*modules, as_module: bool = ..., lock: bool = ..., use_state_dict: bool = ..., lazy_stack: bool = ..., expand_identical: bool = ...): # -> TensorDictParams | LazyStackedTensorDict:
    """Retrieves the parameters of several modules for ensebmle learning/feature of expects applications through vmap.

    Args:
        modules (sequence of nn.Module): the modules to get the parameters from.
            If the modules differ in their structure, a lazy stack is needed
            (see the ``lazy_stack`` argument below).

    Keyword Args:
        as_module (bool, optional): if ``True``, a :class:`~tensordict.nn.TensorDictParams`
            instance will be returned which can be used to store parameters
            within a :class:`torch.nn.Module`. Defaults to ``False``.
        lock (bool, optional): if ``True``, the resulting tensordict will be locked.
            Defaults to ``True``.
        use_state_dict (bool, optional): if ``True``, the state-dict from the
            module will be used and unflattened into a TensorDict with
            the tree structure of the model. Defaults to ``False``.

            .. note::
                This is particularly useful when state-dict hooks have to be used.

        lazy_stack (bool, optional): whether parameters should be densly or
            lazily stacked. Defaults to ``False`` (dense stack).

            .. note::
                ``lazy_stack`` and ``as_module`` are exclusive features.

            .. warning::
                There is a crucial difference between lazy and non-lazy outputs
                in that non-lazy output will reinstantiate parameters with the
                desired batch-size, while ``lazy_stack`` will just represent
                the parameters as lazily stacked. This means that whilst the
                original parameters can safely be passed to an optimizer
                when ``lazy_stack=True``, the new parameters need to be passed
                when it is set to ``True``.

            .. warning::
                Whilst it can be tempting to use a lazy stack to keep the
                orignal parameter references, remember that lazy stack
                perform a stack each time :meth:`~.get` is called. This will
                require memory (N times the size of the parameters, more if a
                graph is built) and time to be computed.
                It also means that the optimizer(s) will contain more
                parameters, and operations like :meth:`~torch.optim.Optimizer.step`
                or :meth:`~torch.optim.Optimizer.zero_grad` will take longer
                to be executed. In general, ``lazy_stack`` should be reserved
                to very few use cases.

        expand_identical (bool, optional): if ``True`` and the same parameter (same
            identity) is being stacked to itself, an expanded version of this parameter
            will be returned instead. This argument is ignored when ``lazy_stack=True``.

    Examples:
        >>> from torch import nn
        >>> from tensordict import from_modules
        >>> torch.manual_seed(0)
        >>> empty_module = nn.Linear(3, 4, device="meta")
        >>> n_models = 2
        >>> modules = [nn.Linear(3, 4) for _ in range(n_models)]
        >>> params = from_modules(*modules)
        >>> print(params)
        TensorDict(
            fields={
                bias: Parameter(shape=torch.Size([2, 4]), device=cpu, dtype=torch.float32, is_shared=False),
                weight: Parameter(shape=torch.Size([2, 4, 3]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([2]),
            device=None,
            is_shared=False)
        >>> # example of batch execution
        >>> def exec_module(params, x):
        ...     with params.to_module(empty_module):
        ...         return empty_module(x)
        >>> x = torch.randn(3)
        >>> y = torch.vmap(exec_module, (0, None))(params, x)
        >>> assert y.shape == (n_models, 4)
        >>> # since lazy_stack = False, backprop leaves the original params untouched
        >>> y.sum().backward()
        >>> assert params["weight"].grad.norm() > 0
        >>> assert modules[0].weight.grad is None

    With ``lazy_stack=True``, things are slightly different:

        >>> params = TensorDict.from_modules(*modules, lazy_stack=True)
        >>> print(params)
        LazyStackedTensorDict(
            fields={
                bias: Tensor(shape=torch.Size([2, 4]), device=cpu, dtype=torch.float32, is_shared=False),
                weight: Tensor(shape=torch.Size([2, 4, 3]), device=cpu, dtype=torch.float32, is_shared=False)},
            exclusive_fields={
            },
            batch_size=torch.Size([2]),
            device=None,
            is_shared=False,
            stack_dim=0)
        >>> # example of batch execution
        >>> y = torch.vmap(exec_module, (0, None))(params, x)
        >>> assert y.shape == (n_models, 4)
        >>> y.sum().backward()
        >>> assert modules[0].weight.grad is not None


    """
    ...

def from_pytree(pytree, *, batch_size: torch.Size | None = ..., auto_batch_size: bool = ..., batch_dims: int | None = ...):
    """Converts a pytree to a TensorDict instance.

    This method is designed to keep the pytree nested structure as much as possible.

    Additional non-tensor keys are added to keep track of each level's identity, providing
    a built-in pytree-to-tensordict bijective transform API.

    Accepted classes currently include lists, tuples, named tuples and dict.

    .. note::
        For dictionaries, non-NestedKey keys are registered separately as :class:`~tensordict.NonTensorData`
        instances.

    .. note::
        Tensor-castable types (such as int, float or np.ndarray) will be converted to torch.Tensor instances.
        Note that this transformation is surjective: transforming back the tensordict to a pytree will not
        recover the original types.

    Examples:
        >>> # Create a pytree with tensor leaves, and one "weird"-looking dict key
        >>> class WeirdLookingClass:
        ...     pass
        ...
        >>> weird_key = WeirdLookingClass()
        >>> # Make a pytree with tuple, lists, dict and namedtuple
        >>> pytree = (
        ...     [torch.randint(10, (3,)), torch.zeros(2)],
        ...     {
        ...         "tensor": torch.randn(
        ...             2,
        ...         ),
        ...         "td": TensorDict({"one": 1}),
        ...         weird_key: torch.randint(10, (2,)),
        ...         "list": [1, 2, 3],
        ...     },
        ...     {"named_tuple": TensorDict({"two": torch.ones(1) * 2}).to_namedtuple()},
        ... )
        >>> # Build a TensorDict from that pytree
        >>> td = from_pytree(pytree)
        >>> # Recover the pytree
        >>> pytree_recon = td.to_pytree()
        >>> # Check that the leaves match
        >>> def check(v1, v2):
        >>>     assert (v1 == v2).all()
        >>>
        >>> torch.utils._pytree.tree_map(check, pytree, pytree_recon)
        >>> assert weird_key in pytree_recon[1]

    """
    ...

def stack(input: Sequence[T], dim: int = ..., *, out=...) -> T:
    """Stacks tensordicts into a single tensordict along the given dimension.

    This call is equivalent to calling :func:`torch.stack` but is compatible with torch.compile.

    """
    ...

def lazy_stack(input: Sequence[T], dim: int = ..., *, out=...) -> T:
    """Creates a lazy stack of tensordicts.

    See :meth:`~tensordict.LazyStackTensorDict.lazy_stack` for details.
    """
    ...

def cat(input: Sequence[T], dim: int = ..., *, out=...) -> T:
    """Concatenates tensordicts into a single tensordict along the given dimension.

    This call is equivalent to calling :func:`torch.cat` but is compatible with torch.compile.

    """
    ...

def maybe_dense_stack(input: Sequence[T], dim: int = ..., *, out=..., **kwargs) -> T:
    """Attempts to make a dense stack of tensordicts, and falls back on lazy stack when required..

    See :meth:`~tensordict.LazyStackTensorDict.maybe_dense_stack` for details.
    """
    ...

def fromkeys(keys: List[NestedKey], value: Any = ...): # -> TensorDict:
    """Creates a tensordict from a list of keys and a single value.

    Args:
        keys (list of NestedKey): An iterable specifying the keys of the new dictionary.
        value (compatible type, optional): The value for all keys. Defaults to ``0``.
    """
    ...

def from_consolidated(filename):
    """Reconstructs a tensordict from a consolidated file."""
    ...

def load(prefix: str | Path, device: torch.device | None = ..., non_blocking: bool = ..., *, out: TensorCollection | None = ...) -> Self:
    """Loads a tensordict from disk.

    This class method is a proxy to :meth:`~.load_memmap`.
    """
    ...

def load_memmap(prefix: str | Path, device: torch.device | None = ..., non_blocking: bool = ..., *, out: TensorCollection | None = ...) -> Self:
    """Loads a memory-mapped tensordict from disk.

    Args:
        prefix (str or Path to folder): the path to the folder where the
            saved tensordict should be fetched.
        device (torch.device or equivalent, optional): if provided, the
            data will be asynchronously cast to that device.
            Supports `"meta"` device, in which case the data isn't loaded
            but a set of empty "meta" tensors are created. This is
            useful to get a sense of the total model size and structure
            without actually opening any file.
        non_blocking (bool, optional): if ``True``, synchronize won't be
            called after loading tensors on device. Defaults to ``False``.
        out (TensorDictBase, optional): optional tensordict where the data
            should be written.

    Examples:
        >>> from tensordict import TensorDict, load_memmap
        >>> td = TensorDict.fromkeys(["a", "b", "c", ("nested", "e")], 0)
        >>> td.memmap("./saved_td")
        >>> td_load = TensorDict.load_memmap("./saved_td")
        >>> assert (td == td_load).all()

    This method also allows loading nested tensordicts.

    Examples:
        >>> nested = TensorDict.load_memmap("./saved_td/nested")
        >>> assert nested["e"] == 0

    A tensordict can also be loaded on "meta" device or, alternatively,
    as a fake tensor.

    Examples:
        >>> import tempfile
        >>> td = TensorDict({"a": torch.zeros(()), "b": {"c": torch.zeros(())}})
        >>> with tempfile.TemporaryDirectory() as path:
        ...     td.save(path)
        ...     td_load = load_memmap(path, device="meta")
        ...     print("meta:", td_load)
        ...     from torch._subclasses import FakeTensorMode
        ...     with FakeTensorMode():
        ...         td_load = load_memmap(path)
        ...         print("fake:", td_load)
        meta: TensorDict(
            fields={
                a: Tensor(shape=torch.Size([]), device=meta, dtype=torch.float32, is_shared=False),
                b: TensorDict(
                    fields={
                        c: Tensor(shape=torch.Size([]), device=meta, dtype=torch.float32, is_shared=False)},
                    batch_size=torch.Size([]),
                    device=meta,
                    is_shared=False)},
            batch_size=torch.Size([]),
            device=meta,
            is_shared=False)
        fake: TensorDict(
            fields={
                a: FakeTensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False),
                b: TensorDict(
                    fields={
                        c: FakeTensor(shape=torch.Size([]), device=cpu, dtype=torch.float32, is_shared=False)},
                    batch_size=torch.Size([]),
                    device=cpu,
                    is_shared=False)},
            batch_size=torch.Size([]),
            device=cpu,
            is_shared=False)

    """
    ...

def save(data: TensorCollection, prefix: str | None = ..., copy_existing: bool = ..., *, num_threads: int = ..., return_early: bool = ..., share_non_tensor: bool = ...) -> None:
    """Saves the tensordict to disk.

    This function is a proxy to :meth:`~.memmap`.
    """
    ...

def memmap(data: TensorCollection, prefix: str | None = ..., copy_existing: bool = ..., *, num_threads: int = ..., return_early: bool = ..., share_non_tensor: bool = ...) -> Self:
    """Writes all tensors onto a corresponding memory-mapped Tensor in a new tensordict.

    Args:
        data (TensorDictBase): a data structure to save.
        prefix (str): directory prefix where the memory-mapped tensors will
            be stored. The directory tree structure will mimic the tensordict's.
        copy_existing (bool): If False (default), an exception will be raised if an
            entry in the tensordict is already a tensor stored on disk
            with an associated file, but is not saved in the correct
            location according to prefix.
            If ``True``, any existing Tensor will be copied to the new location.

    Keyword Args:
        num_threads (int, optional): the number of threads used to write the memmap
            tensors. Defaults to `0`.
        return_early (bool, optional): if ``True`` and ``num_threads>0``,
            the method will return a future of the tensordict.
        share_non_tensor (bool, optional): if ``True``, the non-tensor data will be
            shared between the processes and writing operation (such as inplace update
            or set) on any of the workers within a single node will update the value
            on all other workers. If the number of non-tensor leaves is high (e.g.,
            sharing large stacks of non-tensor data) this may result in OOM or similar
            errors. Defaults to ``False``.

    The TensorDict is then locked, meaning that any writing operations that
    isn't in-place will throw an exception (eg, rename, set or remove an
    entry).
    Once the tensordict is unlocked, the memory-mapped attribute is turned to ``False``,
    because cross-process identity is not guaranteed anymore.

    Returns:
        A new tensordict with the tensors stored on disk if ``return_early=False``,
        otherwise a :class:`~tensordict.utils.TensorDictFuture` instance.

    Note:
        Serialising in this fashion might be slow with deeply nested tensordicts, so
        it is not recommended to call this method inside a training loop.
    """
    ...

