"""
This type stub file was generated by pyright.
"""

import torch
from typing import Callable, TypeVar
from tensordict.base import TensorDictBase

TD_HANDLED_FUNCTIONS: dict[Callable, Callable] = ...
LAZY_TD_HANDLED_FUNCTIONS: dict[Callable, Callable] = ...
T = TypeVar("T", bound="TensorDictBase")
def implements_for_td(torch_function: Callable) -> Callable[[Callable], Callable]:
    """Register a torch function override for TensorDict."""
    ...

def implements_for_lazy_td(torch_function: Callable) -> Callable[[Callable], Callable]:
    """Register a torch function override for TensorDict."""
    ...

@implements_for_td(torch.where)
def where(condition, input, other, *, out=...):
    """Return a ``TensorDict`` of elements selected from either input or other, depending on condition.

    Args:
        condition (BoolTensor): When ``True`` (nonzero), yield ``input``, otherwise yield ``other``.
        input (TensorDictBase or Scalar): value (if ``input`` is a scalar) or values selected at indices where condition is ``True``.
        other (TensorDictBase or Scalar): value (if ``other`` is a scalar) or values selected at indices where condition is ``False``.
        out (Tensor, optional): the output ``TensorDictBase`` instance.

    """
    ...

