"""
This type stub file was generated by pyright.
"""

import torch
from typing import Any, Callable, Self, TYPE_CHECKING
from tensordict._tensorcollection import TensorCollection
from tensordict.base import TensorDictBase
from tensordict.tensorclass import TensorClass
from tensordict.utils import IndexType
from torch import Tensor

if TYPE_CHECKING:
    ...
else:
    ...
_TORCH_SHAPE_OPS = ...
class UnbatchedTensor(TensorClass):
    """A TensorClass that represents a tensor whose shape is ignored during shape operations.

    This class allows tensors to be stored in a TensorDict without enforcing batch size consistency.
    Shape operations (e.g., reshape, unsqueeze, squeeze) on the TensorDict will return the same UnbatchedTensor instance,
    while other operations (e.g., apply, key manipulation, pointwise arithmetic) may modify the underlying tensor content.

    Example:
        >>> td = TensorDict(a=UnbatchedTensor(torch.randn(3, 4)), b=torch.randn(2, 3), batch_size=(2,))
        >>> td_reshaped = td.reshape((1, 2))
        >>> td_reshaped["a"] is td["a"]
        True

    Note that accessing an UnbatchedTensor using `get()` and `__getitem__()` will return different results.
    `get()` returns the UnbatchedTensor instance, while `__getitem__()` returns the underlying tensor content.

    Example:
        >>> td.get("a")
        <UnbatchedTensor ...>
        >>> td["a"]
        tensor([[...]])

    """
    data: torch.Tensor | TensorDictBase
    _pass_through = ...
    @classmethod
    def __torch_function__(cls, func: Callable, types: tuple[type, ...], args: tuple[Any, ...] = ..., kwargs: dict[str, Any] | None = ...) -> Callable:
        ...
    
    def chunk(self, chunks: int, dim: int | None = ...): # -> Self:
        ...
    
    def split(self, split_size: int | list[int], dim: int | None = ...): # -> Self:
        ...
    
    def __getitem__(self, index: IndexType) -> Self | Tensor | TensorCollection | Any:
        ...
    
    @property
    def batch_size(self):
        ...
    
    @batch_size.setter
    def batch_size(self, batch_size): # -> None:
        ...
    
    shape = ...
    def unbind(self, dim: int): # -> tuple[Self | Tensor | Any, ...]:
        ...
    
    @_bypass
    def reshape(self, *shape): # -> None:
        ...
    
    @_bypass
    def view(self, *shape): # -> None:
        ...
    
    def unsqueeze(self, dim: int): # -> Self:
        ...
    
    def transpose(self, dim0, dim1): # -> Self:
        ...
    
    def permute(self, *dims): # -> Self:
        ...
    
    @_bypass
    def unflatten(self, dim, unflattened_size): # -> None:
        ...
    
    @_bypass
    def flatten(self, start_dim: int = ..., end_dim=...): # -> None:
        ...
    


