"""
This type stub file was generated by pyright.
"""

import sys
import torch
from pathlib import Path
from typing import Any, Callable, Self, TYPE_CHECKING, overload
from tensordict.utils import IndexType, implement_for

if TYPE_CHECKING:
    ...
else:
    ...
class MemoryMappedTensor(torch.Tensor):
    """A Memory-mapped Tensor.

    Supports filenames or file handlers.

    The main advantage of MemoryMappedTensor resides in its serialization methods,
    which ensure that the tensor is passed through queues or RPC remote calls without
    any copy.

    .. note::
        When used within RPC settings, the filepath should be accessible to both nodes.
        If it isn't the behaviour of passing a MemoryMappedTensor from one worker
        to another is undefined.

    MemoryMappedTensor supports multiple construction methods.

    Examples:
          >>> # from an existing tensor
          >>> tensor = torch.randn(3)
          >>> with tempfile.NamedTemporaryFile() as file:
          ...     memmap_tensor = MemoryMappedTensor.from_tensor(tensor, filename=file.name)
          ...     assert memmap_tensor.filename is not None
          >>> # if no filename is passed, a handler is used
          >>> tensor = torch.randn(3)
          >>> memmap_tensor = MemoryMappedTensor.from_tensor(tensor, filename=file.name)
          >>> assert memmap_tensor.filename is None
          >>> # one can create an empty tensor too
          >>> with tempfile.NamedTemporaryFile() as file:
          ...     memmap_tensor_empty = MemoryMappedTensor.empty_like(tensor, filename=file.name)
          >>> with tempfile.NamedTemporaryFile() as file:
          ...     memmap_tensor_zero = MemoryMappedTensor.zeros_like(tensor, filename=file.name)
          >>> with tempfile.NamedTemporaryFile() as file:
          ...     memmap_tensor = MemoryMappedTensor.ones_like(tensor, filename=file.name)
    """
    _filename: str | Path = ...
    _handler: _FileHandler = ...
    _clear: bool
    index: Any
    parent_shape: torch.Size
    def __new__(cls, source, *, dtype=..., shape=..., index=..., device=..., handler=..., filename=...):
        ...
    
    def __init__(self, source, *, handler=..., dtype=..., shape=..., device=..., filename=...) -> None:
        ...
    
    __torch_function__ = ...
    @classmethod
    def from_tensor(cls, input, *, filename: Path | str = ..., existsok: bool = ..., copy_existing: bool = ..., copy_data: bool = ..., shape: torch.Size | None = ...):
        """Creates a MemoryMappedTensor with the same content as another tensor.

        If the tensor is already a MemoryMappedTensor the original tensor is
        returned if the `filename` argument is `None` or if the two paths match.
        In all other cases, a new :class:`MemoryMappedTensor` is produced.

        Args:
            input (torch.Tensor): the tensor which content must be copied onto
                the MemoryMappedTensor.

        Keyword Args:
            filename (path to a file): the path to the file where the tensor
                should be stored. If none is provided, a file handler is used
                instead.
            existsok (bool, optional): if ``True``, the file will overwrite
                an existing file. Defaults to ``False``.
            copy_existing (bool, optional): if ``True`` and the provided input
                is a MemoryMappedTensor with an associated filename, copying
                the content to the new location is permitted. Otherwise, an
                exception is thrown. This behaviour exists to prevent
                inadvertently duplicating data on disk.
            copy_data (bool, optional): if ``True``, the content of the tensor
                will be copied on the storage. Defaults to ``True``.
            shape (torch.Size or torch.Tensor): a shape to override the tensor
                shape. If a tensor is passed, it must represent the nested shapes of a
                nested tensor.
        """
        ...
    
    @classmethod
    def from_storage(cls, storage, *, shape: torch.Size | None = ..., dtype: torch.dtype | None = ..., device: torch.device | None = ..., index: IndexType | None = ..., filename: Path | str = ..., handler: _handler = ...): # -> Self | Tensor:
        ...
    
    @property
    def filename(self): # -> str | Path:
        """The filename of the tensor, if it has one.

        Raises an exception otherwise.
        """
        ...
    
    @filename.setter
    def filename(self, value): # -> None:
        ...
    
    @classmethod
    def empty_like(cls, input, *, filename=...):
        """Creates a tensor with no content but the same shape and dtype as the input tensor.

        Args:
            input (torch.Tensor): the tensor to use as an example.

        Keyword Args:
            filename (path or equivalent): the path to the file, if any. If none
                is provided, a handler is used.
        """
        ...
    
    @classmethod
    def full_like(cls, input, fill_value, *, filename=...):
        """Creates a tensor with a single content indicated by the `fill_value` argument, but the same shape and dtype as the input tensor.

        Args:
            input (torch.Tensor): the tensor to use as an example.
            fill_value (float or equivalent): content of the tensor.

        Keyword Args:
            filename (path or equivalent): the path to the file, if any. If none
                is provided, a handler is used.
        """
        ...
    
    @classmethod
    def zeros_like(cls, input, *, filename=...):
        """Creates a tensor with a 0-filled content, but the same shape and dtype as the input tensor.

        Args:
            input (torch.Tensor): the tensor to use as an example.

        Keyword Args:
            filename (path or equivalent): the path to the file, if any. If none
                is provided, a handler is used.
        """
        ...
    
    @classmethod
    def ones_like(cls, input, *, filename=...):
        """Creates a tensor with a 1-filled content, but the same shape and dtype as the input tensor.

        Args:
            input (torch.Tensor): the tensor to use as an example.

        Keyword Args:
            filename (path or equivalent): the path to the file, if any. If none
                is provided, a handler is used.
        """
        ...
    
    @classmethod
    @overload
    def ones(cls, *size, dtype=..., device=..., filename=...):
        ...
    
    @classmethod
    @overload
    def ones(cls, shape, *, dtype=..., device=..., filename=...):
        ...
    
    @classmethod
    def ones(cls, *args, **kwargs):
        """Creates a tensor with a 1-filled content, specific shape, dtype and filename.

        Args:
            shape (integers or torch.Size): the shape of the tensor.

        Keyword Args:
            dtype (torch.dtype): the dtype of the tensor.
            device (torch.device): the device of the tensor. Only `None` and `"cpu"`
                are accepted, any other device will raise an exception.
            filename (path or equivalent): the path to the file, if any. If none
                is provided, a handler is used.
            existsok (bool, optional): whether it is ok to overwrite an existing file.
                Defaults to ``False``.
        """
        ...
    
    @classmethod
    @overload
    def zeros(cls, *size, dtype=..., device=..., filename=...):
        ...
    
    @classmethod
    @overload
    def zeros(cls, shape, *, dtype=..., device=..., filename=...):
        ...
    
    @classmethod
    def zeros(cls, *args, **kwargs):
        """Creates a tensor with a 0-filled content, specific shape, dtype and filename.

        Args:
            shape (integers or torch.Size): the shape of the tensor.

        Keyword Args:
            dtype (torch.dtype): the dtype of the tensor.
            device (torch.device): the device of the tensor. Only `None` and `"cpu"`
                are accepted, any other device will raise an exception.
            filename (path or equivalent): the path to the file, if any. If none
                is provided, a handler is used.
            existsok (bool, optional): whether it is ok to overwrite an existing file.
                Defaults to ``False``.
        """
        ...
    
    @classmethod
    @overload
    def empty(cls, *size, dtype=..., device=..., filename=...):
        ...
    
    @classmethod
    @overload
    def empty(cls, shape, *, dtype=..., device=..., filename=...):
        ...
    
    @classmethod
    def empty(cls, *args, **kwargs): # -> Self:
        """Creates a tensor with empty content, specific shape, dtype and filename.

        Args:
            shape (integers or torch.Size): the shape of the tensor.

        Keyword Args:
            dtype (torch.dtype): the dtype of the tensor.
            device (torch.device): the device of the tensor. Only `None` and `"cpu"`
                are accepted, any other device will raise an exception.
            filename (path or equivalent): the path to the file, if any. If none
                is provided, a handler is used.
            existsok (bool, optional): whether it is ok to overwrite an existing file.
                Defaults to ``False``.
        """
        ...
    
    @classmethod
    def empty_nested(cls, *args, **kwargs):
        """Creates a tensor with empty content, specific shape, dtype and filename.

        Args:
            shape (nested_shape): the shapes of the tensors.

        Keyword Args:
            dtype (torch.dtype): the dtype of the tensor.
            device (torch.device): the device of the tensor. Only `None` and `"cpu"`
                are accepted, any other device will raise an exception.
            filename (path or equivalent): the path to the file, if any. If none
                is provided, a handler is used.
            existsok (bool, optional): whether it is ok to overwrite an existing file.
                Defaults to ``False``.
        """
        ...
    
    @classmethod
    @overload
    def full(cls, *size, fill_value, dtype=..., device=..., filename=...):
        ...
    
    @classmethod
    @overload
    def full(cls, shape, *, fill_value, dtype=..., device=..., filename=...):
        ...
    
    @classmethod
    def full(cls, *args, **kwargs):
        """Creates a tensor with a single content specified by `fill_value`, specific shape, dtype and filename.

        Args:
            shape (integers or torch.Size): the shape of the tensor.

        Keyword Args:
            fill_value (float or equivalent): content of the tensor.
            dtype (torch.dtype): the dtype of the tensor.
            device (torch.device): the device of the tensor. Only `None` and `"cpu"`
                are accepted, any other device will raise an exception.
            filename (path or equivalent): the path to the file, if any. If none
                is provided, a handler is used.
            existsok (bool, optional): whether it is ok to overwrite an existing file.
                Defaults to ``False``.
        """
        ...
    
    @classmethod
    def from_filename(cls, filename, dtype, shape, index=...): # -> Self:
        """Loads a MemoryMappedTensor from a given filename.

        Args:
            filename (path or equivalent): the path to the file.
            dtype (torch.dtype): the dtype of the tensor.
            shape (torch.Size or torch.Tensor): the shape of the tensor. If
                a tensor is provided, it is assumed that the tensor is a nested_tensor
                instance.
            index (torch-compatible index type): an index to use to build the
                tensor.

        """
        ...
    
    @classmethod
    def from_handler(cls, handler, dtype, shape, index=...): # -> Self:
        """Loads a MemoryMappedTensor from a given handler.

        Args:
            handler (compatible file handler): the handler for the tensor.
            dtype (torch.dtype): the dtype of the tensor.
            shape (torch.Size or torch.Tensor): the shape of the tensor. If
                a tensor is provided, it is assumed that the tensor is a nested_tensor
                instance.
            index (torch-compatible index type, optional): an index to use to build the
                tensor.

        """
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    
    def __getstate__(self): # -> dict[str, Any]:
        ...
    
    def __reduce_ex__(self, protocol): # -> tuple[Callable[..., Self], tuple[_FileHandler, dtype, Size, Any]] | tuple[Callable[..., Self], tuple[str | Path, dtype, Size, Any]]:
        ...
    
    def __reduce__(self): # -> tuple[Callable[..., Self], tuple[_FileHandler, dtype, Size, Any]] | tuple[Callable[..., Self], tuple[str | Path, dtype, Size, Any]]:
        ...
    
    @implement_for("torch", "2.0", None)
    def __getitem__(self, item: IndexType) -> Self | torch.Tensor:
        ...
    
    @implement_for("torch", None, "2.0")
    def __getitem__(self, item: IndexType) -> Self | torch.Tensor:
        ...
    
    def unbind(self, dim): # -> tuple[Any | MemoryMappedTensor, ...]:
        ...
    
    def chunk(self, chunks, dim=...): # -> tuple[Any | MemoryMappedTensor, ...]:
        ...
    
    def split(self, split_size, dim=...): # -> tuple[Any | MemoryMappedTensor, ...]:
        ...
    


if sys.platform == "win32":
    ...
else:
    class _FileHandler:
        def __init__(self, size, fd=...) -> None:
            ...
        
    
    
MEMMAP_HANDLED_FUNCTIONS: dict[Callable, Callable] = ...
def implements_for_memmap(torch_function: Callable) -> Callable[[Callable], Callable]:
    """Register a torch function override for MemoryMappedTensor."""
    ...

