"""
This type stub file was generated by pyright.
"""

import torch
from typing import Any, Callable, Self, TYPE_CHECKING, Tuple, Type
from tensordict._td import CompatibleType, _TensorDictKeysView
from tensordict._tensorcollection import TensorCollection
from tensordict.base import T, TensorDictBase
from tensordict.memmap import MemoryMappedTensor
from tensordict.utils import IndexType, NestedKey, _as_context_manager, lock_blocked
from torch import Tensor, multiprocessing as mp

"""Persistent tensordicts (H5 and others)."""
_has_h5 = ...
if TYPE_CHECKING:
    ...
else:
    ...
class _Visitor:
    def __init__(self, fun=...) -> None:
        ...
    
    def __call__(self, name): # -> None:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    


class _PersistentTDKeysView(_TensorDictKeysView):
    def __iter__(self): # -> Generator[Any | tuple[Any, ...], Any, None]:
        ...
    
    def __contains__(self, key): # -> bool:
        ...
    


class PersistentTensorDict(TensorDictBase):
    """Persistent TensorDict implementation.

    :class:`PersistentTensorDict` instances provide an interface with data stored
    on disk such that access to this data is made easy while still taking advantage
    from the fast access provided by the backend.

    Like other :class:`TensorDictBase` subclasses, :class:`PersistentTensorDict`
    has a ``device`` attribute. This does *not* mean that the data is being stored
    on that device, but rather that when loaded, the data will be cast onto
    the desired device.

    Keyword Args:
        batch_size (torch.Size or compatible): the tensordict batch size.
            Defaults to ``torch.Size(())``.
        filename (str, optional): the path to the h5 file. Exclusive with ``group``.
        group (h5py.Group, optional): a file or a group that contains data. Exclusive with ``filename``.
        mode (str, optional): Reading mode. Defaults to ``"r"``.
        backend (str, optional): storage backend. Currently only ``"h5"`` is supported.
        device (torch.device or compatible, optional): device of the tensordict.
            Defaults to ``None`` (ie. default PyTorch device).
        **kwargs: kwargs to be passed to :meth:`h5py.File.create_dataset`.

    .. note::
        Currently, PersistentTensorDict instances are not closed when getting out-of-scope.
        This means that it is the responsibility of the user to close them if necessary.

    Examples:
        >>> import tempfile
        >>> with tempfile.NamedTemporaryFile() as f:
        ...     data = PersistentTensorDict(file=f, batch_size=[3], mode="w")
        ...     data["a", "b"] = torch.randn(3, 4)
        ...     print(data)

    """
    _td_dim_names = ...
    LOCKING = ...
    def __init__(self, *, batch_size=..., filename=..., group=..., mode=..., backend=..., device=..., **kwargs) -> None:
        ...
    
    @classmethod
    def from_h5(cls, filename, *, mode=..., batch_size: torch.size | None = ...): # -> Self:
        """Creates a PersistentTensorDict from a h5 file.

        This function will automatically determine the batch-size for each nested tensordict (unless ``batch_size``
        is provided).

        Args:
            filename (str): The path to the h5 file.

        Keyword Args:
            mode (str, optional): Reading mode. Defaults to ``"r"``.
            batch_size (torch.Size, optional): The batch size of the TensorDict. Defaults to None (batch-size automatically
                determined).

        Returns:
            A PersistentTensorDict representation of the input h5 file.

        Examples:
            >>> ptd = PersistentTensorDict.from_h5("path/to/file.h5")
            >>> print(ptd)
            PersistentTensorDict(
                fields={
                    key1: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False),
                    key2: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float32, is_shared=False)},
                batch_size=torch.Size([]),
                device=None,
                is_shared=False)
        """
        ...
    
    @classmethod
    def from_dict(cls, input_dict, filename, *, auto_batch_size: bool = ..., batch_size=..., device=..., **kwargs): # -> Self:
        """Converts a dictionary or a TensorDict to a h5 file.

        Args:
            input_dict (dict, TensorDict or compatible): data to be stored as h5.
            filename (str or path): path to the h5 file.

        Keyword Args:
            auto_batch_size (bool, optional): if ``True``, the batch size will be computed automatically.
                Defaults to ``False``.
            batch_size (tensordict batch-size, optional): if provided, batch size
                of the tensordict. If not, the batch size will be gathered from the
                input structure (if present) or determined automatically.
            device (torch.device or compatible, optional): the device where to
                expect the tensor once they are returned. Defaults to ``None``
                (on cpu by default).
            **kwargs: kwargs to be passed to :meth:`h5py.File.create_dataset`.

        Returns:
            A :class:`PersitentTensorDict` instance linked to the newly created file.

        """
        ...
    
    def close(self): # -> None:
        """Closes the persistent tensordict."""
        ...
    
    _get_tuple = ...
    def get_at(self, key: NestedKey, idx: IndexType, default: CompatibleType = ...) -> CompatibleType:
        ...
    
    def __getitem__(self, item: IndexType) -> Self | Tensor | TensorCollection | Any:
        ...
    
    __getitems__ = ...
    def __setitem__(self, index: IndexType, value: Any): # -> Self | None:
        ...
    
    def keys(self, include_nested: bool = ..., leaves_only: bool = ..., is_leaf: Callable[[Type], bool] | None = ..., *, sort: bool = ...) -> _PersistentTDKeysView:
        ...
    
    @property
    def batch_size(self): # -> Size:
        ...
    
    @batch_size.setter
    def batch_size(self, value): # -> None:
        ...
    
    _erase_names = ...
    names = ...
    _has_names = ...
    def contiguous(self): # -> Self:
        """Materializes a PersistentTensorDict on a regular TensorDict."""
        ...
    
    @lock_blocked
    def del_(self, key): # -> Self:
        ...
    
    def detach_(self): # -> Self:
        ...
    
    @property
    def device(self): # -> device | None:
        ...
    
    def empty(self, recurse=..., *, batch_size=..., device=..., names=...) -> T:
        ...
    
    def zero_(self) -> Self:
        ...
    
    def entry_class(self, key: NestedKey) -> type:
        ...
    
    def is_contiguous(self): # -> Literal[False]:
        ...
    
    def masked_fill(self, mask, value):
        ...
    
    def where(self, condition: torch.Tensor, other: torch.Tensor | TensorDictBase, *, out: TensorDictBase | None = ..., pad: int | bool = ..., update_batch_size: bool = ...):
        ...
    
    def masked_fill_(self, mask, value): # -> Self:
        ...
    
    def make_memmap(self, key: NestedKey, shape: torch.Size | torch.Tensor, *, dtype: torch.dtype | None = ...) -> MemoryMappedTensor:
        ...
    
    def make_memmap_from_storage(self, key: NestedKey, storage: torch.UntypedStorage, shape: torch.Size | torch.Tensor, *, dtype: torch.dtype | None = ...) -> MemoryMappedTensor:
        ...
    
    def make_memmap_from_tensor(self, key: NestedKey, tensor: torch.Tensor, *, copy_data: bool = ...) -> MemoryMappedTensor:
        ...
    
    def memmap_(self, prefix: str | None = ..., copy_existing: bool = ..., num_threads: int = ...) -> PersistentTensorDict:
        ...
    
    _load_memmap = ...
    def pin_memory(self, *args, **kwargs):
        ...
    
    @lock_blocked
    def popitem(self) -> Tuple[NestedKey, CompatibleType]:
        ...
    
    def map(self, fn: Callable, dim: int = ..., num_workers: int | None = ..., *, out: TensorDictBase = ..., chunksize: int | None = ..., num_chunks: int | None = ..., pool: mp.Pool = ..., generator: torch.Generator | None = ..., max_tasks_per_child: int | None = ..., worker_threads: int = ..., index_with_generator: bool = ..., pbar: bool = ..., mp_start_method: str | None = ...): # -> TensorDictBase:
        ...
    
    def rename_key_(self, old_key: NestedKey, new_key: NestedKey, safe: bool = ...) -> PersistentTensorDict:
        ...
    
    def fill_(self, key: NestedKey, value: float | bool) -> TensorDictBase:
        """Fills a tensor pointed by the key with the a given value.

        Args:
            key (str): key to be remaned
            value (Number, bool): value to use for the filling

        Returns:
            self

        """
        ...
    
    @_as_context_manager()
    def flatten_keys(self, separator: str = ..., inplace: bool = ...) -> T:
        ...
    
    @_as_context_manager()
    def unflatten_keys(self, separator: str = ..., inplace: bool = ...) -> T:
        ...
    
    def share_memory_(self):
        ...
    
    def to(self, *args, **kwargs: Any) -> PersistentTensorDict:
        ...
    
    def __getstate__(self): # -> dict[str, Any]:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    
    def chunk(self, chunks: int, dim: int = ...) -> tuple[TensorDictBase, ...]:
        ...
    
    __eq__ = ...
    __ne__ = ...
    __xor__ = ...
    __or__ = ...
    __ge__ = ...
    __gt__ = ...
    __le__ = ...
    __lt__ = ...
    _apply_nest = ...
    _cast_reduction = ...
    _check_device = ...
    _check_is_shared = ...
    _convert_to_tensordict = ...
    _get_names_idx = ...
    _index_tensordict = ...
    _multithread_apply_flat = ...
    _multithread_rebuild = ...
    _to_module = ...
    _unbind = ...
    all = ...
    any = ...
    expand = ...
    from_dict_instance = ...
    masked_select = ...
    _repeat = ...
    _repeat = ...
    repeat_interleave = ...
    reshape = ...
    split = ...


