"""
This type stub file was generated by pyright.
"""

import collections
import importlib.util
import math
import sys
import torch
from collections import defaultdict
from collections.abc import KeysView
from typing import Any, List, Sequence, TYPE_CHECKING, Tuple, TypeVar, Union
from tensordict._nestedkey import NestedKey
from torch import Tensor
from torch.nn.parameter import UninitializedBuffer, UninitializedParameter
from torch.utils._contextlib import _DecoratorContextManager
from functorch import dim as ftdim
from tensordict.base import TensorDictBase

_has_funcdim = ...
if TYPE_CHECKING:
    ...
if not _has_funcdim:
    class _ftdim_mock:
        class Dim:
            ...
        
        
        class Tensor:
            ...
        
        
        def dims(self, *args, **kwargs):
            ...
        
    
    
    ftdim = ...
T = TypeVar("T", bound="TensorDictBase")
_PIN_MEM_TIMEOUT = ...
_TORCH_DTYPES = ...
if hasattr(torch, "uint16"):
    _TORCH_DTYPES = ...
if hasattr(torch, "uint32"):
    _TORCH_DTYPES = ...
if hasattr(torch, "uint64"):
    _TORCH_DTYPES = ...
_STR_DTYPE_TO_DTYPE = ...
_STRDTYPE2DTYPE = ...
_DTYPE_TO_STR_DTYPE = ...
_DTYPE2STRDTYPE = ...
IndexType = Union[None, int, slice, str, Tensor, List[Any], Tuple[Any, ...]]
DeviceType = Union[torch.device, str, int]
_KEY_ERROR = ...
_LOCK_ERROR = ...
LOGGING_LEVEL = ...
logger = ...
console_handler = ...
formatter = ...
def strtobool(val): # -> Literal[1, 0]:
    """Convert a string representation of truth to true (1) or false (0).

    True values are 'y', 'yes', 't', 'true', 'on', and '1'; false values
    are 'n', 'no', 'f', 'false', 'off', and '0'.  Raises ValueError if
    'val' is anything else.
    """
    ...

def convert_ellipsis_to_idx(idx: tuple[int | Ellipsis] | Ellipsis, batch_size: list[int]) -> tuple[int, ...]:
    """Given an index containing an ellipsis or just an ellipsis, converts any ellipsis to slice(None).

    Example:
        >>> idx = (..., 0)
        >>> batch_size = [1,2,3]
        >>> new_index = convert_ellipsis_to_idx(idx, batch_size)
        >>> print(new_index)
        (slice(None, None, None), slice(None, None, None), 0)

    Args:
        idx (tuple, Ellipsis): Input index
        batch_size (list): Shape of tensor to be indexed

    Returns:
        new_index (tuple): Output index
    """
    ...

def infer_size_impl(shape: list[int], numel: int) -> list[int]:
    """Infers the shape of an expanded tensor whose number of elements is indicated by :obj:`numel`.

    Copied from pytorch for compatibility issues (See #386).
    See https://github.com/pytorch/pytorch/blob/35d4fa444b67cbcbe34a862782ddf2d92f5b1ce7/torch/jit/_shape_functions.py
    for the original copy.

    """
    ...

if hasattr(math, "prod"):
    def prod(sequence): # -> int:
        """General prod function, that generalised usage across math and np.

        Created for multiple python versions compatibility.

        """
        ...
    
else:
    def prod(sequence): # -> int:
        """General prod function, that generalised usage across math and np.

        Created for multiple python versions compatibility.

        """
        ...
    
def expand_as_right(tensor: torch.Tensor | TensorDictBase, dest: torch.Tensor | TensorDictBase) -> torch.Tensor | TensorDictBase:
    """Expand a tensor on the right to match another tensor shape.

    Args:
        tensor: tensor to be expanded
        dest: tensor providing the target shape

    Returns:
         a tensor with shape matching the dest input tensor shape.

    Examples:
        >>> tensor = torch.zeros(3,4)
        >>> dest = torch.zeros(3,4,5)
        >>> print(expand_as_right(tensor, dest).shape)
        torch.Size([3,4,5])

    """
    ...

def expand_right(tensor: Tensor, shape: Sequence[int]) -> Tensor:
    """Expand a tensor on the right to match a desired shape.

    Args:
        tensor: tensor to be expanded
        shape: target shape

    Returns:
         a tensor with shape matching the target shape.

    Examples:
        >>> tensor = torch.zeros(3,4)
        >>> shape = (3,4,5)
        >>> print(expand_right(tensor, shape).shape)
        torch.Size([3,4,5])

    """
    ...

NUMPY_TO_TORCH_DTYPE_DICT = ...
TORCH_TO_NUMPY_DTYPE_DICT = ...
def is_nested_key(key: NestedKey) -> bool:
    """Returns True if key is a NestedKey."""
    ...

def is_seq_of_nested_key(seq: Sequence[NestedKey]) -> bool:
    """Returns True if seq is a Sequence[NestedKey]."""
    ...

class timeit:
    """A dirty but easy to use decorator for profiling code."""
    _REG = ...
    def __init__(self, name) -> None:
        ...
    
    def __call__(self, fn): # -> _Wrapped:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    
    @staticmethod
    def print(prefix=...): # -> None:
        ...
    
    @staticmethod
    def erase(): # -> None:
        ...
    


def int_generator(seed): # -> int:
    """A pseudo-random chain generator.

    To be used to produce deterministic integer sequences

    Examples:
        >>> for _ in range(2):
        ...     init_int = 10
        ...     for _ in range(10):
        ...        init_int = int_generator(init_int)
        ...        print(init_int, end=", ")
        ...     print("")
        6756, 1717, 4410, 9740, 9611, 9716, 5397, 7745, 4521, 7523,
        6756, 1717, 4410, 9740, 9611, 9716, 5397, 7745, 4521, 7523,
    """
    ...

def is_tensorclass(obj: type | Any) -> bool:
    """Returns True if obj is either a tensorclass or an instance of a tensorclass."""
    ...

_TENSORCLASS_MEMO = ...
def cache(fun): # -> _Wrapped:
    """A cache for TensorDictBase subclasses.

    This decorator will cache the values returned by a method as long as the
    input arguments match.
    Leaves (tensors and such) are not cached.
    The cache is stored within the tensordict such that it can be erased at any
    point in time.

    Examples:
        >>> import timeit
        >>> from tensordict import TensorDict
        >>> class SomeOtherTd(TensorDict):
        ...     @cache
        ...     def all_keys(self):
        ...         return set(self.keys(include_nested=True))
        >>> td = SomeOtherTd({("a", "b", "c", "d", "e", "f", "g"): 1.0}, [])
        >>> td.lock_()
        >>> print(timeit.timeit("set(td.keys(True))", globals={'td': td}))
        11.057
        >>> print(timeit.timeit("set(td.all_keys())", globals={'td': td}))
        0.88
    """
    ...

def erase_cache(fun): # -> _Wrapped:
    """A decorator to erase the cache at each call."""
    ...

_NON_STR_KEY_TUPLE_ERR = ...
_NON_STR_KEY_ERR = ...
_GENERIC_NESTED_ERR = ...
class _StringKeys(KeysView):
    """A key view where contains is restricted to strings.

    Saving the keys as an attribute is 25% faster than just subclassing KeysView.

    """
    def __init__(self, keys) -> None:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __contains__(self, item):
        ...
    


_StringOnlyDict = dict
def lock_blocked(func): # -> _Wrapped:
    """Checks that the tensordict is unlocked before executing a function."""
    ...

class _ErrorInteceptor:
    """Context manager for catching errors and modifying message.

    Intended for use with stacking / concatenation operations applied to TensorDicts.

    """
    DEFAULT_EXC_MSG = ...
    def __init__(self, key: NestedKey, prefix: str, exc_msg: str | None = ..., exc_type: type[Exception] | None = ...) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, exc_type, exc_value, _): # -> None:
        ...
    


def assert_close(actual: T, expected: T, rtol: float | None = ..., atol: float | None = ..., equal_nan: bool = ..., intersection: bool = ..., msg: str = ..., prefix: NestedKey = ...) -> bool:
    """Asserts that two tensordicts, `actual` and `expected`, are element-wise equal within a tolerance for all entries.

    This function checks if the elements of the `actual` tensor are close to the corresponding elements
    of the `expected` tensordict, within a relative tolerance (`rtol`) and an absolute tolerance (`atol`).

    It is similar to the :func:`~torch.testing.assert_close` function in PyTorch, but with tensordicts inputs.

    Args:
        actual (T): The tensordict containing actual values.
        expected (T): The tensordict containing expected values.
        rtol (float | None, optional): The relative tolerance parameter. Default is None.
        atol (float | None, optional): The absolute tolerance parameter. Default is None.
        equal_nan (bool, optional): If True, ``NaNs`` will be considered equal to ``NaNs``. Default is ``True``.
        intersection (bool, optional): If True, only the intersection of the two tensordicts will be compared.
            Default is ``False``.
        msg (str, optional): An optional message to include in the assertion error if the check fails.
        prefix (NestedKey, optional): a prefix to add to the key for error messages.

    Returns:
        bool: True if the tensors are close within the specified tolerances, raise an exception otherwise.

    Raises:
        AssertionError: If the tensordicts are not close within the specified tolerances.

    """
    ...

if hasattr(torch.nn, "Buffer"):
    _parent_buffer_cls = ...
    class Buffer:
        ...
    
    
    class _BufferMeta:
        ...
    
    
else:
    class _BufferMeta(torch._C._TensorMeta):
        def __instancecheck__(self, instance): # -> bool:
            ...
        
    
    
    class Buffer(torch.Tensor, metaclass=_BufferMeta):
        """A replicate of torch.nn.Buffer if not available (prior to torch v2.5)."""
        def __new__(cls, data=..., *, persistent=...): # -> Tensor:
            ...
        
        __torch_function__ = ...
    
    
    _parent_buffer_cls = ...
class BufferLegacy(_parent_buffer_cls):
    """A buffer subclass that keeps the grad fn history."""
    def __new__(cls, data=..., *, persistent=...): # -> Tensor:
        ...
    


_DEFAULT_LAZY_OP = ...
_LAZY_OP = ...
class set_lazy_legacy(_DecoratorContextManager):
    """Sets the behaviour of some methods to a lazy transform.

    These methods include :meth:`~tensordict.TensorDict.view`, :meth:`~tensordict.TensorDict.permute`,
    :meth:`~tensordict.TensorDict.transpose`, :meth:`~tensordict.TensorDict.squeeze`
    and :meth:`~tensordict.TensorDict.unsqueeze`.

    This property is dynamic, ie. it can be changed during the code execution, but
    it won't propagate to sub-processes unless it has been called before the process
    has been created.

    """
    def __init__(self, mode: bool) -> None:
        ...
    
    def clone(self) -> set_lazy_legacy:
        ...
    
    def __enter__(self) -> None:
        ...
    
    def set(self) -> None:
        ...
    
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        ...
    


def lazy_legacy(allow_none=...): # -> bool | Literal[1, 0] | None:
    """Returns `True` if lazy representations will be used for selected methods."""
    ...

_DEFAULT_CAPTURE_NONTENSOR_STACK = ...
_CAPTURE_NONTENSOR_STACK = ...
class set_capture_non_tensor_stack(_DecoratorContextManager):
    """A context manager or decorator to control whether identical non-tensor data should be stacked into a single NonTensorData object or a NonTensorStack.

    Args:
        mode (bool): Whether to capture non-tensor stacks. If ``False``, identical
            non-tensor data will be stacked into a :class:`~tensordict.NonTensorStack`. If ``True``,
            a single :class:`~tensordict.NonTensorData` object will contain the unique value, but with the desired batch-size.
            Defaults to ``True``.

    .. note:: Since v0.9, `capture_non_tensor_stack()` returns `False` by default.
        You can set the value of :func:`~tensordict.capture_non_tensor_stack` through:

        - The ``CAPTURE_NON_TENSOR_STACK`` environment variable;
        - By setting ``set_capture_non_tensor_stack(val: bool).set()`` at the beginning of your script;
        - By using ``set_capture_non_tensor_stack(val: bool)`` as a context manager or a decorator.

        It is recommended to use the `set_capture_non_tensor_stack(False)` behavior.

    .. seealso:: :class:`~tensordict.capture_non_tensor_stack`

    Examples:
        >>> with set_capture_non_tensor_stack(False):
        ...     torch.stack([NonTensorData("a"), NonTensorData("a")])
        NonTensorData("a", batch_size=[2])
        >>> @set_capture_non_tensor_stack(False)
        ... def my_function():
        ...     return torch.stack([NonTensorData("a"), NonTensorData("a")])
        >>> my_function()
        NonTensorStack(["a", "a"], stack_dim=0)
    """
    def __init__(self, mode: bool) -> None:
        ...
    
    def clone(self) -> set_capture_non_tensor_stack:
        ...
    
    def __enter__(self) -> None:
        ...
    
    def set(self) -> None:
        ...
    
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        ...
    


def capture_non_tensor_stack(allow_none=...): # -> bool | Literal[1, 0] | None:
    """Get the current setting for capturing non-tensor stacks.

    Args:
        allow_none (bool, optional): If ``True``, returns ``None`` if no setting has been
            specified. Otherwise, returns the default setting. Defaults to ``False``.

    seealso: :func:`~tensordict.set_capture_non_tensor_stack`

    Returns:
        bool or None: The current setting for capturing non-tensor stacks.

    """
    ...

_DEFAULT_LIST_TO_STACK = ...
_LIST_TO_STACK = ...
class set_list_to_stack(_DecoratorContextManager):
    """Context manager and decorator to control the behavior of list handling in TensorDict.

    When enabled, lists assigned to a TensorDict will be automatically stacked along the batch dimension.
    This can be useful for ensuring that lists of tensors or other elements are treated as stackable entities
    within a TensorDict.

    Current Behavior:
        If a list is assigned to a TensorDict without this context manager, it will be converted to a numpy array
            and wrapped in a NonTensorData if it cannot be cast to a Tensor.

    Args:
        mode (bool): If True, enables list-to-stack conversion. If False, disables it.

    Example:
        >>> with set_list_to_stack(True):
        ...     td = TensorDict(a=[torch.zeros(()), torch.ones(())], batch_size=2)
        ...     assert (td["a"] == torch.tensor([0, 1])).all()
        ...     assert td[0]["a"] == 0
        ...     assert td[1]["a"] == 1

    .. seealso:: :func:`~tensordict.list_to_stack`.

    """
    def __init__(self, mode: bool) -> None:
        ...
    
    def clone(self) -> set_list_to_stack:
        ...
    
    def __enter__(self) -> None:
        ...
    
    def set(self) -> None:
        ...
    
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        ...
    


def list_to_stack(allow_none=...): # -> bool | Literal['1', 1, 0] | None:
    """Retrieves the current setting for list-to-stack conversion in TensorDict.

    This function checks the global environment variable or the context manager setting to determine
    whether lists should be automatically stacked when assigned to a TensorDict.

    Current Behavior:
        Returns the current setting for list-to-stack conversion. If the setting is not defined and `allow_none`
            is True, it returns None. Otherwise, it returns the default setting.

    Args:
        allow_none (bool): If True, allows the function to return None if the setting is not defined.

    Returns:
        bool or None: The current setting for list-to-stack conversion.

    .. seealso:: :class:`~tensordict.set_list_to_stack`.

    """
    ...

class TensorDictFuture:
    """A custom future class for TensorDict multithreaded operations.

    Args:
        futures (list of futures): a list of concurrent.futures.Future objects to wait for.
        resulting_td (TensorDictBase): instance that will result from the futures
            completing.

    """
    def __init__(self, futures, resulting_td) -> None:
        ...
    
    def result(self): # -> Any:
        """Wait and returns the resulting tensordict."""
        ...
    


def print_directory_tree(path, indent=..., display_metadata=...) -> str:
    """Prints the directory tree starting from the specified path.

    Args:
        path (str): The path of the directory to print.
        indent (str): The current indentation level for formatting.
        display_metadata (bool): if ``True``, metadata of the dir will be
            displayed too.

    Returns:
        the string printed with the logger.

    """
    ...

def isin(input: TensorDictBase, reference: TensorDictBase, key: NestedKey, dim: int = ...) -> Tensor:
    """Tests if each element of ``key`` in input ``dim`` is also present in the reference.

    This function returns a boolean tensor of length  ``input.batch_size[dim]`` that is ``True`` for elements in
    the entry ``key`` that are also present in the ``reference``. This function assumes that both ``input`` and
    ``reference`` have the same batch size and contain the specified entry, otherwise an error will be raised.

    Args:
        input (TensorDictBase): Input TensorDict.
        reference (TensorDictBase): Target TensorDict against which to test.
        key (Nestedkey): The key to test.
        dim (int, optional): The dimension along which to test. Defaults to ``0``.

    Returns:
        out (Tensor): A boolean tensor of length ``input.batch_size[dim]`` that is ``True`` for elements in
            the ``input`` ``key`` tensor that are also present in the ``reference``.

    Examples:
        >>> td = TensorDict(
        ...     {
        ...         "tensor1": torch.tensor([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9]]),
        ...         "tensor2": torch.tensor([[10, 20], [30, 40], [40, 50], [50, 60]]),
        ...     },
        ...     batch_size=[4],
        ... )
        >>> td_ref = TensorDict(
        ...     {
        ...         "tensor1": torch.tensor([[1, 2, 3], [4, 5, 6], [10, 11, 12]]),
        ...         "tensor2": torch.tensor([[10, 20], [30, 40], [50, 60]]),
        ...     },
        ...     batch_size=[3],
        ... )
        >>> in_reference = isin(td, td_ref, key="tensor1")
        >>> expected_in_reference = torch.tensor([True, True, True, False])
        >>> torch.testing.assert_close(in_reference, expected_in_reference)
    """
    ...

def remove_duplicates(input: TensorDictBase, key: NestedKey, dim: int = ..., *, return_indices: bool = ...) -> TensorDictBase:
    """Removes indices duplicated in `key` along the specified dimension.

    This method detects duplicate elements in the tensor associated with the specified `key` along the specified
    `dim` and removes elements in the same indices in all other tensors within the TensorDict. It is expected for
    `dim` to be one of the dimensions within the batch size of the input TensorDict to ensure consistency in all
    tensors. Otherwise, an error will be raised.

    Args:
        input (TensorDictBase): The TensorDict containing potentially duplicate elements.
        key (NestedKey): The key of the tensor along which duplicate elements should be identified and removed. It
            must be one of the leaf keys within the TensorDict, pointing to a tensor and not to another TensorDict.
        dim (int, optional): The dimension along which duplicate elements should be identified and removed. It must be one of
            the dimensions within the batch size of the input TensorDict. Defaults to ``0``.
        return_indices (bool, optional): If ``True``, the indices of the unique elements in the input tensor will be
            returned as well. Defaults to ``False``.

    Returns:
        output (TensorDictBase): input tensordict with the indices corrsponding to duplicated elements
            in tensor `key` along dimension `dim` removed.
        unique_indices (torch.Tensor, optional): The indices of the first occurrences of the unique elements in the
            input tensordict for the specified `key` along the specified `dim`. Only provided if return_index is True.

    Example:
        >>> td = TensorDict(
        ...     {
        ...         "tensor1": torch.tensor([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9]]),
        ...         "tensor2": torch.tensor([[10, 20], [30, 40], [40, 50], [50, 60]]),
        ...     }
        ...     batch_size=[4],
        ... )
        >>> output_tensordict = remove_duplicate_elements(td, key="tensor1", dim=0)
        >>> expected_output = TensorDict(
        ...     {
        ...         "tensor1": torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
        ...         "tensor2": torch.tensor([[10, 20], [30, 40], [50, 60]]),
        ...     },
        ...     batch_size=[3],
        ... )
        >>> assert (td == expected_output).all()
    """
    ...

class _CloudpickleWrapper:
    def __init__(self, fn) -> None:
        ...
    
    def __getstate__(self): # -> bytes:
        ...
    
    def __setstate__(self, ob: bytes): # -> None:
        ...
    
    def __call__(self, *args, **kwargs): # -> Any:
        ...
    


class _BatchedUninitializedParameter(UninitializedParameter):
    batch_size: torch.Size
    in_dim: int | None = ...
    vmap_level: int | None = ...
    def materialize(self, shape, device=..., dtype=...): # -> None:
        ...
    


class _BatchedUninitializedBuffer(UninitializedBuffer):
    batch_size: torch.Size
    in_dim: int | None = ...
    vmap_level: int | None = ...
    def materialize(self, shape, device=..., dtype=...): # -> None:
        ...
    


class _add_batch_dim_pre_hook:
    def __call__(self, mod: torch.nn.Module, args, kwargs): # -> None:
        ...
    


def is_non_tensor(data) -> bool:
    """Checks if an item is a non-tensor."""
    ...

_NON_TENSOR_MEMO = ...
_PASSTHROUGH_MEMO = ...
class KeyDependentDefaultDict(collections.defaultdict):
    """A key-dependent default dict.

    Examples:
        >>> my_dict = KeyDependentDefaultDict(lambda key: "foo_" + key)
        >>> print(my_dict["bar"])
        foo_bar
    """
    def __init__(self, fun) -> None:
        ...
    
    def __missing__(self, key):
        ...
    


def is_namedtuple(obj): # -> bool:
    """Check if obj is a namedtuple."""
    ...

def is_namedtuple_class(cls): # -> bool:
    """Check if a class is a namedtuple class."""
    ...

def unravel_key(key): # -> str | tuple[Any | str | tuple[Any, ...], ...]:
    """Unravel a nested key.

    Examples:
        >>> unravel_key("a")
        "a"
        >>> unravel_key(("a",))
        "a"
        >>> unravel_key((("a", ("b",))))
        ("a", "b")

    """
    ...

def unravel_keys(*keys): # -> tuple[Any | str | tuple[Any | str | tuple[Any, ...], ...], ...]:
    """Unravels a sequence of keys."""
    ...

def unravel_key_list(keys): # -> list[Any | str | tuple[Any | str | tuple[Any, ...], ...]]:
    """Unravels a list of keys."""
    ...

assert_allclose_td = ...
NESTED_TENSOR_ERR = ...
_DEVICE2STRDEVICE = ...
_lock_warn = ...
_check_inbuild = ...
if sys.version_info >= (3, 10):
    _zip_strict = ...
else:
    ...
def parse_tensor_dict_string(s: str): # -> TensorDict:
    """Parse a TensorDict repr to a TensorDict.

    .. note::
        This functions is intended to be used for debugging, to reproduce a tensordict
        given its printed version, and should not be used in real applications.

    """
    ...

class _ContextManager:
    def __init__(self, default=...) -> None:
        ...
    
    def get_mode(self) -> Any | None:
        ...
    
    def set_mode(self, type: Any | None) -> None:
        ...
    


def json_dumps(data, **kwargs): # -> bytes:
    """Unified JSON serialization function that works with both json and orjson backends."""
    ...

def set_json_backend(backend): # -> None:
    """Set the JSON backend to use (either 'json' or 'orjson')."""
    ...

def get_json_backend(): # -> Any:
    """Get the current JSON backend."""
    ...

if importlib.util.find_spec("orjson") is not None:
    ...
else:
    ...
class LinkedList(list):
    """A thin wrapper around a list that automatically updates a tensordict when the list is modified."""
    def __init__(self, *args, td: TensorDictBase, **kwargs) -> None:
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def append(self, object: Any) -> None:
        ...
    
    def extend(self, object: Any) -> None:
        ...
    
    def insert(self, index: int, object: Any) -> None:
        ...
    
    def pop(self, index: int = ...) -> Any:
        ...
    
    def remove(self, value: Any) -> None:
        ...
    
    def clear(self) -> None:
        ...
    
    def __delitem__(self, index: int) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __eq__(self, other: Any) -> bool:
        ...
    
    def __ne__(self, other: Any) -> bool:
        ...
    
    def __getstate__(self) -> object:
        ...
    
    def __iadd__(self, other: Any) -> Any:
        ...
    
    def __imul__(self, other: Any) -> Any:
        ...
    


