"""
This type stub file was generated by pyright.
"""

import torch

class Logger:
    """Logger to save the learning metrics to different logging services."""
    def __init__(self, log_dir: str | None, cfg: dict, env_cfg: dict | object, num_envs: int, is_distributed: bool, gpu_world_size: int, gpu_global_rank: int, device: str) -> None:
        """Initialize buffers and logging state for a training run."""
        ...
    
    def init_logging_writer(self) -> None:
        """Initialize the logging writer, which can be either Tensorboard, W&B or Neptune and save the code state.

        If the writer is either W&B or Neptune, the configuration and code state are uploaded as well.
        """
        ...
    
    def process_env_step(self, rewards: torch.Tensor, dones: torch.Tensor, extras: dict, intrinsic_rewards: torch.Tensor | None = ...) -> None:
        """Add metrics from the environment step to the buffers."""
        ...
    
    def log(self, it: int, start_it: int, total_it: int, collect_time: float, learn_time: float, loss_dict: dict, learning_rate: float, action_std: torch.Tensor, rnd_weight: float | None, print_minimal: bool = ..., width: int = ..., pad: int = ...) -> None:
        """Log the training metrics to the logging service and print them to the console.

        If videos are available, they are uploaded to the logging service (W&B) as well.
        """
        ...
    
    def save_model(self, path: str, it: int) -> None:
        """Save the model to external logging services if specified."""
        ...
    
    def stop_logging_writer(self) -> None:
        """Stop the logging writer."""
        ...
    


