"""
This type stub file was generated by pyright.
"""

from torch.utils.tensorboard import SummaryWriter

class NeptuneSummaryWriter(SummaryWriter):
    """Summary writer for Neptune."""
    def __init__(self, log_dir: str, flush_secs: int, cfg: dict) -> None:
        """Initialize a Neptune run for logging."""
        ...
    
    def store_config(self, env_cfg: dict | object, train_cfg: dict) -> None:
        """Upload environment and training configuration to Neptune."""
        ...
    
    def add_scalar(self, tag: str, scalar_value: float, global_step: int | None = ..., walltime: float | None = ..., new_style: bool = ...) -> None:
        """Log a scalar to both TensorBoard and Neptune."""
        ...
    
    def stop(self) -> None:
        """Finish the active Neptune run."""
        ...
    
    def save_model(self, model_path: str, it: int) -> None:
        """Upload a model checkpoint artifact to Neptune."""
        ...
    
    def save_file(self, path: str) -> None:
        """Upload an arbitrary file artifact to Neptune."""
        ...
    


