"""
This type stub file was generated by pyright.
"""

import pathlib
from torch.utils.tensorboard import SummaryWriter

class WandbSummaryWriter(SummaryWriter):
    """Summary writer for W&B."""
    def __init__(self, log_dir: str, flush_secs: int, cfg: dict) -> None:
        """Initialize a W&B run for logging."""
        ...
    
    def store_config(self, env_cfg: dict | object, train_cfg: dict) -> None:
        """Upload environment and training configuration to W&B."""
        ...
    
    def add_scalar(self, tag: str, scalar_value: float, global_step: int | None = ..., walltime: float | None = ..., new_style: bool = ...) -> None:
        """Log a scalar to both TensorBoard and W&B."""
        ...
    
    def stop(self) -> None:
        """Finish the active W&B run."""
        ...
    
    def save_model(self, model_path: str, it: int) -> None:
        """Upload a model checkpoint artifact to W&B."""
        ...
    
    def save_file(self, path: str) -> None:
        """Upload an arbitrary file artifact to W&B."""
        ...
    
    def save_video(self, video: pathlib.Path, it: int) -> None:
        """Upload a video artifact once per filename to W&B."""
        ...
    


