"""
This type stub file was generated by pyright.
"""

from .cnn_model import CNNModel
from .mlp_model import MLPModel
from .rnn_model import RNNModel

"""Neural models for the learning algorithm."""
__all__ = ["CNNModel", "MLPModel", "RNNModel"]
