"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn
from tensordict import TensorDict
from typing import Any
from rsl_rl.models.mlp_model import MLPModel
from rsl_rl.modules import HiddenState

class CNNModel(MLPModel):
    """CNN-based neural model.

    This model uses one or more convolutional neural network (CNN) encoders to process one or more 2D observation groups
    before passing the resulting latent to an MLP. Any 1D observation groups are directly concatenated with the CNN
    latent and passed to the MLP. 1D observations can be normalized before being passed to the MLP. The output of the
    model can be either deterministic or stochastic, in which case a distribution module is used to sample the outputs.
    """
    def __init__(self, obs: TensorDict, obs_groups: dict[str, list[str]], obs_set: str, output_dim: int, hidden_dims: tuple[int, ...] | list[int] = ..., activation: str = ..., obs_normalization: bool = ..., distribution_cfg: dict | None = ..., cnn_cfg: dict[str, dict] | dict[str, Any] | None = ..., cnns: nn.ModuleDict | dict[str, nn.Module] | None = ...) -> None:
        """Initialize the CNN-based model.

        Args:
            obs: Observation Dictionary.
            obs_groups: Dictionary mapping observation sets to lists of observation groups.
            obs_set: Observation set to use for this model (e.g., "actor" or "critic").
            output_dim: Dimension of the output.
            hidden_dims: Hidden dimensions of the MLP.
            activation: Activation function of the CNN and MLP.
            obs_normalization: Whether to normalize the observations before feeding them to the MLP.
            distribution_cfg: Configuration dictionary for the output distribution.
            cnn_cfg: Configuration of the CNN encoder(s).
            cnns: CNN modules to use, e.g., for sharing CNNs between actor and critic. If None, new CNNs are created.
        """
        ...
    
    def get_latent(self, obs: TensorDict, masks: torch.Tensor | None = ..., hidden_state: HiddenState = ...) -> torch.Tensor:
        """Build the model latent by combining normalized 1D and CNN-encoded 2D observation groups."""
        ...
    
    def as_jit(self) -> nn.Module:
        """Return a version of the model compatible with Torch JIT export."""
        ...
    
    def as_onnx(self, verbose: bool = ...) -> nn.Module:
        """Return a version of the model compatible with ONNX export."""
        ...
    


class _TorchCNNModel(nn.Module):
    """Exportable CNN model for JIT."""
    def __init__(self, model: CNNModel) -> None:
        """Create a TorchScript-friendly copy of a CNNModel."""
        ...
    
    def forward(self, obs_1d: torch.Tensor, obs_2d: list[torch.Tensor]) -> torch.Tensor:
        """Run deterministic inference from separated 1D and 2D inputs."""
        ...
    
    @torch.jit.export
    def reset(self) -> None:
        """Reset recurrent export state (no-op for CNN exports)."""
        ...
    


class _OnnxCNNModel(nn.Module):
    """Exportable CNN model for ONNX."""
    def __init__(self, model: CNNModel, verbose: bool) -> None:
        """Create an ONNX-export wrapper around a CNNModel."""
        ...
    
    def forward(self, obs_1d: torch.Tensor, *obs_2d: torch.Tensor) -> torch.Tensor:
        """Run deterministic inference for ONNX export."""
        ...
    
    def get_dummy_inputs(self) -> tuple[torch.Tensor, ...]:
        """Return representative dummy inputs for ONNX tracing."""
        ...
    
    @property
    def input_names(self) -> list[str]:
        """Return ONNX input tensor names."""
        ...
    
    @property
    def output_names(self) -> list[str]:
        """Return ONNX output tensor names."""
        ...
    


