"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn
from tensordict import TensorDict
from rsl_rl.modules import HiddenState

class MLPModel(nn.Module):
    """MLP-based neural model.

    This model uses a simple multi-layer perceptron (MLP) to process 1D observation groups. Observations can be
    normalized before being passed to the MLP. The output of the model can be either deterministic or
    stochastic, in which case a distribution module is used to sample the outputs.
    """
    is_recurrent: bool = ...
    def __init__(self, obs: TensorDict, obs_groups: dict[str, list[str]], obs_set: str, output_dim: int, hidden_dims: tuple[int, ...] | list[int] = ..., activation: str = ..., obs_normalization: bool = ..., distribution_cfg: dict | None = ...) -> None:
        """Initialize the MLP-based model.

        Args:
            obs: Observation Dictionary.
            obs_groups: Dictionary mapping observation sets to lists of observation groups.
            obs_set: Observation set to use for this model (e.g., "actor" or "critic").
            output_dim: Dimension of the output.
            hidden_dims: Hidden dimensions of the MLP.
            activation: Activation function of the MLP.
            obs_normalization: Whether to normalize the observations before feeding them to the MLP.
            distribution_cfg: Configuration dictionary for the output distribution. If provided, the model outputs
                stochastic values sampled from the distribution.
        """
        ...
    
    def forward(self, obs: TensorDict, masks: torch.Tensor | None = ..., hidden_state: HiddenState = ..., stochastic_output: bool = ...) -> torch.Tensor:
        """Forward pass of the MLP model.

        ..note::
            The `stochastic_output` flag only has an effect if the model has a distribution (i.e., ``distribution_cfg``
            was provided) and defaults to ``False``, meaning that even stochastic models will return deterministic
            outputs by default.
        """
        ...
    
    def get_latent(self, obs: TensorDict, masks: torch.Tensor | None = ..., hidden_state: HiddenState = ...) -> torch.Tensor:
        """Build the model latent by concatenating and normalizing selected observation groups."""
        ...
    
    def reset(self, dones: torch.Tensor | None = ..., hidden_state: HiddenState = ...) -> None:
        """Reset the internal state for recurrent models (no-op)."""
        ...
    
    def get_hidden_state(self) -> HiddenState:
        """Return the recurrent hidden state (``None`` for MLP)."""
        ...
    
    def detach_hidden_state(self, dones: torch.Tensor | None = ...) -> None:
        """Detach therecurrent hidden state for truncated backpropagation (no-op)."""
        ...
    
    @property
    def output_mean(self) -> torch.Tensor:
        """Return the mean of the current output distribution."""
        ...
    
    @property
    def output_std(self) -> torch.Tensor:
        """Return the standard deviation of the current output distribution."""
        ...
    
    @property
    def output_entropy(self) -> torch.Tensor:
        """Return the entropy of the current output distribution."""
        ...
    
    @property
    def output_distribution_params(self) -> tuple[torch.Tensor, ...]:
        """Return raw parameters of the current output distribution."""
        ...
    
    def get_output_log_prob(self, outputs: torch.Tensor) -> torch.Tensor:
        """Compute log-probabilities of outputs under the current distribution."""
        ...
    
    def get_kl_divergence(self, old_params: tuple[torch.Tensor, ...], new_params: tuple[torch.Tensor, ...]) -> torch.Tensor:
        """Compute KL divergence between two parameterizations of the distribution."""
        ...
    
    def as_jit(self) -> nn.Module:
        """Return a version of the model compatible with Torch JIT export."""
        ...
    
    def as_onnx(self, verbose: bool) -> nn.Module:
        """Return a version of the model compatible with ONNX export."""
        ...
    
    def update_normalization(self, obs: TensorDict) -> None:
        """Update observation-normalization statistics from a batch of observations."""
        ...
    


class _TorchMLPModel(nn.Module):
    """Exportable MLP model for JIT."""
    def __init__(self, model: MLPModel) -> None:
        """Create a TorchScript-friendly copy of an MLPModel."""
        ...
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Run deterministic inference on pre-concatenated observations."""
        ...
    
    @torch.jit.export
    def reset(self) -> None:
        """Reset recurrent export state (no-op for MLP exports)."""
        ...
    


class _OnnxMLPModel(nn.Module):
    """Exportable MLP model for ONNX."""
    is_recurrent: bool = ...
    def __init__(self, model: MLPModel, verbose: bool) -> None:
        """Create an ONNX-export wrapper around an MLPModel."""
        ...
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Run deterministic inference for ONNX export."""
        ...
    
    def get_dummy_inputs(self) -> tuple[torch.Tensor]:
        """Return representative dummy inputs for ONNX tracing."""
        ...
    
    @property
    def input_names(self) -> list[str]:
        """Return ONNX input tensor names."""
        ...
    
    @property
    def output_names(self) -> list[str]:
        """Return ONNX output tensor names."""
        ...
    


