"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn
from tensordict import TensorDict
from rsl_rl.models.mlp_model import MLPModel
from rsl_rl.modules import HiddenState

class RNNModel(MLPModel):
    """RNN-based neural model.

    This model uses a recurrent neural network (RNN) to process 1D observation groups before passing the resulting
    latent to an MLP. Available RNN types are "lstm" and "gru". Observations can be normalized before being passed to
    the RNN. The output of the model can be either deterministic or stochastic, in which case a distribution module is
    used to sample the outputs.
    """
    is_recurrent: bool = ...
    def __init__(self, obs: TensorDict, obs_groups: dict[str, list[str]], obs_set: str, output_dim: int, hidden_dims: tuple[int, ...] | list[int] = ..., activation: str = ..., obs_normalization: bool = ..., distribution_cfg: dict | None = ..., rnn_type: str = ..., rnn_hidden_dim: int = ..., rnn_num_layers: int = ...) -> None:
        """Initialize the RNN-based model.

        Args:
            obs: Observation Dictionary.
            obs_groups: Dictionary mapping observation sets to lists of observation groups.
            obs_set: Observation set to use for this model (e.g., "actor" or "critic").
            output_dim: Dimension of the output.
            hidden_dims: Hidden dimensions of the MLP.
            activation: Activation function of the MLP.
            obs_normalization: Whether to normalize the observations before feeding them to the MLP.
            distribution_cfg: Configuration dictionary for the output distribution.
            rnn_type: Type of RNN to use ("lstm" or "gru").
            rnn_hidden_dim: Dimension of the RNN hidden state.
            rnn_num_layers: Number of RNN layers.
        """
        ...
    
    def get_latent(self, obs: TensorDict, masks: torch.Tensor | None = ..., hidden_state: HiddenState = ...) -> torch.Tensor:
        """Build the model latent by passing normalized observation groups through the RNN."""
        ...
    
    def reset(self, dones: torch.Tensor | None = ..., hidden_state: HiddenState = ...) -> None:
        """Reset the recurrent hidden state of the RNN."""
        ...
    
    def get_hidden_state(self) -> HiddenState:
        """Return the recurrent hidden state of the RNN."""
        ...
    
    def detach_hidden_state(self, dones: torch.Tensor | None = ...) -> None:
        """Detach the recurrent hidden state for truncated backpropagation."""
        ...
    
    def as_jit(self) -> nn.Module:
        """Return a version of the model compatible with Torch JIT export."""
        ...
    
    def as_onnx(self, verbose: bool = ...) -> nn.Module:
        """Return a version of the model compatible with ONNX export."""
        ...
    


class _TorchGRUModel(nn.Module):
    """Exportable GRU model for JIT."""
    def __init__(self, model: RNNModel) -> None:
        """Create a TorchScript-friendly copy of a GRU-based RNNModel."""
        ...
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Run one GRU inference step and update hidden states."""
        ...
    
    @torch.jit.export
    def reset(self) -> None:
        """Reset exported GRU hidden states to zeros."""
        ...
    


class _TorchLSTMModel(nn.Module):
    """Exportable LSTM model for JIT."""
    def __init__(self, model: RNNModel) -> None:
        """Create a TorchScript-friendly copy of an LSTM-based RNNModel."""
        ...
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Run one LSTM inference step and update hidden and cell states."""
        ...
    
    @torch.jit.export
    def reset(self) -> None:
        """Reset exported LSTM hidden and cell states to zeros."""
        ...
    


class _OnnxRNNModel(nn.Module):
    """Exportable RNN model for ONNX."""
    is_recurrent: bool = ...
    def __init__(self, model: RNNModel, verbose: bool) -> None:
        """Create an ONNX-export wrapper around an RNNModel."""
        ...
    
    def forward(self, obs: torch.Tensor, h_in: torch.Tensor, c_in: torch.Tensor | None = ...) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor | None]:
        """Run deterministic inference for ONNX export."""
        ...
    
    def get_dummy_inputs(self) -> tuple[torch.Tensor, ...]:
        """Return representative dummy inputs for ONNX tracing."""
        ...
    
    @property
    def input_names(self) -> list[str]:
        """Return ONNX input tensor names."""
        ...
    
    @property
    def output_names(self) -> list[str]:
        """Return ONNX output tensor names."""
        ...
    


