"""
This type stub file was generated by pyright.
"""

"""
Check OS requirements for ONNX Runtime Python Bindings.
"""
def check_distro_info(): # -> None:
    ...

def get_package_name_and_version_info(): # -> tuple[Literal['onnxruntime', ''], Literal['1.24.4', ''], Any | Literal['']]:
    ...

def check_training_module(): # -> tuple[bool, Literal['onnxruntime', ''], Literal['1.24.4', ''], Any | Literal['']]:
    ...

