"""
This type stub file was generated by pyright.
"""

from rsl_rl.algorithms import Distillation
from rsl_rl.runners import OnPolicyRunner

class DistillationRunner(OnPolicyRunner):
    """Distillation runner for student-teacher algorithms."""
    alg: Distillation
    def learn(self, num_learning_iterations: int, init_at_random_ep_len: bool = ...) -> None:
        """Run the learning loop after validating that the teacher model is loaded."""
        ...
    


