"""
This type stub file was generated by pyright.
"""

from rsl_rl.algorithms import PPO
from rsl_rl.env import VecEnv
from rsl_rl.models import MLPModel

class OnPolicyRunner:
    """On-policy runner for reinforcement learning algorithms."""
    alg: PPO
    def __init__(self, env: VecEnv, train_cfg: dict, log_dir: str | None = ..., device: str = ...) -> None:
        """Construct the runner, algorithm, and logging stack."""
        ...
    
    def learn(self, num_learning_iterations: int, init_at_random_ep_len: bool = ...) -> None:
        """Run the learning loop for the specified number of iterations."""
        ...
    
    def save(self, path: str, infos: dict | None = ...) -> None:
        """Save the models and training state to a given path and upload them if external logging is used."""
        ...
    
    def load(self, path: str, load_cfg: dict | None = ..., strict: bool = ..., map_location: str | None = ...) -> dict:
        """Load the models and training state from a given path.

        Args:
            path (str): Path to load the model from.
            load_cfg (dict | None): Optional dictionary that defines what models and states to load. If None, all
                models and states are loaded.
            strict (bool): Whether state_dict loading should be strict.
            map_location (str | None): Device mapping for loading the model.
        """
        ...
    
    def get_inference_policy(self, device: str | None = ...) -> MLPModel:
        """Return the policy on the requested device for inference."""
        ...
    
    def export_policy_to_jit(self, path: str, filename: str = ...) -> None:
        """Export the model to a Torch JIT file."""
        ...
    
    def export_policy_to_onnx(self, path: str, filename: str = ..., verbose: bool = ...) -> None:
        """Export the model into an ONNX file."""
        ...
    
    def add_git_repo_to_log(self, repo_file_path: str) -> None:
        """Register a repository path whose git status should be logged."""
        ...
    


