from _typeshed import Incomplete
from bam.actuator import ArrayLike as ArrayLike, VoltageControlledActuator as VoltageControlledActuator
from bam.message import bright as bright, print_parameter as print_parameter, yellow as yellow
from bam.parameter import Parameter as Parameter
from bam.testbench import Pendulum as Pendulum, Testbench as Testbench

class STS3215Actuator(VoltageControlledActuator):
    default_max_velocity: Incomplete
    def __init__(self, testbench_class: Testbench) -> None: ...
    def get_extra_inertia(self) -> float: ...
    q_target_smooth: Incomplete
    def load_log(self, log: dict): ...
    def initialize(self) -> None: ...
    def compute_control(self, q_target: ArrayLike, q: ArrayLike, dq: ArrayLike, dt: float) -> ArrayLike | None: ...
